New Components - seqera
PipedreamHQ/pipedream pull request #10236
Opened 2024-02-05 20:58 UTC by jcortes

Resolves #10218.

2024-02-08 11:26 UTC, lcaresia requested changes

2024-02-08 11:26 UTC, lcaresia commented on components/seqera/actions/create-action/create-action.mjs
> +      ],
Move this to an constants.mjs file

```suggestion
      options: constants.SOURCES,
```

2024-02-15 07:15 UTC, hungv-turing commented on components/seqera/actions/create-action/create-action.mjs
> +  description: "Creates a new pipeline action in Seqera. [See the documentation](https://docs.seqera.io/platform/23.3.0/api/overview)",
```suggestion
  description: "Creates a new pipeline action in Seqera. [See the documentation](https://tower.nf/openapi/index.html#post-/pipelines)",
```

2024-02-15 07:15 UTC, hungv-turing commented on components/seqera/actions/create-action/create-action.mjs
> +      description: "The launch configuration of the action to create",
```suggestion
      description: "The launch configuration of the action to create. For the model reference look [here](https://tower.nf/openapi/index.html#post-/pipelines)",
```

2024-02-15 19:24 UTC, merged