Google drive usability improvements
PipedreamHQ/pipedream pull request #11652
Opened 2024-04-26 01:59 UTC by GTFalcao

2024-04-29 13:40 UTC, luancazarine submitted a review, later dismissed
Hi @GTFalcao, thanks for your contribution! LGTM!

2024-05-07 00:28 UTC, GTFalcao commented
@vunguyenhung , as I understand it, these sources are also triggered for new files/folders, or in other situations that do not necessarily have 'changes' to be emitted - do you think we should emit an empty 'changes' object to maintain the schema in this case?

2024-05-07 13:12 UTC, GTFalcao commented
/approve

2024-05-07 13:36 UTC, luancazarine requested changes
Hi @GTFalcao, I just added a minor change request.

2024-05-07 13:36 UTC, luancazarine commented on components/google_drive/actions/add-file-sharing-preference/add-file-sharing-preference.mjs
> +  version: "0.1.{{ts}}",
please set the version.

2024-05-07 16:54 UTC, GTFalcao commented on components/google_drive/actions/add-file-sharing-preference/add-file-sharing-preference.mjs
> +  version: "0.1.{{ts}}",
Thanks for catching that! Fixed

2024-05-07 16:55 UTC, GTFalcao commented
/approve

2024-05-07 17:13 UTC, merged