[Components] recruitis #11523
PipedreamHQ/pipedream pull request #11903
Opened 2024-05-09 21:28 UTC by lcaresia

## WHY

2024-05-16 11:44 UTC, lcaresia commented
@luancazarine For some reason script don't assigned an reviewer, so I assigned you manually.

2024-05-16 12:02 UTC, luancazarine submitted a review, later dismissed
Hi @lcaresia, thanks for your contribution! LGTM!

2024-05-22 11:21 UTC, lcaresia commented
/approve

2024-05-22 12:29 UTC, luancazarine requested changes
Hi @lcaresia, I just added a minor change request.

2024-05-22 12:29 UTC, luancazarine commented on components/recruitis/actions/create-answer/create-answer.mjs
> +  version: "0.0.{{ts}}",
```suggestion
  version: "0.0.1",
```

2024-05-23 01:20 UTC, lcaresia commented
/approve

2024-05-23 12:23 UTC, luancazarine approved these changes

2024-05-27 12:27 UTC, merged