Webflow V2 migration
PipedreamHQ/pipedream pull request #14734
Opened 2024-11-26 06:58 UTC by GTFalcao

Closes #14688

2024-11-29 15:11 UTC, luancazarine requested changes
Hi @GTFalcao, I just added some suggestions about versions.

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/create-collection-item/create-collection-item.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/delete-collection-item/delete-collection-item.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/get-collection-item/get-collection-item.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/get-collection/get-collection.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/get-item-inventory/get-item-inventory.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/get-order/get-order.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/get-site/get-site.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/list-collection-items/list-collection-items.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/list-collections/list-collections.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/list-orders/list-orders.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/list-sites/list-sites.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/publish-site/publish-site.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/refund-order/refund-order.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/unfulfill-order/unfulfill-order.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/update-collection-item/update-collection-item.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/update-item-inventory/update-item-inventory.mjs
>    version: "0.0.5",
```suggestion
  version: "0.0.6",
```

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/actions/update-order/update-order.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/sources/changed-collection-item/changed-collection-item.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/sources/changed-ecommerce-inventory/changed-ecommerce-inventory.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/sources/new-site-published/new-site-published.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/sources/new-form-submission/new-form-submission.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/sources/new-ecommerce-order/new-ecommerce-order.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/sources/new-deleted-collection-item/new-deleted-collection-item.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/sources/new-collection-item/new-collection-item.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 15:11 UTC, luancazarine commented on components/webflow_v2/sources/changed-ecommerce-order/changed-ecommerce-order.mjs
> +  version: "0.0.{{ts}}",
Please set the right version

2024-11-29 17:54 UTC, GTFalcao commented
Thanks for the notes @luancazarine , the version numbers were left as-is temporarily to speed up testing on this, and I'll set them all to 0.0.1 when the migration is ready to be released

2024-12-02 04:02 UTC, GTFalcao commented
/approve

2024-12-02 16:26 UTC, luancazarine approved these changes

2024-12-02 17:22 UTC, merged