[ACTIONS] Trello actions
PipedreamHQ/pipedream pull request #1639
Opened 2021-08-26 17:43 UTC by sergioeliot2039

Created Trello actions:

- [ ] Find a List
- [ ] Find a Label
- [ ] Search Boards
- [ ] Search Cards
- [ ] Create a Card
- [ ] Move Card to List
- [ ] Get Card 
- [ ] Update Card
- [ ] List Rename
- [ ] Add Attachment to Card via URL
- [ ] Add Existing Label to Card
- [ ] Add a Member to a Card
- [ ] Archive Card
- [ ] Create Label
- [ ] Remove Label From Card
- [ ] Close a Board
- [ ] Create a Checklist Item
- [ ] Create a Comment
- [ ] Create a Checklist
- [ ] Delete a Checklist

Development notes: sources were modify to comply with ESlint spell check, but no functionality was changed. Sources were not tested after the ESlinit fixes (most of them done in auto, except declared variables that were not used in code, which were removed manually)

2021-09-22 13:27 UTC, compwright commented
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2021-09-22 19:06 UTC, compwright requested changes
Thanks for the extensive set of new actions, @sergioeliot2039! This needs some work to comply with these guidelines:

- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

I've also made a number of specific suggestions to address various issues.

Finally, I've noticed that we aren't handling API retries, and I recommend adding that.

2022-01-25 00:22 UTC, isaiahtaylor commented
Hi, is anything blocking this PR? Creating a new Trello card would be super helpful!

2022-01-25 22:14 UTC, sergioeliot2039 commented
> Hi, is anything blocking this PR? Creating a new Trello card would be super helpful!

I have this on my radar. 
There is a Trello card, it is related to issue #1402 
![attachment-about-trello-card-on-github-issue-for-trello](https://user-images.githubusercontent.com/25184117/151068489-210b9963-1752-4f4f-ba2d-83928b06dbac.png)

Unsure why there are two issues for Trello actions, though

2026-08-08 04:46 UTC, closed without merging