Jotform new actions
PipedreamHQ/pipedream pull request #1802
Opened 2021-10-18 21:54 UTC by michelle0927

Adds new actions:
**Get Monthly User Usage**
**Get Form Submissions**
**Get User Submissions**

And adds pagination to the `formId` prop.

2021-10-18 21:54 UTC, dylburger commented
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling soures, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2021-12-02 17:55 UTC, vellames-turing requested changes
Hey, the code looks great.
- Could you please add a `summary` to the actions?
- Could you please add the doc link to the actions?
- It would be nice if you could use pipedream axios

2021-12-02 17:55 UTC, vellames-turing commented on components/jotform/actions/common.mjs
> +        if (items.length < limit) return;
Could you please add the brackets here?

2021-12-02 17:55 UTC, vellames-turing commented on components/jotform/jotform.app.mjs
> +      if (str.endsWith("/")) return str;
Maybe you can add a ternary here?

2021-12-02 17:55 UTC, vellames-turing commented on components/jotform/jotform.app.mjs
> +      return (await this._makeRequest(
I guess you dont need this await here

2021-12-02 17:55 UTC, vellames-turing commented on components/jotform/actions/get-user-submissions/get-user-submissions.mjs
> +    const submissions = await this.paginate(this.jotform.getUserSubmissions.bind(this));
Can you add a `max` property to avoid long paginations?

2021-12-02 17:55 UTC, vellames-turing commented on components/jotform/actions/get-form-submissions/get-form-submissions.mjs
> +    const submissions = await this.paginate(this.jotform.getFormSubmissions.bind(this), params);
Can you add a `max` property to avoid long paginations?

2021-12-06 18:41 UTC, vellames-turing approved these changes
Looks great for me. Approved!

2022-01-26 04:28 UTC, dannyroosevelt commented
@michelle0927 getting an error on async options 
![image](https://user-images.githubusercontent.com/20780753/151104042-175a4d87-e0c4-4bd9-82b9-1168cf02262a.png)

2022-01-26 04:32 UTC, dannyroosevelt commented
looks good, @michelle0927 plz merge away!

2022-01-26 15:47 UTC, merged