[ACTION] Zoho CRM
PipedreamHQ/pipedream pull request #2012
Opened 2022-01-05 12:57 UTC by vellames-turing

New Actions

- [ ] Please provide a link to the relevant API docs for the specific service / operation.
- [ ] Add Attachment - Add attachment to the slected Module entry
- [ ] Add Tag - Add new tag to existing module entries
- [ ] Convert Lead - Convert an existing lead to contact and account
- [ ] Create Module Entry - Create module entry if entry does not exist
- [ ] Create New Entry - Creates a new entry in a module
- [ ] Create/Update Module Entry - Create or update module entries
- [ ] Find Module Entry Finds an entry in a module
- [ ] Find or Create Contact - Create contact if contact does not exist
- [ ] Find or Create Lead - Create Lead if contact does not exist
- [ ] Update Module Entry - Update existing entry in the selected module
- [ ] Update Related Module Entry - Relates an entry in this module with an entry in another module

Sources Refactors

- [ ] New Contract
- [ ] New Event
- [ ] New Lead
- [ ] New Module Entry
- [ ] New or Updated Contract
- [ ] New or Updated Lead
- [ ] New or Updated Module Entry
- [ ] New User
- [ ] Updated Module Entry

Others

- [ ] Refactor Code Base

2022-01-05 12:57 UTC, dylburger commented
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-01-05 12:58 UTC, vellames-turing commented
Related: #1379

2022-03-10 21:34 UTC, js07 requested changes
@michelle0927 I made some comments, but looks good overall!

2022-03-10 21:34 UTC, js07 commented on components/zoho_crm/zoho_crm.app.mjs
> +      description: "Use this key to associate a contact with the lead being converted. Pass the unique and valid contact ID.",
```suggestion
      description: "Use this key to assign record owner for the new contact and account. Pass the unique and valid user ID.",
```

2022-03-10 21:34 UTC, js07 commented on components/zoho_crm/zoho_crm.app.mjs
> +      });
Remove this `console.log`?

2022-03-10 21:34 UTC, js07 commented on components/zoho_crm/zoho_crm.app.mjs
> +      const { data } = await axios(this, url, requestConfig);
Should this be `const data =` since axios is replaced with `@pipedream/platform` axios?

2022-03-10 21:34 UTC, js07 commented on components/zoho_crm/zoho_crm.app.mjs
> +        url: `https://www.zohoapis.com/crm/v2.1${opts.path}`,
Is there a reason to use `crm/v2.1` instead of `crm/v2` (`this._apiUrl()`)?

2022-03-10 21:34 UTC, js07 commented on components/zoho_crm/zoho_crm.app.mjs
> +    _getAxiosParams(opts) {
**-Minor-**
I'd suggest naming this method `_getRequestParams` or `_makeRequestConfig` so its intended usage can be understood by someone who doesn't know what axios is.

2022-03-10 21:34 UTC, js07 commented on components/zoho_crm/zoho_crm.app.mjs
> -      return this.$auth.oauth_access_token;
Was this method (`_authToken`) intended to be removed? It looks like it's still used in `_makeRequestConfig()`.

2022-03-11 21:10 UTC, js07 reviewed
@michelle0927 Thanks for making those changes! I made a couple comments.

2022-03-11 23:46 UTC, js07 submitted a review, later dismissed
Looks good to me.

2022-03-18 17:34 UTC, dannyroosevelt commented
@vellames-turing merge when ready!

2022-03-18 17:35 UTC, dannyroosevelt commented
@vellames-turing does anything need to happen with https://github.com/PipedreamHQ/pipedream/pull/1379? or is that PR superseded by this one?

2022-04-07 17:30 UTC, DilanAthukorala commented
Observing following issue for create-object  (Creating Campaigns)

![image](https://user-images.githubusercontent.com/102980146/162262181-6a39bb95-f536-49bb-9bcf-f526f0cbb3c2.png)

2022-04-07 18:17 UTC, DilanAthukorala commented
@michelle0927 Thank you. 

Verification completed successfully.

2022-04-07 18:42 UTC, dannyroosevelt approved these changes

2022-04-07 18:45 UTC, merged