Google analytics new goals source
PipedreamHQ/pipedream pull request #2131
Opened 2022-01-26 21:01 UTC by andrewjschuang

Google Analytics

New Goals | Triggers when a new goal is added.

2022-01-26 21:02 UTC, andrewjschuang commented
The OAuth authentication is missing some Analytics scopes

2022-01-26 21:02 UTC, dylburger commented
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-02-22 20:33 UTC, michelle0927 requested changes

2022-02-22 20:33 UTC, michelle0927 commented on components/google_analytics/actions/list-goals/list-goals.mjs
> +  description: "Lists goals to which the user has access",
Include a link to the docs for actions:
```suggestion
  description: "Lists goals to which the user has access. [See the docs here](https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/goals/list)",
```

2022-02-22 20:33 UTC, michelle0927 commented on components/google_analytics/actions/list-goals/list-goals.mjs
> +    },
I don't think `token` is necessary since we have `this.$auth.oauth_access_token`.
```suggestion
```

2022-02-22 20:33 UTC, michelle0927 commented on components/google_analytics/actions/list-goals/list-goals.mjs
> +    },
`accountId`, `webPropertyId`, and `profileId` should all have `async options` that list the accounts, web properties, and profiles that the user has access to. You could have them default to "~all".

2022-02-22 20:33 UTC, michelle0927 commented on components/google_analytics/actions/list-goals/list-goals.mjs
> +    },
I'd leave in `maxResults`, but take out `startIndex` and handle pagination in the component.
```suggestion
```

2022-02-22 20:33 UTC, michelle0927 commented on components/google_analytics/actions/list-goals/list-goals.mjs
> +    let params = {
We should declare variables as constants whenever we can.
```suggestion
    const params = {
```

2022-02-22 20:33 UTC, michelle0927 commented on components/google_analytics/actions/list-goals/list-goals.mjs
> +    );
`response` should be a constant. We can remove `token`. Then put this call in a loop that handles pagination.
```suggestion
    const response = await this.analytics.listGoals(
      params,
    );
```

2022-02-22 20:33 UTC, michelle0927 commented on components/google_analytics/google_analytics.app.mjs
> +    },
I don't think `token` is needed.
```suggestion
```

2022-02-22 20:33 UTC, michelle0927 commented on components/google_analytics/google_analytics.app.mjs
> +    },
As mentioned above, `accountId`, `webPropertyId`, and `profileId` should use async options if possible.

2022-02-22 20:33 UTC, michelle0927 commented on components/google_analytics/google_analytics.app.mjs
> +    },
I don't see `goalId` being used anywhere, so I think it can be removed.
```suggestion
```

2022-02-22 20:33 UTC, michelle0927 commented on components/google_analytics/google_analytics.app.mjs
> +      });
I think we can just use the `oauth_access_token`.
```suggestion
    _getAnalyticsInstance() {
      const auth = new google.auth.OAuth2();
      auth.setCredentials({
        access_token: this.$auth.oauth_access_token,
      });
```

2022-02-22 20:33 UTC, michelle0927 commented on components/google_analytics/google_analytics.app.mjs
> +    },
```suggestion
    _getGoalsInstance() {
      return this._getAnalyticsInstance().management.goals;
    },
```

2022-02-22 20:33 UTC, michelle0927 commented on components/google_analytics/google_analytics.app.mjs
> +      return (await this._getGoalsInstance(token).list(params)).data;
```suggestion
    async listGoals(params) {
      return (await this._getGoalsInstance().list(params)).data;
```

2022-02-22 20:33 UTC, michelle0927 commented on components/google_analytics/sources/new-goal/new-goal.mjs
> +    let params = {
```suggestion
    const params = {
```

2022-02-22 20:33 UTC, michelle0927 commented on components/google_analytics/sources/new-goal/new-goal.mjs
> +      "profileId": "~all",
Could we have `accountId`, `webPropertyId`, and `profileId` as props in this component? Then the user can select which ones to watch.

2022-02-22 20:33 UTC, michelle0927 commented on components/google_analytics/sources/new-goal/new-goal.mjs
> +    let response = await this.analytics.listGoals(null, params);
```suggestion
    const response = await this.analytics.listGoals(null, params);
```

2022-02-23 14:56 UTC, andrewjschuang commented
Thanks @michelle0927 for the review!
I will proceed to make the changes requested after the authentication scopes are added.

2026-08-08 00:39 UTC, GTFalcao commented
Closing as outdated and blocked

2026-08-08 00:39 UTC, closed without merging