[ACTIONS] Monday new actions
PipedreamHQ/pipedream pull request #2155
Opened 2022-01-31 20:32 UTC by jcortes

# [Actions](#1769)
- [x] Create an Item | Creates an item
- [x] Update Item Name | Update an item's name
- [x] Create a Board | Creates a new board
- [x] Create a Group | Creates a new group in a specific board
- [x] Create an Update | Creates a new update

2022-01-31 20:33 UTC, dylburger commented
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-02-01 17:55 UTC, michelle0927 requested changes
I wasn't able to get the `workspaceId` prop to work in create-board.mjs. I have 2 workspaces in my account, but it always displays: **No matching options**. Is it displaying them properly for you?

2022-02-01 17:55 UTC, michelle0927 commented on components/monday/actions/create-board/create-board.mjs
> +      throw new Error(`Fail to create board: ${errorMessage}`);
```suggestion
      throw new Error(`Failed to create board: ${errorMessage}`);
```

2022-02-01 17:55 UTC, michelle0927 commented on components/monday/actions/create-group/create-group.mjs
> +      throw new Error(`Fail to create group: ${errorMessage}`);
```suggestion
      throw new Error(`Failed to create group: ${errorMessage}`);
```

2022-02-01 17:55 UTC, michelle0927 commented on components/monday/actions/create-update/create-update.mjs
> +      throw new Error(`Failed to create update with errors: ${errors[0].message}`);
```suggestion
      throw new Error(`Failed to create update: ${errors[0].message}`);
```

2022-02-01 17:55 UTC, michelle0927 commented on components/monday/actions/create-update/create-update.mjs
> +      throw new Error(`Failed to create update with message: ${errorMessage}`);
```suggestion
      throw new Error(`Failed to create update: ${errorMessage}`);
```

2022-02-01 17:55 UTC, michelle0927 commented on components/monday/actions/update-item-name/update-item-name.mjs
> +      throw new Error(`Failed to update the item name with errors: ${errors[0].message}`);
```suggestion
      throw new Error(`Failed to update the item name: ${errors[0].message}`);
```

2022-02-01 17:55 UTC, michelle0927 commented on components/monday/actions/update-item-name/update-item-name.mjs
> +      throw new Error(`Failed to update the item name with error message: ${errorMessage}`);
```suggestion
      throw new Error(`Failed to update the item name: ${errorMessage}`);
```

2022-02-01 17:55 UTC, michelle0927 commented on components/monday/actions/update-item-name/update-item-name.mjs
> +    $.export("$summary", `Successfully updated item name: ${updateItemId}`);
Optional, but maybe include the new item name in the summary?
```suggestion
    $.export("$summary", `Successfully updated item ${updateItemId} name to ${this.itemName}`);
```

2022-02-01 17:55 UTC, michelle0927 commented on components/monday/common/base.mjs
> +};
This file isn't being used by any components. I think it can be removed.

2022-02-01 17:55 UTC, michelle0927 commented on components/monday/monday.app.mjs
> +        }
Is this `if` statement needed? I tried removing it, and it appears to work the same. It's present in props `workspaceId`, `groupId`, and `itemId`.

2022-02-01 18:29 UTC, jcortes commented
> I wasn't able to get the `workspaceId` prop to work in create-board.mjs. I have 2 workspaces in my account, but it always displays: **No matching options**. Is it displaying them properly for you?

Yeah I think you migth need to initiate the workflow either by clicking on `Add from templates` or `Start from scratch` using whe Monday's UI then you will be able to list those workspaces using the API

2022-02-01 18:43 UTC, michelle0927 requested changes

2022-02-01 18:43 UTC, michelle0927 commented on components/monday/actions/create-board/create-board.mjs
> +  version: "0.0.35",
```suggestion
  version: "0.0.1",
```

2022-02-01 18:50 UTC, michelle0927 approved these changes
Approved!

2022-02-08 05:59 UTC, dannyroosevelt commented
Everything looks great except I'm running into an issue with the `templateId` prop in the Create Board action:
![GIF 2-7-2022 at 9 56 46 PM](https://user-images.githubusercontent.com/20780753/152927256-fee82a23-4c90-4bce-8fee-70cc77df532e.gif)
![image](https://user-images.githubusercontent.com/20780753/152927310-d540b91b-364c-4d1b-a0a9-ae9d6df52aa1.png)

2022-02-16 20:44 UTC, jcortes commented
> Everything looks great except I'm running into an issue with the `templateId` prop in the Create Board action: ...
@dannyroosevelt it's kind of weird because it seems like you have a previous version since the `templateId` property doesn't have options. Can you do a pull again to make sure you have latest version?

2022-02-24 23:21 UTC, dannyroosevelt commented
@jcortes were you able to create a new board? I can't seem to find the right permissions to do so
![image](https://user-images.githubusercontent.com/20780753/155624035-515ac341-e387-4f6a-8421-d92ece9fde16.png)

2022-03-08 22:29 UTC, jcortes commented
> @jcortes were you able to create a new board? I can't seem to find the right permissions to do so ![image](https://user-images.githubusercontent.com/20780753/155624035-515ac341-e387-4f6a-8421-d92ece9fde16.png)

Hi @dannyroosevelt can you please `pull` this PR and try again with this version please? Make sure you are using the Admin role. Thanks!

2022-03-08 22:47 UTC, jcortes commented
> @jcortes were you able to create a new board? I can't seem to find the right permissions to do so ![image](https://user-images.githubusercontent.com/20780753/155624035-515ac341-e387-4f6a-8421-d92ece9fde16.png)

Hi @dannyroosevelt I've found some issues with Monday API using *Template ID* property so I removed it. Here you can see  the [issue](https://community.monday.com/t/error-format-thrown-by-api-changed-without-notice/12723).

2022-03-14 20:46 UTC, michelle0927 requested changes

2022-03-14 20:46 UTC, michelle0927 commented on components/monday/actions/create-board/create-board.mjs
> +  async run({ $ }) {
I tried adding `templateId` back in and couldn't get it to work with any of the "predefined templates" (the ones you added to templates.mjs). It always returns this error:

`Failed to create board [CreateBoardException]: Failed to create board from predefined template`

However, I did get it to work using the templateId/boardId of a board I had "Saved as template". I think we should leave `templateId` in as an optional integer field, and let the user enter a templateId if they have one.

```suggestion
    },
    templateId: {
       propDefinition: [
          monday,
          "templateId",
       ],
    },
  },
  async run({ $ }) {
```

2022-03-14 20:46 UTC, michelle0927 commented on components/monday/actions/create-board/create-board.mjs
> +    } = this;
```suggestion
      workspaceId,
      templateId,
    } = this;
```

2022-03-14 20:46 UTC, michelle0927 commented on components/monday/actions/create-board/create-board.mjs
> +      });
```suggestion
        folderId: utils.emptyStrToUndefined(folderId),
        workspaceId: utils.emptyStrToUndefined(workspaceId),
        templateId: utils.emptyStrToUndefined(templateId),
      });
```

2022-03-14 20:46 UTC, michelle0927 commented on components/monday/monday.app.mjs
> +  },
```suggestion
    },
    templateId: {
      type: "integer",
      label: "Template ID",
      description: "Board template ID",
      optional: true,
    },
  },
```

2022-03-15 15:33 UTC, michelle0927 approved these changes

2022-03-15 19:56 UTC, merged