Intercom - New Actions
PipedreamHQ/pipedream pull request #2196
Opened 2022-02-07 19:32 UTC by michelle0927

New actions:
**Create a Note** | Creates a note for a specific user
**Send Incoming Message** | Send a message from a user into your Intercom app

Addresses issue: https://github.com/PipedreamHQ/pipedream/issues/1499

2022-02-07 19:32 UTC, dylburger commented
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-02-17 22:09 UTC, jcortes requested changes
Looks good to me. Just a few comments (optional suggestions).

2022-02-17 22:09 UTC, jcortes commented on components/intercom/actions/create-note/create-note.mjs
> +    $.export("summary", "Successfully created note");
Optionally I guess you can show the note id here
```suggestion
    const res = await this.intercom.createNote(userId, adminId, body, $);
    $.export("summary", `Successfully created note with ID ${res.id}`);
```

2022-02-17 22:09 UTC, jcortes commented on components/intercom/actions/send-incoming-message/send-incoming-message.mjs
> +    $.export("summary", "Message sent successfully");
```suggestion
    const res = await this.intercom.createConversation(data, $);
    $.export("summary", `Message sent successfully with ID ${res.id}`);
```

2022-02-17 22:09 UTC, jcortes commented on components/intercom/intercom.app.mjs
> +          : `https://api.intercom.io/${endpoint}`,
```suggestion
        url: url ?? `https://api.intercom.io/${endpoint}`,
```

2022-02-17 22:09 UTC, jcortes commented on components/intercom/intercom.app.mjs
> +      return await axios($ || this, config);
Optionally I would remove this `await` and others in `return` statement.

2022-02-17 22:09 UTC, jcortes commented on components/intercom/intercom.app.mjs
> +          : ""}`;
Optionally. I think these lines are a little hard to understand, Maybe I would recommend doing it like this?
```suggestion
        const search = isSearch && "/search" || "";
        const startingAfterParam = startingAfter && `?starting_after=${startingAfter}` || "";
        const endpoint = `${itemType}${search}${startingAfterParam}`;
```

2022-02-17 22:09 UTC, jcortes commented on components/intercom/package.json
> -        "axios": "^0.21.1"
I think you should uninstall `axios` and then `npm i @pipedream/platform`

2022-02-22 15:51 UTC, jcortes approved these changes
It looks good to me, thanks!

2022-03-03 19:03 UTC, dannyroosevelt commented
@michelle0927 plz merge when ready!

2022-03-03 19:11 UTC, merged