Added submit video URL action
PipedreamHQ/pipedream pull request #2299
Opened 2022-02-23 01:19 UTC by mjabali

2022-02-23 01:20 UTC, dylburger commented
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-02-23 01:26 UTC, dannyroosevelt commented
Thanks for submitting the PR, @mjabali! Someone from the team will take a look asap.

2022-02-25 23:43 UTC, jcortes requested changes
It's looking good. Just a small refactor and it's done. The main idea is to be as consistent as possible with the [folder structure](https://pipedream.com/docs/components/guidelines/#guidelines-patterns) and most of components that are already in the [repo](https://github.com/PipedreamHQ/pipedream/tree/master/components). I think we should make use of the file `symbl_ai.app.mjs` in that way you can separate the concerns on each component. So you can modify this file like this:
```javascript
import { axios } from "@pipedream/platform";

export default {
  type: "app",
  app: "symbl_ai",
  propDefinitions: {},
  methods: {
    getHeaders() {
      return {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.$auth.oauth_access_token}`,
      };
    },
    async makeRequest(customConfig) {
      const {
        $,
        path,
        url,
        ...otherConfig
      } = customConfig;

      const basePath = "https://api.symbl.ai/v1";

      const config = {
        url: url ?? `${basePath}${path}`,
        headers: this.getHeaders(),
        ...otherConfig,
      };

      return axios($, config);
    },
    async postVideoUrl({
      $, data,
    }) {
      return this.makeRequest({
        $,
        method: "post",
        path: "/process/video/url",
        data,
      });
    },
  },
};

```

Also can you add the `package.json` file please?
```javascript
{
  "name": "@pipedream/symbl_ai",
  "version": "0.3.3",
  "description": "Pipedream Symbl_ai Components",
  "main": "symbl_ai.app.mjs",
  "keywords": [
    "pipedream",
    "symbl_ai"
  ],
  "homepage": "https://pipedream.com/apps/symbl_ai",
  "author": "Pipedream <support@pipedream.com> (https://pipedream.com/)",
  "license": "MIT",
  "dependencies": {
    "fraudlabspro-nodejs": "^2.1.0"
  },
  "gitHead": "e12480b94cc03bed4808ebc6b13e7fdb3a1ba535",
  "publishConfig": {
    "access": "public"
  }
}

```

2022-02-25 23:43 UTC, jcortes commented on components/symbl_ai/actions/submit-video-url/post-video-url.js
> +import axios from "axios";
If you modify the file `symbl_ai.app.mjs` as I suggested here, then you can replace this line with
```suggestion
import symblAIApp from "../../symbl_ai.app.mjs";
```

2022-02-25 23:43 UTC, jcortes commented on components/symbl_ai/actions/submit-video-url/post-video-url.js
> +    },
Then you can repace this with
```suggestion
    symblAIApp,
```

2022-02-25 23:43 UTC, jcortes commented on components/symbl_ai/actions/submit-video-url/post-video-url.js
> +    }
Also you can replace this block with
```suggestion
    try {
      const response =
        await this.symblAIApp.postVideoUrl({
          $,
          data: {
            url: this.videoUrl,
            name: this.meetingName ?? "",
          },
        });

      $.export("$summary", `Successfully posted video URL. Conversation Id: ${response.conversationId} and Job Id: ${response.jobId}`);

      return response;

    } catch (error) {
      console.log("Error: ", error);
      $.export("$summary", "Failed to post video URL");
    }
```

2022-02-28 17:04 UTC, jcortes reviewed
OK looks good to me now. So about testing your changes there is no unit testing tool just yet as far as I know so what I'm always do is to use the Pipedrean CLI tools are there, you can check the docs [here](https://pipedream.com/docs/cli/reference/#pd-publish) when it comes to publishing an action component

2022-02-28 18:07 UTC, mjabali commented on components/symbl_ai/package.json
> +      "fraudlabspro-nodejs": "^2.1.0",
Thanks! Changes are done.

2022-02-28 22:32 UTC, jcortes approved these changes

2022-03-02 19:05 UTC, dannyroosevelt commented
> Hi @jcortes, I have other updates to be submitted but they will be all dependent on this one. Is there any chance we can have this merged soon? Thanks a bunch.

@mjabali to confirm, do these all functionally work for you? If so, we'll get them published asap!

2022-03-02 20:13 UTC, mjabali commented
> 

Thanks @dannyroosevelt. We have a whole lot of other actions to be submitted but would like to use this as our starting point for any of the next ones being added.

2022-03-02 20:16 UTC, merged

2022-03-02 20:17 UTC, dannyroosevelt commented
Merged and published!