UltraMsg New Actions
PipedreamHQ/pipedream pull request #2348
Opened 2022-03-02 14:46 UTC by vellames-turing

- [ ] Send Audio
- [ ] Send Document
- [ ] Send Image
- [ ] Send Link
- [ ] Send Location
- [ ] Send Message
- [ ] Send Video

2022-03-02 14:47 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-03-04 22:36 UTC, jcortes requested changes
Hi @vellames-turing it looks good to me. Just a few minor issues and it will be ready for QA. Thanks!

2022-03-04 22:36 UTC, jcortes commented on components/ultramsg/ultramsg.app.mjs
> +    },
```suggestion
    _getAxiosConvertedData(data = {}) {
      return new URLSearchParams({
        token: this.$auth.token,
        ...data,
      });
    },
```

2022-03-04 22:36 UTC, jcortes commented on components/ultramsg/package.json
> +    "main": "ultramsg.app.js",
```suggestion
    "main": "ultramsg.app.mjs",
```

2022-03-04 22:36 UTC, jcortes commented on components/ultramsg/action/send-message/send-message.mjs
> +    },
Seems like you can set an `options` property with this data
```
priority = 0: for High priority like OTP messages.
priority = 5: used with general messages.
priority =10: Non-urgent promotional offers and notifications to your customers.
```

2022-03-04 22:36 UTC, jcortes commented on components/ultramsg/action/send-location/send-location.mjs
> +  version: "0.0.2",
```suggestion
  version: "0.0.1",
```

2022-03-04 22:36 UTC, jcortes commented on components/ultramsg/action/send-audio/send-audio.mjs
> +  key: "ultramsg-send-an-audio",
```suggestion
  key: "ultramsg-send-audio",
```

2022-03-04 22:36 UTC, jcortes commented on components/ultramsg/action/send-document/send-doucument.mjs
> +  key: "ultramsg-send-a-document",
```suggestion
  key: "ultramsg-send-document",
```

2022-03-04 22:36 UTC, jcortes commented on components/ultramsg/action/send-image/send-image.mjs
> +  key: "ultramsg-send-a-image",
```suggestion
  key: "ultramsg-send-image",
```

2022-03-04 22:36 UTC, jcortes commented on components/ultramsg/action/send-link/send-link.mjs
> +  key: "ultramsg-send-a-link",
```suggestion
  key: "ultramsg-send-link",
```

2022-03-04 22:36 UTC, jcortes commented on components/ultramsg/action/send-location/send-location.mjs
> +  key: "ultramsg-send-a-location",
```suggestion
  key: "ultramsg-send-location",
```

2022-03-04 22:36 UTC, jcortes commented on components/ultramsg/action/send-message/send-message.mjs
> +  key: "ultramsg-send-a-message",
```suggestion
  key: "ultramsg-send-message",
```

2022-03-04 22:36 UTC, jcortes commented on components/ultramsg/action/send-video/send-video.mjs
> +  key: "ultramsg-send-a-video",
```suggestion
  key: "ultramsg-send-video",
```

2022-03-07 17:23 UTC, vellames-turing commented
@jcortes Suggestions implemented

2022-03-07 19:20 UTC, js07 reviewed
The changes since the last review look good. I just made some minor comments.

2022-03-07 20:33 UTC, vellames-turing commented on components/ultramsg/ultramsg.app.mjs
> +      description: "Phone with international format e.g. `+1408XXXXXXX` , or chatID for contact or group",
Oh, I did not notice these endpoints, I will take a look

2022-03-09 17:37 UTC, js07 approved these changes
@vellames-turing Looks good to me! I just made a minor suggestion.

2022-03-09 17:37 UTC, js07 commented on components/ultramsg/action/send-audio/send-audio.mjs
> +  description: "Send audio file to a specified number. [See the docs here](https://docs.ultramsg.com/api/post/messages/audio)",
```suggestion
  name: "Send Audio",
  description: "Send an audio file to a specified number. [See the docs here](https://docs.ultramsg.com/api/post/messages/audio)",
```

2022-03-09 19:37 UTC, js07 approved these changes

2022-03-15 19:26 UTC, dannyroosevelt commented
@vellames-turing feel free to merge!

2022-03-15 19:28 UTC, merged