fix for  [warning] object was filtered for serialization in Tweet code
PipedreamHQ/pipedream pull request #2445
Opened 2022-03-16 23:03 UTC by DomHawken

When _addParseId() is called on a tweet, it adds a BigInt version of the ID on the end of the object and uses it to sort, which works fine.

If you subsequently do anything to the tweet object (console.log it, update it etc), the BigInt is stripped with the warning: [warning] object was filtered for serialization  - it;s too big for the parser.

Given that it's only used for this one sort and not needed anyway, I dropped the map and did the work in the sort code. Advantage is no extra additions to the object and no map needed.

Warning fixed as a result.

2022-03-16 23:04 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-03-16 23:05 UTC, dylburger commented
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

2022-03-18 18:18 UTC, michelle0927 requested changes
Looks good. Thanks for fixing that. You'll just need to update the versions of the sources that use `tweets.mjs`.
`my-tweets.mjs`
`new-tweet-in-list.mjs`
`user-tweets.mjs`
`watch-retweets-of-me.mjs`
`watch-retweets-of-my-tweet.mjs`
`watch-retweets-of-user-tweet.mjs`

2022-03-18 20:58 UTC, dannyroosevelt commented
@michelle0927 if all that is left is bumping the versions for the impacted sources, can you go ahead and apply those changes? then let's ship it!

2022-03-18 23:01 UTC, michelle0927 approved these changes

2022-03-18 23:01 UTC, merged