Google Calendar - bug fix & refactor
PipedreamHQ/pipedream pull request #2482
Opened 2022-03-24 17:26 UTC by michelle0927

Addresses a bug in **New or Update Event (Instant)** source and refactors Google Calendar sources.

Resolves #2472

2022-03-24 17:27 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-03-31 18:18 UTC, vellames-turing requested changes
Great refactor! Just some minors comments

2022-03-31 18:18 UTC, vellames-turing commented on components/google_calendar/google_calendar.app.mjs
> +        if (calendars && calendars.length) {
Can we use the code below?
```suggestion
        if (calendars?.length) {
```

2022-03-31 18:18 UTC, vellames-turing commented on components/google_calendar/sources/common.mjs
> +    async processEvents(event) {
There is some `console.log` here at the same line of other statementss

2022-03-31 18:18 UTC, vellames-turing commented on components/google_calendar/sources/common.mjs
> +      const intervalMs = 1000 * (event.interval_seconds || 300); // fall through to default for manual testing
Just checking, if `event.interval_seconds = 0` so the evaluated value will be `300`. Maybe you want to use `??` operator or the idea is to use `300` if `event.interval_seconds = 0 or null`?

2022-04-04 17:52 UTC, vellames-turing submitted a review, later dismissed
Thank you!

2022-05-16 15:55 UTC, vunguyenhung commented
Hello @michelle0927, in order for me to verify, could you resolve conflicts in this PR?

2022-05-19 17:02 UTC, michelle0927 commented
@vunguyenhung Is the only component that's failing "New or Updated Event (Instant)"? If you have the prop "New Events Only?" set to `true`, it will emit for new events, but not updated events. If you set the prop to `false`, it will emit for new or updated events.
<img width="434" alt="Screen Shot 2022-05-19 at 12 56 03 PM" src="https://user-images.githubusercontent.com/10889229/169356906-f5934708-7525-4115-98b4-7122f4e63563.png">

2022-05-20 14:15 UTC, vunguyenhung commented
Thank you @michelle0927 for your explanation. There was only one failed case which is New or Updated Event (Instant), though, I have disable the "New Event" options and I can receive Update event now. Everything is Good! ready for release!

2022-05-20 14:18 UTC, vunguyenhung commented
Thank you @michelle0927 for your explanation. There was only one failed case which is New or Updated Event (Instant), though, I have disable the "New Event" options and I can receive Update event now. Everything is Good! ready for release!

Test Report
[Google_Calendar_2472_2113.pdf](https://github.com/PipedreamHQ/pipedream/files/8740792/Google_Calendar_2472_2113.pdf)

2022-05-20 14:33 UTC, vunguyenhung commented
Thank you [@michelle0927](https://github.com/michelle0927) for your explanation. There was only one failed case which is New or Updated Event (Instant), though, I have disable the "New Event" options and I can receive Update event now. 

I have also tested the case where events are still emitted after push notification renewal. More detail on the test report

All test cases are passed! Ready for release!

Test report
[Google_Calendar_2472_2128.pdf](https://github.com/PipedreamHQ/pipedream/files/8740913/Google_Calendar_2472_2128.pdf)

2022-05-20 14:39 UTC, michelle0927 commented
/approve

2022-05-20 14:41 UTC, andrewjschuang approved these changes

2022-05-20 14:43 UTC, merged