[ACTIONS/SOURCE] Segment actions refactor and new source
PipedreamHQ/pipedream pull request #2483
Opened 2022-03-24 19:09 UTC by jcortes

# Actions refactored #1530 
- [x] **Identify** \| Identifies a user
- [x] **Track** \| Records a user's actions
- [x] **Group** \| Associates an individual user with a group
- [x] **Alias** \| Associates one identity with another or merges two identities

# Source #106 
- [x] Webhook Destination

2022-03-24 19:09 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-04-05 18:36 UTC, vellames-turing requested changes
Hi there, looks great, just some minors

2022-04-05 18:36 UTC, vellames-turing commented on components/segment/sources/webhook-destination/webhook-destination.mjs
> +    workspace: {
Maybe this can be moved to `app` for future uses?

2022-04-05 18:36 UTC, vellames-turing commented on components/segment/segment.app.mjs
> +      description: "A pseudo-unique substitute for a User ID, for cases when you dont have an absolutely unique identifier. A userId or an anonymousId is required.",
```suggestion
      description: "A pseudo-unique substitute for a User ID, for cases when you don't have an absolutely unique identifier. A `userId` or an `anonymousId` is required.",
```

2022-04-05 18:36 UTC, vellames-turing commented on components/segment/segment.app.mjs
> +      // return "https://api.segmentapis.com";
Can we remove this comment?

2022-04-11 17:00 UTC, vellames-turing approved these changes
Thank you!

2022-04-20 18:56 UTC, merged