Added PUT Conversation metadata action
PipedreamHQ/pipedream pull request #2510
Opened 2022-03-29 15:14 UTC by mjabali

2022-04-05 15:51 UTC, dylburger commented
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

2022-04-05 16:14 UTC, jcortes requested changes
@mjabali Thanks for this contribution. It looks good. Just a couple of requested changes regarding refactoring and `prop` type and it's done!

2022-04-05 16:14 UTC, jcortes commented on components/symbl_ai/symbl_ai.app.mjs
> +    },
```suggestion
    async putConversation({
      conversationId, ...args
    }) {
      return this.makeRequest({
        method: "put",
        path: `/conversations/${conversationId}`,
        ...args,
      });
    },
```

2022-04-05 20:23 UTC, mjabali commented on components/symbl_ai/symbl_ai.app.mjs
> +    },
Thanks. Addressed in f6b7f8b3.

2022-04-05 20:23 UTC, mjabali commented on components/symbl_ai/actions/put-conversation/put-conversation.mjs
> +      type: "string",
Thanks. Addressed in f6b7f8b3.

2022-04-06 21:42 UTC, jcortes approved these changes
LGTM! Ready for QA

2022-04-12 00:43 UTC, merged