Suspend delay prototype
PipedreamHQ/pipedream pull request #2555
Opened 2022-04-06 00:32 UTC by dannyroosevelt

2022-04-06 00:33 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-05-02 20:33 UTC, dannyroosevelt commented
Btw this was my prototype, so any refactoring / code changes, etc that you want to see, go for it -- whoever is reviewing, please just go ahead and implement whatever recommendations you have.

2022-05-02 22:35 UTC, jcortes requested changes
@dannyroosevelt  It looks good to me, just added a couple of comments and that's it

2022-05-02 22:35 UTC, jcortes commented on components/delay/actions/workflow-delay/workflow-delay.mjs
> +  methods: {},
I think these two properties can be removed

2022-05-02 22:35 UTC, jcortes commented on components/delay/actions/workflow-delay/workflow-delay.mjs
> +    const resp = $.flow.delay(milliseconds);
shouldn't this line be await?
```suggestion
    const resp = await $.flow.delay(milliseconds);
```

2022-05-02 22:49 UTC, jcortes approved these changes
@dannyroosevelt  LGTM!

2022-05-02 22:55 UTC, merged