Salesforce update legacy actions
PipedreamHQ/pipedream pull request #2557
Opened 2022-04-06 12:14 UTC by andrewjschuang

This PR resolves issue #2283.

Salesforce legacy actions were using API v20.0 that is deprecated and will soon be retired. This PR updates the API version to v50.0, maintaining consistent with the sources. Also some minor refactoring was made, though not enough to be compliant with the guidelines.

**Therefore, this PR should not be merged alone.**

@dannyroosevelt Should a new card be created for refactoring these actions? I think combining them into one PR would be too big of a change for these actions.

2022-04-06 12:15 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-04-06 17:56 UTC, dannyroosevelt commented
> This PR addressed issue #2283.
> 
> Salesforce legacy actions were using API v20.0 that is deprecated and will soon be retired. This PR updates the API version to v50.0, staying consistent with the sources. Also some minor refactoring was made, though not enough to be compliant with the guidelines.
> 
> **Therefore, this PR should not be merged alone.**
> 
> @dannyroosevelt Should a new card be created for refactoring these actions? I think combining them into one PR would be too big of a change, especially for the review. Also, would there be a big impact if most of the props were to be deleted? There is a large number of props in each action and I think refactoring each one would take a very long time.
> 
> Resolves #2283

@andrewjschuang thank you for the detailed and clear update! If you think it makes sense to break out the work into multiple PRs, that makes sense and sounds good to me. I think probably just keep a single issue to track all the work on the GitHub project board, but you can attach multiple PRs.

And for the props question, that's fine to get rid of a lot of them (there are too many there anyway, and the current component actions were converted programmatically from the legacy actions we had in the v1 builder). I think it makes sense to **rev the `major` version for any component you're updating**, since there are major changes. And that will notify users in the UI about breaking changes when they do an update.

How does that all sound?

2022-04-06 18:03 UTC, andrewjschuang commented
> > This PR addressed issue #2283.
> > Salesforce legacy actions were using API v20.0 that is deprecated and will soon be retired. This PR updates the API version to v50.0, staying consistent with the sources. Also some minor refactoring was made, though not enough to be compliant with the guidelines.
> > **Therefore, this PR should not be merged alone.**
> > @dannyroosevelt Should a new card be created for refactoring these actions? I think combining them into one PR would be too big of a change, especially for the review. Also, would there be a big impact if most of the props were to be deleted? There is a large number of props in each action and I think refactoring each one would take a very long time.
> > Resolves #2283
> 
> @andrewjschuang thank you for the detailed and clear update! If you think it makes sense to break out the work into multiple PRs, that makes sense and sounds good to me. I think probably just keep a single issue to track all the work on the GitHub project board, but you can attach multiple PRs.
> 
> And for the props question, that's fine to get rid of a lot of them (there are too many there anyway, and the current component actions were converted programmatically from the legacy actions we had in the v1 builder). I think it makes sense to **rev the `major` version for any component you're updating**, since there are major changes. And that will notify users in the UI about breaking changes when they do an update.
> 
> How does that all sound?

Alright, sounds great! Thanks

2022-04-13 20:00 UTC, michelle0927 requested changes
I don't think the action filenames need to start with "salesforce". I think it would be better to rename them as `create-account.mjs`, `create-attachment.mjs`, etc. by renaming the folder names, filenames, and component `key`s.

2022-04-13 20:00 UTC, michelle0927 commented on components/salesforce_rest_api/actions/salesforce-update-contact/salesforce-update-contact.mjs
>      },
Is `LastName` required or optional? The description says required, but it's listed as optional.

2022-04-13 20:00 UTC, michelle0927 commented on components/salesforce_rest_api/salesforce_rest_api.app.mjs
> +          };
We can just return the empty array.
```suggestion
          return [];
```

2022-04-13 20:00 UTC, michelle0927 commented on components/salesforce_rest_api/salesforce_rest_api.app.mjs
>          };
We don't need to return `options` inside an object.
```suggestion
        const { sobjects } = await this.listSObjectTypes();
        return sobjects
          .filter((sobject) => sobject.replicateable)
          .map((sobject) => ({
            label: sobject.label,
            value: sobject.name,
          }));
```

2022-04-13 20:00 UTC, michelle0927 commented on components/salesforce_rest_api/sources/common-instant.mjs
> +        };
We don't need to return the options inside an object.
```suggestion
        return supportedObjectTypes.map((i) => ({
          label: i.label,
          value: i.name,
        }));
```

2022-04-14 13:48 UTC, michelle0927 approved these changes

2022-04-22 13:43 UTC, DilanAthukorala commented
Hi @andrewjschuang, I'm getting the following error when trying add Salesforce Account to Pipedream

Pipedream failed to connect to your account.

Please reach out to integration-errors@pipedream.com and provide this error ID: 18cb5e9b3c294adf8700706996654b33

https://api.pipedream.com/connect/oauth/oa_GXxiEz/callback?code=aPrx_yTkbIprMMiwU2cLnIHnyqFTdWteO_jvKP0lhphtuXyT7f3JhO11tiiqKLnC.TziasSmzQ%3D%3D&state=dV9xbGhwRURMfGFjNjg0OTJlNDQ1OTc4MzNkODI2MGFlNWFmMDliZTFj

2022-04-25 18:16 UTC, dannyroosevelt commented
Here's the error we got for you @DilanAthukorala -- are you able to enable the Rest API for your account?
```
[
  {
    "message": "The REST API is not enabled for this Organization.",
    "errorCode": "API_DISABLED_FOR_ORG"
  }
]
```

2022-05-13 13:12 UTC, vunguyenhung commented
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Salesforce_Test_Report_2557.pdf](https://github.com/PipedreamHQ/pipedream/files/8687318/Salesforce_Test_Report_2557.pdf)

2022-06-07 21:46 UTC, dannyroosevelt commented
What's the status of this?

2022-06-07 21:51 UTC, andrewjschuang commented
> What's the status of this?

Pending #1474 because of conflicts.

2022-06-15 20:08 UTC, closed without merging