[ACTION] Refactor Bitbucket actions #1484
PipedreamHQ/pipedream pull request #2669
Opened 2022-04-21 14:25 UTC by lcaresia

2022-05-03 20:03 UTC, jcortes requested changes
Hi @lcaresia I've just added a few minor request changes. Everything else looks good to me. Thanks!

2022-05-03 20:03 UTC, jcortes commented on components/bitbucket/package.json
>      "main": "bitbucket.app.js",
```suggestion
    "main": "bitbucket.app.mjs",
```

2022-05-06 17:36 UTC, lcaresia commented on components/bitbucket/actions/common/common.mjs
> +import bitbucket from "../../bitbucket.app.mjs";
What the difference between `common` and `base` in this case ?

This is documented in some place?

2022-05-06 17:45 UTC, lcaresia commented on components/bitbucket/package.json
> +    "dependencies": {},
Why ? Now is used the `@pipedream/platform` axios

2022-05-06 18:26 UTC, jcortes commented on components/bitbucket/package.json
> +    "dependencies": {},
Yeah I meant to say `@pipedream/platform`. From now on please add all third party dependencies in `package.json`

2022-05-06 18:38 UTC, jcortes submitted a review, later dismissed
@lcaresia LGTM! Ready for QA!

2022-05-10 17:44 UTC, DilanAthukorala commented
@lcaresia 

Getting following error for get_file_from_repository 

![image](https://user-images.githubusercontent.com/102980146/167690260-a6d13667-5558-408b-8e72-9cb268a01726.png)


```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>Bearer uVSxvDHdzlNH2E7dzJDvhfTNN6pWdfQtdnHhbhOfct7egoIk0SAi5oPqdRpAcpXjT9b_WgmypMavmfM9oliOVj5AoGk6nwZjSKQaFXvLaXCAQuZKOpsrw5o7</ArgumentValue><RequestId>0D07P410RDA0D8PX</RequestId><HostId>Ucow3AGZjSlY5qgFbCb5q30C/X+GxvTrEnMueUva+NvdeEZ54PYQQzOXhcY5NcDd5Let7s6rrcM=</HostId></Error>
```

2022-05-12 19:16 UTC, lcaresia commented
@DilanAthukorala Can you take a look now? I made some updates.

2022-05-13 13:49 UTC, DilanAthukorala commented
Verification successful no issues observed.

2022-05-13 16:38 UTC, lcaresia commented
/approve

2022-05-13 16:54 UTC, michelle0927 approved these changes

2022-05-13 17:22 UTC, merged