Added config action to setup variables for a workflow
PipedreamHQ/pipedream pull request #2681
Opened 2022-04-22 18:06 UTC by jcortes

The idea is to give support to any workflow with variables that can be set with a simple action component step that in a following step we can reference with something like
```
export default defineComponent({
  async run({ steps, $ }) {
    return steps.helpers_variables_config.config;
  },
})
```

2022-04-25 16:45 UTC, vellames-turing approved these changes

2022-05-03 17:45 UTC, dannyroosevelt commented
@jcortes is there a reason to `$.export` config in addition to just `return`ing it?

Also, this should go in the `helper_functions` app, not `helpers`.

2022-05-09 20:26 UTC, dannyroosevelt commented on components/helper_functions/actions/export-variables/export-variables.mjs
> +    config: {
can you also import `helper_functions` so the action inherits the app icon?

2022-05-09 20:27 UTC, dannyroosevelt commented on components/helper_functions/actions/export-variables/export-variables.mjs
> +export default {
`import helper_functions from "../../helper_functions.app.mjs"`

2022-05-09 20:28 UTC, dannyroosevelt commented on components/helper_functions/actions/export-variables/export-variables.mjs
> +    config: {
so that the action inherits the app icon

2022-05-09 20:29 UTC, dannyroosevelt requested changes
Can you just make sure to import the app in the action props, so the action inherits the app icon? Then let's ship it!

2022-05-09 23:39 UTC, dannyroosevelt approved these changes

2022-05-09 23:41 UTC, merged