2229 cloudtables cations
PipedreamHQ/pipedream pull request #2687
Opened 2022-04-22 23:48 UTC by Giuan0

2022-04-22 23:48 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-04-25 14:43 UTC, dylburger commented on components/cloudtables/actions/add-single-row/add-single-row.mjs
> +      $.export("$summary", `No data points available at [${datasetID}].`);
Should this throw an error instead of a success message? I don't know the Cloudtables API - does the user need to take action in this case?

2022-04-25 14:44 UTC, dylburger commented on components/cloudtables/actions/delete-row/delete-row.mjs
> +// legacy_hash_id: a_bKijbM
You'll want to remove this comment. This is for older actions that we programmatically converted, and we use this comment for analytics, but it's not relevant here.

2022-04-25 23:51 UTC, Giuan0 commented on components/cloudtables/actions/add-single-row/add-single-row.mjs
> +      description: "",
removed property, using default description value from cloudtables.app.mjs

2022-04-27 17:45 UTC, vellames-turing requested changes
Hey. Thanks for your PR. Looks real good. Just some minors

2022-04-27 17:45 UTC, vellames-turing commented on components/cloudtables/cloudtables.app.mjs
>      authKeys() {
You can remove this guy and the comment above, it's just a template :)

2022-04-27 17:45 UTC, vellames-turing commented on components/cloudtables/cloudtables.app.mjs
> +      opts.url = `https://${this.$auth.subdomain}.cloudtables.io/api/1${path[0] === "/"
I see you are using query parameters here. Axios has a property called `params`, you can create an object with your query params and pass it to this param.
Take a look on `getBlogPosts` at `blogger.app.mjs` for reference

2022-04-27 17:45 UTC, vellames-turing commented on components/cloudtables/cloudtables.app.mjs
> +        headers: {
Can we have the headers returned by a function? take a look at `blogger.app.mjs` for reference

2022-04-28 15:37 UTC, vellames-turing approved these changes
Great, thank you!

2022-05-02 22:24 UTC, merged