Add Notion Query Database action
PipedreamHQ/pipedream pull request #2693
Opened 2022-04-24 05:08 UTC by vunguyenhung

This PR adds Notion query a database action to support this request: https://github.com/PipedreamHQ/pipedream/issues/2570

2022-04-24 05:08 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-04-24 11:02 UTC, dylburger commented
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

2022-04-25 14:25 UTC, vellames-turing requested changes
Hi there, thanks for your contribution. I left some comments

2022-04-25 14:25 UTC, vellames-turing commented on components/notion/actions/query-database/query-database.mjs
> +    const params = { filter, sorts }
You need to use `this` in order to get the `props` params
```suggestion
    const params = {
    filter: this.filter,
    sorts: this.sorts
    }
```

2022-04-25 14:25 UTC, vellames-turing commented on components/notion/actions/query-database/query-database.mjs
> +      description: "Filter Pages in the Database [See the docs](https://developers.notion.com/reference/post-database-query-filter)",
```suggestion
      description: "A filter is a single condition used to specify and limit the entries returned from a database query. Database queries can be filtered by page property values [See the docs](https://developers.notion.com/reference/post-database-query-filter)",
```

2022-04-25 14:25 UTC, vellames-turing commented on components/notion/actions/query-database/query-database.mjs
> +      description: "Sort Pages in the Database [See the docs](https://developers.notion.com/reference/post-database-query-sort)",
```suggestion
      description: "A sort is a condition used to order the entries returned from a database query. [See the docs](https://developers.notion.com/reference/post-database-query-sort)",
```

2022-04-26 14:10 UTC, vunguyenhung commented
Thanks @vellames-turing, I've address your comments! Kindly check again when you have time 🙏

2022-05-18 12:52 UTC, andrewjschuang commented
@vunguyenhung @dannyroosevelt I think this was resolved in #2718

2022-05-18 16:27 UTC, dannyroosevelt commented
> @vunguyenhung @dannyroosevelt It seems that #2718 resolved this a few days ago

Oh nice, so is this PR not needed?

2022-05-18 16:52 UTC, andrewjschuang commented
> > @vunguyenhung @dannyroosevelt It seems that #2718 resolved this a few days ago
> 
> Oh nice, so is this PR not needed?

Yeah, it can be closed

2022-05-18 16:56 UTC, closed without merging