[ACTION] Notion - Query a database #2570
PipedreamHQ/pipedream pull request #2718
Opened 2022-04-27 15:13 UTC by lcaresia

2022-04-28 17:17 UTC, vellames-turing requested changes
Hi there! Just some suggestions

2022-04-28 17:17 UTC, vellames-turing commented on components/notion/actions/query-database/query-database.mjs
> +      type: "string",
Can this be an object?

2022-04-29 15:29 UTC, vellames-turing approved these changes
THank you!

2022-05-02 14:08 UTC, DilanAthukorala commented
@lcaresia Observing the following issue, could you please check and define how the filter query should be constructed in the UI.

![image](https://user-images.githubusercontent.com/102980146/166247976-96ffdba7-6bdc-4f12-8967-05db5cb0be96.png)

2022-05-10 16:10 UTC, lcaresia commented
@DilanAthukorala Exampel added!

2022-05-13 13:54 UTC, vunguyenhung commented
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Notion_2570.pdf](https://github.com/PipedreamHQ/pipedream/files/8688385/Notion_2570.pdf)

2022-05-13 17:18 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Notion_2570_0017.pdf](https://github.com/PipedreamHQ/pipedream/files/8689678/Notion_2570_0017.pdf)

2022-05-13 17:19 UTC, lcaresia commented
/approve

2022-05-13 17:21 UTC, michelle0927 approved these changes

2022-05-13 17:23 UTC, merged