1542-google-sheets-component-improvements
PipedreamHQ/pipedream pull request #2731
Opened 2022-04-29 15:44 UTC by alysonturing

**Improving New Spreadsheet (Instant) source**
Adding deploy hook to emit sample records on the first run
Changing summary to `New File: ${fileInfo.name}`

2022-04-29 15:45 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-05-04 19:35 UTC, jcortes requested changes
Hi @alysonturing I've added just one minor request change. The rest looks good to me! Thanks!

2022-05-04 19:35 UTC, jcortes commented on components/google_sheets/sources/new-spreadsheet/new-spreadsheet.mjs
> +      opts.q = `${mimeQuery} and parents in '${folderId}' and trashed = false`;
```suggestion
      let opts = {
        q: `${mimeQuery} and parents in '${folderId}' and trashed = false`,
      };
      if (!this.isMyDrive()) {
        opts = {
          corpora: "drive",
          driveId: this.getDriveId(),
          includeItemsFromAllDrives: true,
          supportsAllDrives: true,
          ...opts,
        };
      }
```

2022-05-04 21:01 UTC, jcortes approved these changes
Hi @alysonturing LGTM! Ready for QA!

2022-05-05 01:13 UTC, vunguyenhung commented
Verified with the following test cases:
## 1. Google Sheets - Create a new SpreadSheet manually
Google Sheet
![Screen Shot 2022-05-05 at 07 58 14](https://user-images.githubusercontent.com/18277920/166850389-7bf779e9-1c92-42b1-a1f4-0c50813e5e11.png)

PipeDream console
![Untitled SpreadSheet](https://user-images.githubusercontent.com/18277920/166850367-9e0ac899-0f80-4504-8f33-3ed2cf27b4fe.png)

## 2. Google Sheets - Create import a new Spreadsheet using CSV file with name
Google Sheets
![Screen Shot 2022-05-05 at 07 58 20](https://user-images.githubusercontent.com/18277920/166850423-541dd744-e7b8-4b9b-ab54-a38845f35d9b.png)

PipeDream console
![Import SpreadSheet via CSV file](https://user-images.githubusercontent.com/18277920/166850432-238e537f-0fa4-4834-a6a6-74adaabfff04.png)

## 3. Google Drive - Upload new file
Google Drive
![Screen Shot 2022-05-05 at 08 11 21](https://user-images.githubusercontent.com/18277920/166850666-3ab259ed-f10b-48ff-9a66-3dd020cd7839.png)

PipeDream console
![Screen Shot 2022-05-05 at 08 10 57](https://user-images.githubusercontent.com/18277920/166850672-bbc5f514-8dba-4158-8eda-c06d3bdd85c0.png)

2022-05-05 01:17 UTC, merged

2022-05-16 16:57 UTC, Yazir commented
I'm using this to track new files. Event data it provides is much better and detailed than the other google drive components. Great work. 

I wish there was this kind of amount of such data for file modifications.