1537 action xero accounting new actions
PipedreamHQ/pipedream pull request #2744
Opened 2022-05-02 16:18 UTC by bush4u

Danny confirmed it is okay to skip **New or updated subscription** trigger

2022-05-02 16:19 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-05-02 22:02 UTC, jcortes requested changes
Hi @bush4u I've just left a request change I would like you to make in the meantime, thanks for this work, it's looking great so far.

2022-05-03 08:49 UTC, bush4u commented on components/xero_accounting_api/xero_accounting_api.app.mjs
> +      });
Done

2022-05-03 17:01 UTC, jcortes requested changes
Hi @bush4u thanks for making the refactor. It's looking good so far. I've just added a few more request changes and I think it'll be good for QA!

2022-05-03 20:00 UTC, bush4u commented on components/xero_accounting_api/common/common.util.mjs
> +import { ConfigurationError } from "@pipedream/platform";
Fixed

2022-05-03 21:22 UTC, bush4u commented on components/xero_accounting_api/actions/add-line-item-to-invoice/add-line-item-to-invoice.mjs
> +    return await this.xero_accounting_api.createInvoice(tenant_id, data);
Fixed

2022-05-03 21:22 UTC, bush4u commented on components/xero_accounting_api/actions/add-line-item-to-invoice/add-line-item-to-invoice.mjs
> +import xero_accounting_api from "../../xero_accounting_api.app.mjs";
Fixed

2022-05-03 21:23 UTC, bush4u commented on components/xero_accounting_api/sources/new-updated-contact/new-updated-contact.mjs
> +      (lastDateChecked = this.db.get("lastDateChecked"));
Done

2022-05-11 16:52 UTC, bush4u commented
> Hi @bush4u Unable deploy add-line-item-to-invoice action, getting following error
> 
> ![image](https://user-images.githubusercontent.com/102980146/167876329-b63f22a5-b97b-4a1b-ad10-ea00dd78f9c7.png)

This is done

2022-05-11 20:16 UTC, DilanAthukorala commented
@bush4u  please check the following issues;

create_bill action - **DueDate** is not passing to the xero accounting site. 

find_invoice action - following error observed for tenant id
![image](https://user-images.githubusercontent.com/102980146/167936590-c0b15dd3-2a27-4819-a962-29720af59ff4.png)



new-updated-contacts / new-updated-invoice sources - observing following error when deploying
![image](https://user-images.githubusercontent.com/102980146/167939254-c9a1ed06-040c-4f9b-8533-29bf9872088d.png)

2022-05-11 23:08 UTC, bush4u commented
> @bush4u please check the following issues;
> 
> create_bill action - **DueDate** is not passing to the xero accounting site.
> 
> find_invoice action - following error observed for tenant id ![image](https://user-images.githubusercontent.com/102980146/167936590-c0b15dd3-2a27-4819-a962-29720af59ff4.png)
> 
> new-updated-contacts / new-updated-invoice sources - observing following error when deploying ![image](https://user-images.githubusercontent.com/102980146/167939254-c9a1ed06-040c-4f9b-8533-29bf9872088d.png)

I am reproducing the error

2022-05-12 01:52 UTC, bush4u commented
I think that error came up because the DueDate format does not follow **YYYY-MM-DD** format

2022-05-12 02:14 UTC, bush4u commented
> > @bush4u please check the following issues;
> > create_bill action - **DueDate** is not passing to the xero accounting site.
> > find_invoice action - following error observed for tenant id ![image](https://user-images.githubusercontent.com/102980146/167936590-c0b15dd3-2a27-4819-a962-29720af59ff4.png)
> > new-updated-contacts / new-updated-invoice sources - observing following error when deploying ![image](https://user-images.githubusercontent.com/102980146/167939254-c9a1ed06-040c-4f9b-8533-29bf9872088d.png)
> 
> I am reproducing the error

I was able to trap this particular error and it is fixed

2022-05-12 06:12 UTC, DilanAthukorala commented
@bush4u Thanks the **find_invoice** bug is fixed. Please update me once the other issues are fixed. 

https://github.com/PipedreamHQ/pipedream/pull/2744#issuecomment-1124247412

2022-05-12 09:08 UTC, bush4u commented
Thanks @DilanAthukorala ,
The bug has been fixed. Thanks

2022-05-12 14:08 UTC, bush4u commented
Please give me a little while. Not sure why my task is breaking at this time. I will test the sources again end to end

2022-05-12 16:04 UTC, bush4u commented
Thanks for your patience. Most of the bug were due to previous change requested.
I have tested the sources again and they should be fine now

2022-05-13 07:43 UTC, bush4u commented
Hi  @DilanAthukorala , Kindly let mw know if I have any more clarification is required

2022-05-13 14:12 UTC, DilanAthukorala commented
@bush4u It's better if we can some data to the events in **'New or updated invoice'** source. 
![image](https://user-images.githubusercontent.com/102980146/168302440-3a05ddf8-8db2-4de8-ab00-dd35a2e8d676.png)

2022-05-13 15:08 UTC, bush4u commented
> 
@DilanAthukorala 
Hi. 
I have discovered and fixed the bug

2022-05-13 15:08 UTC, bush4u commented
> @bush4u I am still seeing the issue for **create_bill** action where **duedate** is not updating in the xero accounting side. ![image](https://user-images.githubusercontent.com/102980146/168300007-815eaf72-554a-4fee-8e2a-c1f133a16911.png) ![image](https://user-images.githubusercontent.com/102980146/168300366-42a10f32-5a7d-4312-8ee3-950facca9d3c.png)

@DilanAthukorala
Hi.
I have discovered and fixed the bug

2022-05-13 15:16 UTC, bush4u commented
> @bush4u It's better if we can some data to the events in **'New or updated invoice'** source. ![image](https://user-images.githubusercontent.com/102980146/168302440-3a05ddf8-8db2-4de8-ab00-dd35a2e8d676.png)

Done!

2022-05-13 15:29 UTC, DilanAthukorala commented
Verification completed successfully.

2022-05-13 16:42 UTC, bush4u commented
Hi @michelle0927,

Kindly help review for approval. 
Ticket already passed QA, and it is ready for release

2022-05-13 16:56 UTC, michelle0927 approved these changes

2022-05-13 18:22 UTC, merged