Add bannerbear create image action
PipedreamHQ/pipedream pull request #2749
Opened 2022-05-03 02:59 UTC by vunguyenhung

This PR adds BannerBear create an image action. Related to this issue https://github.com/PipedreamHQ/pipedream/issues/753

BannerBear API Doc can be found here: https://developers.bannerbear.com/#introduction

BannerBear Create Image API Doc can be found here: https://developers.bannerbear.com/#post-v2-images

Select templates
![Screen Shot 2022-04-29 at 08 29 11](https://user-images.githubusercontent.com/18277920/165872646-c7ee596e-a8da-495f-b406-2f6712e9360a.png)

Set `modifications`
![Screen Shot 2022-04-29 at 08 28 54](https://user-images.githubusercontent.com/18277920/165872655-9b141481-92af-4ed4-845a-f635ed87e912.png)

Additionally I have added the user-friendly user message in case that the modifications field is incorrect
![Screen Shot 2022-04-29 at 08 32 58](https://user-images.githubusercontent.com/18277920/165872560-2650075d-f0be-4dda-82ae-cc91dc8e1dc2.png)

2022-05-03 02:59 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-05-04 19:16 UTC, jcortes requested changes
Hi @vunguyenhung Overall it's looking great so far. Can you please fix all these eslint errors also? Thanks
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/506051/166809421-fc101d73-e2c3-414b-9627-68bf8b88eb2b.png">

2022-05-04 19:16 UTC, jcortes commented on components/bannerbear/bannerbear.app.mjs
> +      return response
```suggestion
      return axios(ctx, this._getRequestParams({
        method: 'GET',
        url: 'https://api.bannerbear.com/v2/templates',
        ...params
      }));
```

2022-05-04 19:16 UTC, jcortes commented on components/bannerbear/bannerbear.app.mjs
> +      return response;
```suggestion
      return axios(ctx, this._getRequestParams({
        method: 'POST',
        url: 'https://sync.api.bannerbear.com/v2/images',
        data: {
          template,
          modifications,
        },
        ...params
      }));
```

2022-05-08 04:30 UTC, vunguyenhung commented
Hello @jcortes, I've fixed the lint error! Kindly review again when you have time. Thanks!

2022-05-10 19:11 UTC, michelle0927 requested changes
It looks like these previous suggestions haven't been implemented yet:
https://github.com/PipedreamHQ/pipedream/pull/2749#discussion_r865188615
https://github.com/PipedreamHQ/pipedream/pull/2749#discussion_r865188922

2022-05-12 03:55 UTC, dannyroosevelt commented
> It looks like these previous suggestions haven't been implemented yet:

@vunguyenhung do you want to implement the suggested changes or do you want another dev to finish it up?

2022-05-12 13:52 UTC, vunguyenhung commented
Hey @michelle0927 and @dannyroosevelt, I have updated the code to pass all eslint rules (suggested by @jcortes). As I checked the Github checks the step is passed
![image](https://user-images.githubusercontent.com/18277920/168090654-f79bc4a6-0d99-4680-aad4-c9acbffdbdb7.png)

Also the code with changes suggested by @jcortes is outdated, which indicate that it is changed
![image](https://user-images.githubusercontent.com/18277920/168090846-9d85e92d-6ab3-4b93-8ed1-e37865bc150f.png)
![image](https://user-images.githubusercontent.com/18277920/168090895-cfe66925-180f-4d47-82a6-c080db11b331.png)

2022-05-12 15:16 UTC, michelle0927 approved these changes
@vunguyenhung If you look at the code, you can see that those 2 suggested changes were actually not made. I'm approving anyway since they're minor suggestions that shouldn't affect the functionality.

2022-05-12 15:16 UTC, michelle0927 commented on components/bannerbear/bannerbear.app.mjs
> +    },
```suggestion
    async fetchTemplates(ctx = this, params = {}) {
      return axios(ctx, this._getRequestParams({
        method: "GET",
        url: "https://api.bannerbear.com/v2/templates",
        ...params,
      }));
    },
    async createImage(ctx = this, template, modifications, params = {}) {
      return axios(ctx, this._getRequestParams({
        method: "POST",
        url: "https://sync.api.bannerbear.com/v2/images",
        data: {
          template,
          modifications,
        },
        ...params,
      }));
    },
```

2022-05-24 13:51 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[BannerBear_PR_2749.pdf](https://github.com/PipedreamHQ/pipedream/files/8763359/BannerBear_PR_2749.pdf)

2022-05-24 13:52 UTC, vunguyenhung commented
/approve

2022-05-24 15:56 UTC, merged