Paytrace New Actions
PipedreamHQ/pipedream pull request #2775
Opened 2022-05-04 23:53 UTC by isaiahtaylor

New actions:

* Batch summary
* List batch transactions
* List batches
* List transactions

Tested locally and reviewed the guidelines. Looking forward to the feedback.

2022-05-04 23:53 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-05-05 00:14 UTC, dylburger commented
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

2022-05-05 18:03 UTC, jcortes requested changes
Hi @isaiahtaylor Thanks for this contribution. It's looking pretty good so far. I've just added a few request changes.

2022-05-05 18:03 UTC, jcortes commented on components/paytrace/actions/batch-summary/batch-summary.mjs
> +import { axios } from "@pipedream/platform"
Can you please take a look at [this component](https://github.com/PipedreamHQ/pipedream/blob/master/components/segment/segment.app.mjs) as an example and make use also of `paytrace.app.mjs` file? In that way you can centralize the axios import in that file and handle better all needed endpoints in only one place?

2022-05-05 18:03 UTC, jcortes commented on components/paytrace/actions/list-batches/list-batches.mjs
> +    start_date: {
Try to always create properties in `camelCase` name convention as much as possible
```suggestion
    startDate: {
```

2022-05-18 17:25 UTC, lcaresia commented
I could not commit in this PR, so I create new one [#2881 ](https://github.com/PipedreamHQ/pipedream/pull/2881)

2022-05-24 23:41 UTC, dannyroosevelt commented
@isaiahtaylor do you want to wrap this up with the suggested changes, or did you want one of our devs to take it from here?

2022-05-24 23:43 UTC, isaiahtaylor commented
@dannyroosevelt I will update this PR later in the week! Thanks!

2022-06-16 21:40 UTC, dannyroosevelt commented
> @dannyroosevelt I will update this PR later in the week! Thanks!

@isaiahtaylor wanted to check in on this -- do you want someone from the team to wrap this up?

2022-07-12 22:28 UTC, dannyroosevelt commented
@feyzullah or @jcortes can one of you implement the suggested changes and get this into QA?

2022-07-12 22:35 UTC, feyzullah commented
> @feyzullah or @jcortes can one of you implement the suggested changes and get this into QA?

Sure, I will have a look

2022-07-13 17:41 UTC, feyzullah commented
@dannyroosevelt I created another PR [here](https://github.com/PipedreamHQ/pipedream/pull/3431). @jcortes can you please do another review?

2026-08-13 17:55 UTC, GTFalcao commented
Closing as outdated and superseded

2026-08-13 17:55 UTC, closed without merging