Delighted new action sending to people
PipedreamHQ/pipedream pull request #2817
Opened 2022-05-09 17:02 UTC by jcortes

This PR was uploaded by the user @nauxliu and has the fix reported at #2308 by QA

2022-05-09 17:02 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-05-09 18:14 UTC, michelle0927 requested changes

2022-05-09 18:14 UTC, michelle0927 commented on components/delighted/actions/sending-to-people/sending-to-people.mjs
> +  name: "Sending to people",
```suggestion
  name: "Sending to People",
```

2022-05-09 18:14 UTC, michelle0927 commented on components/delighted/actions/sending-to-people/sending-to-people.mjs
> +  version: "0.0.7",
Should be version 0.0.1
```suggestion
  version: "0.0.1",
```

2022-05-09 18:14 UTC, michelle0927 commented on components/delighted/delighted.app.mjs
> +  description: "The Delighted app that will be used to send the survey.",
These aren't needed.
```suggestion
```

2022-05-09 20:21 UTC, michelle0927 approved these changes

2022-05-13 15:22 UTC, dannyroosevelt commented
This is ready for release!

2022-05-14 21:22 UTC, merged