[Actions] JIRA (Create Issue)
PipedreamHQ/pipedream pull request #2911
Opened 2022-05-21 00:38 UTC by mattgauf

### Issue:
The current version of the `jira-create-issue` action requires both a `description` and a `reporter_id`. This leaves the action incompatible with some projects. 

- `description` requires use of the  'Atlassian Document Format' object structure to complete the API call. As of 2022-05-20 the API rejects calls that include an empty object (the props default) instead of a complete structure.
- Presence of `reporter` in the body triggers a '400 Bad Request' response when issuing the API call for team managed projects.

Additionally, in the V2 workflow editor, the code for a prebuilt action cannot be modified inline to remove this requirement. Forcing the user to choose the `jira-make-api-call` action and then copy code from this Github repo to selectively modify the action.

### Solution:
Make both `description` and `reporter_id` optional and implement conditionals to handle their presence.

- `description` is now optional, and has been changed to a string format prop. The new conditional creates a valid 'Atlassian Document Format' object from the value if it's included by the user.
- `reporter_id` is now optional, and the property `reporter` is now defined inside the conditional for `reporter_id`

2022-05-21 00:39 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-05-21 00:53 UTC, dylburger commented
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

2022-05-21 12:05 UTC, andrewjschuang requested changes
@mattgauf thanks for the contribution!

I noticed in lines 160-164 the `fields` object is still being built with `description` and `reporter_id`.

Also noted these are legacy actions, so we might refactor this soon to keep them up to date. If you wish to help us with this, you may start by reading [this docs](https://pipedream.com/docs/components/guidelines/#components-should-be-es-modules)!

2022-05-21 12:05 UTC, andrewjschuang commented
I'm moving this card to the To Do Column, once you're finished you can move this back to Ready for PR Review. Thanks!

2022-05-21 14:47 UTC, mattgauf commented
I've removed the fields from the initial object (an oversight as I was rebuilding the solution), and I committed the suggested changes.

2022-05-22 09:09 UTC, mattgauf commented
@andrewjschuang Sorry to bother you directly, but I can't seem to change the PR status in the project. I'm still a bit unfamiliar with the Github web interface.

Everything should be good to go for another PR Review. No rush, just wanted to follow up.

2022-05-30 12:11 UTC, lcaresia commented
I'm blocked until [this task](https://github.com/PipedreamHQ/pipedream/issues/1472) of @feyzullah be merged.

@feyzullah Call me on chat when its merged, thanks!

2022-07-06 23:54 UTC, dannyroosevelt commented
@lcaresia what's the status of this?

2022-07-07 11:29 UTC, lcaresia commented
@dannyroosevelt It has been resolved!

2022-08-11 18:59 UTC, mattgauf commented
@lcaresia / @dannyroosevelt

I just wanted to follow up on this. Is there anything I can do to help it along? I know there was working being put into refactoring all of the JIRA actions. So if this PR is out of date then does that mean the action it was meant to fix is good to go on production?

2022-08-15 12:33 UTC, lcaresia commented
@mattgauf I don't remember about this task, if possible check if it's working with the refactoration.

Anything call me on slack!

2022-08-15 13:46 UTC, andrewjschuang commented
Hey @mattgauf, I tested the refactored action and the problems you mentioned still occurred.
I've added your changes in a new PR #4010, please subscribe to it to receive the updates.

2022-08-15 17:24 UTC, mattgauf commented
Closing this PR

2022-08-15 17:24 UTC, closed without merging