[ACTION / SOURCE] Github new actions #1430
PipedreamHQ/pipedream pull request #2938
Opened 2022-05-24 17:02 UTC by lcaresia

2022-05-25 15:13 UTC, vellames-turing requested changes
Hi there, just some minors

2022-05-25 15:13 UTC, vellames-turing commented on components/github/sources/new-mention/new-mention.mjs
> +      this.db.set("login", user.login);
Can you create a setter function for `login`, please?

2022-05-26 19:12 UTC, vellames-turing approved these changes
Tks!

2022-06-16 18:19 UTC, lcaresia commented
@dannyroosevelt 

For some reason `new-organization` source in some Github accounts don't do the polling in the organizations.

I don't found how to resolve this issue, what I do in this case?

[More context here](https://pipedream-users.slack.com/archives/C01E5KCTR16/p1655128700257509)

2022-06-16 19:14 UTC, dannyroosevelt commented
> @dannyroosevelt
> 
> For some reason `new-organization` source in some Github accounts don't do the polling in the organizations.
> 
> I don't found how to resolve this issue, what I do in this case?
> 
> [More context here](https://pipedream-users.slack.com/archives/C01E5KCTR16/p1655128700257509)

Go ahead and skip that trigger for now

2022-06-23 15:30 UTC, vunguyenhung commented
Hello @lcaresia, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Github_1430.pdf](https://github.com/PipedreamHQ/pipedream/files/8968694/Github_1430.pdf)

2022-06-24 14:43 UTC, vunguyenhung commented
Hello, per discussion with @lcaresia, I have tested again and all test cases are passed. Ready for release!

[Github_1430_2142.pdf](https://github.com/PipedreamHQ/pipedream/files/8976981/Github_1430_2142.pdf)

2022-06-24 14:44 UTC, lcaresia commented
/approve

2022-06-24 14:50 UTC, michelle0927 approved these changes

2022-06-24 15:12 UTC, merged