Amqp source receive message
PipedreamHQ/pipedream pull request #2945
Opened 2022-05-24 20:27 UTC by jcortes

# Action
- [x] Send message

# Source
- [x] Receive message

2022-05-24 20:27 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-05-25 15:32 UTC, vellames-turing requested changes
Hi there, just some minors

2022-05-25 15:32 UTC, vellames-turing commented on components/amqp/actions/send-message/send-message.mjs
> +  description: "Send a new message to an AMQP 1.0 queue",
Could you please add a reference to `AMQP`?

2022-05-25 15:32 UTC, vellames-turing commented on components/amqp/actions/send-message/send-message.mjs
> +      console.log("Error sending message", JSON.stringify(error.innerError));
We don't wanna throw the error? Looks like if some error occurs we will just console. Maybe we could console and `throw error`?

2022-05-25 15:32 UTC, vellames-turing commented on components/amqp/sources/receive-message/receive-message.mjs
> +  description: "Emit new event for each new message in an AMQP 1.0 queue",
Could you please add some ref to `AMQP`, please?

2022-05-25 15:32 UTC, vellames-turing commented on components/amqp/sources/receive-message/receive-message.mjs
> +      console.log("Error receiving message", JSON.stringify(error));
We don't wanna throw the error? Looks like if some error occurs we will just console. Maybe we could console and `throw error`?

2022-05-26 20:10 UTC, vellames-turing commented on components/amqp/sources/receive-message/receive-message.mjs
> +      throw "Error receiving message from queue";
I am wondering if we can use `throw error`

2022-05-27 17:53 UTC, vellames-turing approved these changes
Tks

2022-06-01 14:28 UTC, vunguyenhung commented
Hello @jcortes, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[AMQP_2945.pdf](https://github.com/PipedreamHQ/pipedream/files/8815076/AMQP_2945.pdf)

2022-06-05 16:09 UTC, feyzullah approved these changes
LGTM

2022-06-06 14:52 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[AMQP_2945_2152.pdf](https://github.com/PipedreamHQ/pipedream/files/8845295/AMQP_2945_2152.pdf)

2022-06-06 15:02 UTC, merged