2854 kanbanize new actions
PipedreamHQ/pipedream pull request #2953
Opened 2022-05-25 15:06 UTC by alysonturing

[ACTIONS]
- added `List Tasks` action
- added `Create New Task` action
- added `Edit Task` action

Following the docs here: https://kanbanize.com/api

2022-05-25 15:07 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-05-25 15:46 UTC, vellames-turing requested changes
Hi there, tks for your PR. I saw some properties being repeated across the files. Ex: `boardId`, `type`, `assignee`, etc. Could you please move these repeated props to the `app`? Also, could you please add the `package` files?

2022-05-26 19:27 UTC, vellames-turing requested changes
Hi there, tks for the changes, I just left one more comment that I did not see before, sorry

2022-05-26 19:27 UTC, vellames-turing commented on components/kanbanize/actions/edit-task/edit-task.mjs
> +    if (response === 1) {
What about if the response is not 1? Can we handle all status properly? Is it possible to create some consts here to avoid magic numbers?

2022-05-27 17:54 UTC, vellames-turing commented on components/kanbanize/actions/edit-task/edit-task.mjs
> +    if (response === 1) {
tks!

2022-05-27 17:54 UTC, vellames-turing approved these changes
tks!

2022-05-30 08:30 UTC, DilanAthukorala commented
@alysonturing for **list_all_tasks** action getting invalid error - 500 when sending param '**lane**' along with '**column**' or '**section**' params
![image](https://user-images.githubusercontent.com/102980146/170951003-262876d8-7802-40ab-a97a-23b35dc60b9b.png)

2022-05-30 08:56 UTC, DilanAthukorala commented
@alysonturing 

when returning cards by passing **Archive Container = true** and **Show initiatives = false** ,,, this only returns archived cards in the initiative workflow. No archived cards in Cards workflow returned.

2022-05-30 13:18 UTC, alysonturing commented
> @alysonturing for **list_all_tasks** action getting invalid error - 500 when sending param '**lane**' along with '**column**' or '**section**' params ![image](https://user-images.githubusercontent.com/102980146/170951003-262876d8-7802-40ab-a97a-23b35dc60b9b.png)

may you please try again?
for me it’s working when I set `lane` along with `column`  and `section`
<img width="882" alt="Captura de Tela 2022-05-30 às 10 16 55" src="https://user-images.githubusercontent.com/103650302/171000516-e2c82f0c-a175-4c52-b28c-d9bf890920f7.png">

2022-05-30 13:21 UTC, alysonturing commented
> @alysonturing
> 
> when returning cards by passing **Archive Container = true** and **Show initiatives = false** ,,, this only returns archived cards in the initiative workflow. No archived cards in Cards workflow returned.

this is how their API works, the parameters are being sent straight direct to them

2022-05-30 13:29 UTC, alysonturing commented
/approve

2022-05-31 11:22 UTC, merged