new source
PipedreamHQ/pipedream pull request #3003
Opened 2022-05-30 18:06 UTC by luancazarine

Source
   - New list contact

2022-06-02 12:09 UTC, feyzullah requested changes
Hi @luancazarine I added just 2 comments. Can you please check?

2022-06-02 12:09 UTC, feyzullah commented on components/emailoctopus/emailoctopus.app.mjs
> +    },
According to [this doc](https://emailoctopus.com/api-documentation/lists/get-all-contacts), all results are not returned, where `page` defaults to `1` and `limit` defaults to `100`. Is it possible to have more than `100` contacts? If so can we just make sure that we are returning all contacts here? [This](https://github.com/PipedreamHQ/pipedream/blob/5a4392ae161a9f60ecda6cd501240b5af87f09a8/components/gorgias/gorgias.app.mjs#L127) can be a good example.

2022-06-02 22:58 UTC, feyzullah approved these changes
Thanks for the updates, approved

2022-06-06 10:48 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Email_Octopus_3303.pdf](https://github.com/PipedreamHQ/pipedream/files/8843823/Email_Octopus_3303.pdf)

2022-06-06 12:27 UTC, merged