[ACTION] Lusha #864
PipedreamHQ/pipedream pull request #3041
Opened 2022-06-02 19:18 UTC by lcaresia

@dannyroosevelt 

I create the actions based on API, but to test I will need a premium account.
Can I move this for review or I set as blocked for now?

2022-06-02 19:19 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-06-06 16:44 UTC, dannyroosevelt commented
> @dannyroosevelt
> 
> I create the actions based on API, but to test I will need a premium account. Can I move this for review or I set as blocked for now?

please move to review, and we can figure that out during QA

2022-06-13 16:03 UTC, jcortes requested changes
Hi @lcaresia just three minor observations everything else looks good to me. thanks

2022-06-13 16:03 UTC, jcortes commented on components/lusha/actions/find-company/find-contact.mjs
> +import lusha from "../../lusha.app.mjs";
Please rename this file to `find-company.mjs`

2022-06-20 15:04 UTC, vunguyenhung commented
Hello @dannyroosevelt, I faced the same issue as @lcaresia that I can not get the API Key since Lusha require Enterprise plan for it
![screenshot - 2022-06-20T215904 937](https://user-images.githubusercontent.com/18277920/174630354-00a04da8-b447-4545-9707-a3dcf1f51813.png)

Similar to Zoom Phone and others that requiring paid plan, I suggest that we ship this first and monitor if any customer faced any issue. Then if there's a bug then we can have a paid account to investigate. what do you think?

2022-06-21 08:18 UTC, vunguyenhung commented
Hello @lcaresia, as discussed with @dannyroosevelt, we agree to ship this Lusha component first for customer to use, then monitor if any customer faced any issue. Then if there's a bug then we can have a paid account to investigate.

cc @jcortes

2022-06-21 14:45 UTC, merged