Refactor and added new action bigquery-insert-rows
PipedreamHQ/pipedream pull request #3070
Opened 2022-06-07 00:09 UTC by jcortes

When trying to list datasets I get the following error:
```
Unable to detect a Project Id in the current environment. To learn more about authentication and Google APIs, visit: https://cloud.google.com/docs/authentication/getting-started
```

2022-06-08 11:56 UTC, lcaresia requested changes
Thanks for your contribution.

Just some minor changes!

2022-06-08 11:56 UTC, lcaresia commented on components/google_cloud/utils/base.mjs
> +};
Rename this file to `utils.mjs` and move to `common` folder.

2022-06-09 12:01 UTC, lcaresia submitted a review, later dismissed
LGTM!

2022-06-09 14:21 UTC, vunguyenhung commented
Hello @jcortes, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[BigTable3070.pdf](https://github.com/PipedreamHQ/pipedream/files/8871215/BigTable3070.pdf)

2022-06-10 21:42 UTC, jcortes commented
> Hello @jcortes, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information [BigTable3070.pdf](https://github.com/PipedreamHQ/pipedream/files/8871215/BigTable3070.pdf)

Hi @vunguyenhung can you please try to test again with latest change. Thanks in adance!

2022-06-13 13:24 UTC, vunguyenhung commented
Hello @jcortes, the source can load more rows now on the first run
![screencapture-pipedream-sources-dc-2EuRawb-2022-06-13-20_18_43](https://user-images.githubusercontent.com/18277920/173363283-ea7e78c3-4f16-43e9-bf8d-ddcbe0257180.png)

Though for new rows (that I have added via Pipedream Google Cloud - Insert BigQuery action), there is no new event emitted
Google Big Query
![Screen Shot 2022-06-13 at 20 23 23](https://user-images.githubusercontent.com/18277920/173363501-37b69904-f2b1-49b1-b49a-655a5931616d.png)

Pipedream Source events
![screencapture-pipedream-sources-dc-2EuRawb-2022-06-13-20_24_07](https://user-images.githubusercontent.com/18277920/173363591-67c4fbfb-06a8-4f51-bd54-9c6d5349f198.png)

Pipedream Source log
![screencapture-pipedream-sources-dc-2EuRawb-logs-2022-06-13-20_24_19](https://user-images.githubusercontent.com/18277920/173363671-fc0f0d81-6106-4e77-9058-a3391dcfc36a.png)

Could you check again?

2022-06-13 15:00 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Google_Cloud_3070.pdf](https://github.com/PipedreamHQ/pipedream/files/8892190/Google_Cloud_3070.pdf)

2022-06-13 21:35 UTC, jcortes commented
/approve

2022-06-13 21:45 UTC, dannyroosevelt approved these changes

2022-06-13 22:12 UTC, merged