Action freshdesk
PipedreamHQ/pipedream pull request #3115
Opened 2022-06-10 00:56 UTC by bush4u

2022-06-10 00:57 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-06-10 11:49 UTC, lcaresia requested changes
Thanks for your contribution!

I requested just a minor changes.

2022-06-10 11:49 UTC, lcaresia commented on components/freshdesk/actions/create-company/create-company.mjs
> +  version: "0.0.2",
```suggestion
  version: "0.0.1",
```

2022-06-10 11:49 UTC, lcaresia commented on components/freshdesk/actions/create-contact/create-contact.mjs
> +  description: "create a contact. [See docs here](https://developers.freshdesk.com/api/#companies)",
```suggestion
  description: "Create a contact. [See docs here](https://developers.freshdesk.com/api/#create_contact)",
```

You can check and fix this in other descriptions too.

2022-06-10 11:49 UTC, lcaresia commented on components/freshdesk/actions/create-contact/create-contact.mjs
> +  version: "0.0.2",
```suggestion
  version: "0.0.1",
```

You can check and fix this in other descriptions too.

2022-06-10 11:49 UTC, lcaresia commented on components/freshdesk/actions/get-ticket/get-ticket.mjs
> +    response && $.export("$summary", "Ticket found");
```suggestion
    response && $.export("$summary", "Successfully found ticket");
```

2022-06-10 11:49 UTC, lcaresia commented on components/freshdesk/freshdesk.app.mjs
> +      description: "ID of the primary company to which this contact belongs",
```suggestion
      description: "The ID of the company",
```

2022-06-10 11:49 UTC, lcaresia commented on components/freshdesk/freshdesk.app.mjs
> +        }));
```suggestion
        return constants.TICKET_STATUS;
```

2022-06-10 11:49 UTC, lcaresia commented on components/freshdesk/freshdesk.app.mjs
> +        }));
```suggestion
        return constants.TICKET_PRIORITY;
```

2022-06-10 11:49 UTC, lcaresia commented on components/freshdesk/freshdesk.app.mjs
> +          label: `${contact.name} | ${contact.email}`,
```suggestion
          label: contact?.email ?? contact?.name,
```

2022-06-10 11:49 UTC, lcaresia commented on components/freshdesk/package.json
> +}
```suggestion
}

```

2022-06-10 11:49 UTC, lcaresia commented on components/freshdesk/package.json
> +  "version": "0.0.2",
```suggestion
  "version": "0.0.1",
```

2022-06-10 11:49 UTC, lcaresia commented on components/freshdesk/package.json
> +  "description": "Pipedream Harvest Components",
```suggestion
  "description": "Pipedream Freshdesk Components",
```

2022-06-10 11:49 UTC, lcaresia commented on components/freshdesk/sources/new-contact/new-contact.mjs
> +            summary: `Contact name: ${contact.name}`,
```suggestion
            summary: `Contact name: ${contact.name}`,
            ts: Date.parse(contact.created_at),
```

2022-06-10 11:49 UTC, lcaresia commented on components/freshdesk/sources/new-ticket/new-ticket.mjs
> +            summary: `Ticket number: ${ticket.id}`,
```suggestion
            summary: `Ticket number: ${ticket.id}`,
            ts: Date.parse(ticket.created_at)
```

2022-06-10 16:57 UTC, lcaresia requested changes
Just need fix the versions.

2022-06-10 16:57 UTC, lcaresia commented on components/freshdesk/actions/get-ticket/get-ticket.mjs
> +  version: "0.0.2",
```suggestion
  version: "0.0.1",
```

2022-06-10 16:57 UTC, lcaresia commented on components/freshdesk/sources/new-contact/new-contact.mjs
> +  version: "0.0.2",
```suggestion
  version: "0.0.1",
```

2022-06-10 16:57 UTC, lcaresia commented on components/freshdesk/sources/new-ticket/new-ticket.mjs
> +  version: "0.0.2",
```suggestion
  version: "0.0.1",
```

2022-06-11 21:12 UTC, lcaresia approved these changes
LGTM!

2022-06-12 19:20 UTC, merged

2022-06-13 16:35 UTC, DilanAthukorala commented
@bush4u all action requests are success but nothing gets created on freshdesk app and api responses are not returned from the action component

freshdesk url - https://pipedream-help.freshdesk.com/

```
domain - pipedream-help
apikey -  662erykZvAU7NUzbBN
```

![image](https://user-images.githubusercontent.com/102980146/173400472-4cd5d3fb-ad70-461d-bf91-6afd1b68cf08.png)

2022-06-13 16:42 UTC, bush4u commented
Kindly let me check this

2022-06-13 17:23 UTC, bush4u commented
So, published the action, and tested.

I was able to create a company and I got API response.
I also confirmed that data was created on freshdesk portal. 

How can we narrow this down further to get the cause of the issue?



![image](https://user-images.githubusercontent.com/68253993/173409471-0044e573-1418-4363-925e-b41da313b6a4.png)
![image](https://user-images.githubusercontent.com/68253993/173409759-a765463e-733d-4a5d-9d94-e8af8e8609d3.png)

2022-06-13 19:44 UTC, DilanAthukorala commented
@bush4u in create_contact and create_ticket actions, the `Company ID` prop is listing the contact id list. 
![image](https://user-images.githubusercontent.com/102980146/173428450-18484eb5-6f97-49b1-8db5-526ccab1a912.png)


for create_ticket action params `subject , description` are **required** parameters.  
![image](https://user-images.githubusercontent.com/102980146/173429609-caac0943-2455-41fd-85ac-8f64100597b8.png)



for create_ticket action email prop does not retrieve any emails. Should we make it an input field?
![image](https://user-images.githubusercontent.com/102980146/173429897-90d6a1f8-65e3-493d-9e86-d9fd5ba89a29.png)



for create_ticket action observing following error when sending value for description_text

![image](https://user-images.githubusercontent.com/102980146/173431209-419cf7ac-ba09-4897-9575-8beac2c3997f.png)



No response for list all tickets action
![image](https://user-images.githubusercontent.com/102980146/173432077-d3675802-b79a-4981-9296-9cd073b1ed46.png)

2022-06-14 18:22 UTC, DilanAthukorala commented
Verification completed