[FEATURE] Improve Reddit sources to use global search endpoint #1513
PipedreamHQ/pipedream pull request #3154
Opened 2022-06-15 14:00 UTC by lcaresia

Added a action `search-post`, need test too.

2022-06-15 14:00 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-06-15 15:52 UTC, jcortes requested changes
HI @lcaresia I've added just one minor fix and it'll be ready for QA

2022-06-15 15:52 UTC, jcortes commented on components/reddit/reddit.app.mjs
> +      ].includes(statusCode);
```suggestion
      return [
        408,
        429,
        500,
      ].includes(statusCode);
```

2022-06-15 21:54 UTC, jcortes reviewed
Hi @lcaresia LGTM. Ready for QA!

2022-06-21 13:57 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Reddit_1513.pdf](https://github.com/PipedreamHQ/pipedream/files/8949538/Reddit_1513.pdf)

2022-06-21 13:58 UTC, lcaresia commented
/approve

2022-06-21 14:23 UTC, michelle0927 approved these changes

2022-06-21 14:44 UTC, merged