[TRIGGER AND ACTION] Toggl #3138
PipedreamHQ/pipedream pull request #3196
Opened 2022-06-20 17:30 UTC by lcaresia

2022-06-20 17:30 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-06-20 18:05 UTC, michelle0927 requested changes
I notice this is failing the Lint Code Base check. You probably just need to merge the master branch back into this one.

I see 3 triggers listed in the issue (https://github.com/PipedreamHQ/pipedream/issues/3138), but only one trigger in this PR. It's great to have a trigger that can handle multiple event types, but we also want to have the ones the issue specifies in case the user is looking for that specific one.

2022-06-20 18:05 UTC, michelle0927 commented on components/toggl/actions/get-current-time-entry/get-current-time-entry.mjs
> +  key: "tally-get-current-time-entry",
```suggestion
  key: "toggl-get-current-time-entry",
```

2022-06-20 18:05 UTC, michelle0927 commented on components/toggl/actions/get-time-entries/get-time-entries.mjs
> +  key: "tally-get-time-entries",
```suggestion
  key: "toggl-get-time-entries",
```

2022-06-20 18:05 UTC, michelle0927 commented on components/toggl/actions/get-time-entries/get-time-entries.mjs
> +  description: "Get the last thousand time entries. [See docs here](https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md#get-time-entries-started-in-a-specific-time-range)",
Could we add a `max` prop that defaults to 1000 in case the user would like to return less than 1000 entries?

2022-06-22 15:26 UTC, michelle0927 commented on components/toggl/sources/new-time-entry/new-time-entry.mjs
> +  description: "Emit new event on a time entry is updated. [See docs here](https://github.com/toggl/toggl_api_docs/blob/master/webhooks.md)",
I think `new-time-entry` and `new-update-time-entry` got switched.
```suggestion
  key: "toggl-new-time-entry",
  description: "Emit new event when a time entry is created. [See docs here](https://github.com/toggl/toggl_api_docs/blob/master/webhooks.md)",
```

2022-06-22 15:26 UTC, michelle0927 commented on components/toggl/sources/new-update-time-entry/new-update-time-entry.mjs
> +      return "created";
```suggestion
      return "updated";
```

2022-06-24 13:47 UTC, michelle0927 approved these changes

2022-06-26 14:49 UTC, DilanAthukorala commented
@lcaresia Observing following issues;

for **get_time_entry** action the url has spaces in between params causing 404 error
![image](https://user-images.githubusercontent.com/102980146/175819057-f75f53fa-982a-47de-8bee-bea13853ca9a.png)


for all sources only the first event is captured, All other events are not reflected. (applicable for all sources)
![image](https://user-images.githubusercontent.com/102980146/175819869-31686342-5fbd-43c1-a3fc-46f0a02c9e78.png)


for new webhook event source type of event is not displayed. 
![image](https://user-images.githubusercontent.com/102980146/175820021-bcb85a34-ea24-4533-8257-e2c53533a071.png)

2022-06-27 15:32 UTC, andrewjschuang submitted a review, later dismissed

2022-06-27 18:42 UTC, DilanAthukorala commented
@lcaresia  above issues are resolved. However I'm observing the following with new fixes

for Toggl **new_start_time** source, I'm receiving events for both **start** and **stop** the timer triggers. Instead we should receive only the timer starting event.

and for **new_time_entry** source, currently the event received is the starting timer event, I think instead it should trigger the stop timer event because it has the completed time record info

2022-06-28 06:59 UTC, DilanAthukorala commented
Verification Completed

2022-06-28 12:36 UTC, merged