pinterest sources & 1 action
PipedreamHQ/pipedream pull request #3253
Opened 2022-06-27 21:45 UTC by feyzullah

### Triggers
- |&check;| New Board
- |&check;| New pin
- |&cross;| New follower: Could not find API endpoint for fetching followers in API `v5`
### Actions
- |&check;| Create pin 

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/3253"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-06-27 21:46 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-06-28 14:15 UTC, andrewjschuang requested changes
@feyzullah thanks for the contribution!

Looking good, I've left some comments below.

2022-06-28 14:15 UTC, andrewjschuang commented on components/pinterest/pinterest.app.mjs
> +        const { bookmark } = prevContext || {};
**-Minor-**

```suggestion
        const bookmark = prevContext?.bookmark;
```

2022-06-28 14:15 UTC, andrewjschuang commented on components/pinterest/pinterest.app.mjs
> +        "user-agent": "@PipedreamHQ/pipedream v0.1",
**-Minor-**

```suggestion
        "User-Agent": "@PipedreamHQ/pipedream v0.1",
```

2022-06-28 14:15 UTC, andrewjschuang commented on components/pinterest/pinterest.app.mjs
> +        url: await this._getUrl(path),
Is there a reason for this method to be `async`?

2022-06-28 14:15 UTC, andrewjschuang commented on components/pinterest/pinterest.app.mjs
> +      return await this._makeRequest({
`return await` [is not necessary](https://eslint.org/docs/latest/rules/no-return-await) unless it's inside a `try/catch` statement

2022-06-30 15:08 UTC, andrewjschuang approved these changes
Thanks for the changes, LGTM!

I've just left a comment about using `createdTime` instead of `Date.now()`

2022-07-01 14:27 UTC, vunguyenhung commented
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Pinterest_3253.pdf](https://github.com/PipedreamHQ/pipedream/files/9029597/Pinterest_3253.pdf)

2022-07-11 11:21 UTC, feyzullah commented
closing this one, created another PR because of merging issues [new PR link](https://github.com/PipedreamHQ/pipedream/pull/3376)

2022-07-11 11:21 UTC, closed without merging