Fix an error trying to assign to an undefined object when using the Reply To parameters
PipedreamHQ/pipedream pull request #3278
Opened 2022-06-30 15:37 UTC by aca02djr

2022-06-30 15:38 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-06-30 16:34 UTC, andrewjschuang requested changes
@aca02djr thanks for the contribution!

Just need to change formatting for ESLint

2022-06-30 16:34 UTC, andrewjschuang commented on components/sendgrid/actions/send-email-multiple-recipients/send-email-multiple-recipients.mjs
> +      replyTo = { email: this.replyToEmail };
```suggestion
      replyTo = {
        email: this.replyToEmail,
      };
```

2022-06-30 16:34 UTC, andrewjschuang commented on components/sendgrid/actions/send-email-single-recipient/send-email-single-recipient.mjs
> +      replyTo = { email: this.replyToEmail };
```suggestion
      replyTo = {
        email: this.replyToEmail,
      };
```

2022-07-01 14:43 UTC, vunguyenhung commented
Since the user doesn't have write permission, I will merge this PR on behave of him 🙏

2022-07-01 14:44 UTC, merged