Create Payment #3352
PipedreamHQ/pipedream pull request #3361
Opened 2022-07-07 23:23 UTC by lcaresia

2022-07-07 23:24 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-07-08 16:11 UTC, vellames-turing requested changes
Hi there, I left some comments

2022-07-08 16:11 UTC, vellames-turing commented on components/quickbooks/actions/create-bill/create-bill.mjs
>      return await axios($, {
Could you please move this call to `app`?

2022-07-08 16:11 UTC, vellames-turing commented on components/quickbooks/actions/create-customer/create-customer.mjs
>      return await axios($, {
Could you please move this call to `app`?

2022-07-08 16:11 UTC, vellames-turing commented on components/quickbooks/actions/create-invoice/create-invoice.mjs
>      return await axios($, {
Could you please move this call to `app`?

2022-07-08 16:11 UTC, vellames-turing commented on components/quickbooks/actions/create-payment/create-payment.mjs
> +    response && $.export("summary", "Successfully created payment");
Could you please use a regular `if` instead of `&&` operator?

2022-07-08 16:11 UTC, vellames-turing commented on components/quickbooks/actions/get-bill/get-bill.mjs
>      return await axios($, {
Could you please move this call to `app`?

2022-07-08 16:11 UTC, vellames-turing commented on components/quickbooks/actions/get-customer/get-customer.mjs
>      return await axios($, {
Could you please move this call to `app`?

2022-07-12 12:47 UTC, feyzullah requested changes
Hi @lcaresia, I added some comments. Can you please check?

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/create-bill/create-bill.mjs
>      minorversion: {
```suggestion
    minorVersion: {
```
Optionally, we can use camel case here.

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/create-bill/create-bill.mjs
> +      $.export("summary", "Successfully created bill");
If there is an id or a name in the response, can we add it to `summary`?

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/create-customer/create-customer.mjs
>      minorversion: {
Since it is used everywhere, can we move `minorversion` prop to the app file?

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/create-customer/create-customer.mjs
> +      $.export("summary", "Successfully created customer");
Can we add customer name or id to `summary`

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/create-invoice/create-invoice.mjs
> +      $.export("summary", "Successfully created invoice");
If there is an invoice id in the response, can we add it to `summary`?

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/create-payment/create-payment.mjs
> +      $.export("summary", "Successfully created payment");
Again if there is a payment id, can we add it to `summary`?

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/get-my-company/get-my-company.mjs
>    description: "Gets info about a company.",
Can we add a link to the developer page if there is one?

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/get-my-company/get-my-company.mjs
> +    const response = await this.quickbooks.getBill({
Is `getBill` the correct call?

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/create-invoice/create-invoice.mjs
> +    lineItems: {
Can we move `lineItems` to the app file? It is used in here and in `create-invoice`

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/create-invoice/create-invoice.mjs
> +    customerRefValue: {
Can we move `customerRefValue` to the app file? It is used here, and in `create-payment`

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/create-invoice/create-invoice.mjs
> +    customerRefName: {
Can we move `customerRefName` to the app file? It is used here and in `create-payment`

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/create-invoice/create-invoice.mjs
> +    currencyRefValue: {
Can we move `currencyRefValue` to the app file? It is used here, in `create-payment`, in `update-customer` and in `create-bill`

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/create-invoice/create-invoice.mjs
> +    currencyRefName: {
Can we move `currencyRefName` to the app file? It is used here, in `create-payment`, in `update-customer` and in `create-bill`

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/get-customer/get-customer.mjs
> +    const response = await this.quickbooks.getBill({
Is `getBill` the correct call?

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/get-invoice/get-invoice.mjs
> +    const response = await this.quickbooks.getBill({
Is `getBill` the correct call?

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/get-purchase-order/get-purchase-order.mjs
> +    const response = await this.quickbooks.getBill({
Is `getBill` the correct call?

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/get-purchase/get-purchase.mjs
> +    const response = await this.quickbooks.getBill({
Is `getBill` the correct call?

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/get-sales-receipt/get-sales-receipt.mjs
> +    const response = await this.quickbooks.getBill({
Is `getBill` the correct call?

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/get-time-activity/get-time-activity.mjs
> +    const response = await this.quickbooks.getBill({
Is `getBill` the correct call?

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/sandbox-search-invoices/sandbox-search-invoices.mjs
> +    includeClause: {
Can we move `includeClause` to the app file? It is used in all querying actions.

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/sandbox-search-invoices/sandbox-search-invoices.mjs
> +    maxResults: {
Can we move `maxResults` to the app file? It is used in all querying actions.

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/sandbox-search-invoices/sandbox-search-invoices.mjs
> +    orderClause: {
Can we move `orderClause` to the app file? It is used in all querying actions.

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/sandbox-search-invoices/sandbox-search-invoices.mjs
> +    startPosition: {
Can we move `startPosition` to the app file? It is used in all querying actions.

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/sandbox-search-invoices/sandbox-search-invoices.mjs
> +    whereClause: {
Can we move `whereClause` to the app file? It is used in all querying actions.

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/update-customer/update-customer.mjs
> +    displayName: {
Can we move `displayName` to the app file? It is used here and in `create-customer`

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/update-customer/update-customer.mjs
>      title: {
Can we move `title` to the app file? It is used here and in `create-customer`

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/update-customer/update-customer.mjs
> +    givenName: {
Can we move `givenName` to the app file? It is used here and in `create-customer`

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/update-customer/update-customer.mjs
> +    middleName: {
Can we move `middleName` to the app file? It is used here and in `create-customer`

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/update-customer/update-customer.mjs
> +    familyName: {
Can we move `familyName` to the app file? It is used here and in `create-customer`

2022-07-12 12:47 UTC, feyzullah commented on components/quickbooks/actions/update-customer/update-customer.mjs
>      suffix: {
Can we move `suffix` to the app file? It is used here and in `create-customer`

2022-07-12 15:33 UTC, feyzullah approved these changes
Thanks for the updates, LGTM!

2022-07-12 17:36 UTC, feyzullah commented
Hi @lcaresia there is [another PR](https://github.com/PipedreamHQ/pipedream/pull/3418) which just updates url for `get-invoice`, and it was merged. Can you please check and resolve the conflicts if any?

2022-07-12 17:40 UTC, feyzullah approved these changes

2022-07-13 13:20 UTC, DilanAthukorala commented
Verification completed successfully, This is ready for release.

2022-07-13 13:21 UTC, lcaresia commented
/approve

2022-07-13 13:22 UTC, feyzullah approved these changes

2022-07-13 13:27 UTC, merged