Trigger bitbucket rest api event
PipedreamHQ/pipedream pull request #3380
Opened 2022-07-08 20:51 UTC by bush4u

2022-07-08 20:51 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-07-08 20:51 UTC, bush4u commented
The following historical data were skipped due to unclear data source. 

new-pipeline-event
new-repository-event
new-workspace-event
watch-user

2022-07-11 18:06 UTC, feyzullah requested changes
Hi @bush4u, it looks great overall. I added a few comments. Can you please check?

2022-07-11 18:54 UTC, bush4u commented on components/bitbucket/bitbucket.app.mjs
> +    },
The function is actually not in us. I have taken it out

2022-07-11 19:03 UTC, bush4u commented on components/bitbucket/sources/new-commit-comment/new-commit-comment.mjs
> +          pagelen: 25,
Done

2022-07-11 19:09 UTC, bush4u commented on components/bitbucket/sources/new-commit-comment/new-commit-comment.mjs
> +        } while (true);
Thanks for the suggestion. 

The issue here is that we need 25 historical data maximum. 

There might be a challenge with this suggestion. 
Imagine there are 25 commits with 30 comments each, the total commit comments would be 750 commit-comments which is not what we want. What we want is 25 historical data of commit-comments.

2022-07-12 12:51 UTC, feyzullah submitted a review, later dismissed
Thanks, LGTM!

2022-07-13 14:21 UTC, DilanAthukorala commented
@bush4u following issues are observed;

1.  "New Branch" source events are only triggered at the point of source creation/deployment for already existing branches. Events received for new branches after the deployment are not reflected.
![image](https://user-images.githubusercontent.com/102980146/178748074-078a849b-6562-41da-b8b6-f0c92b9346f5.png)




2.  "New Branch" source gets events from other actions such as commits. It should trigger events only for New Branch events. 
![image](https://user-images.githubusercontent.com/102980146/178748556-8eae0f75-6c36-4c04-9c97-c56c32124033.png)



3.  "New Pipeline Event" source gets an error upon creation when previous data is not available
![image](https://user-images.githubusercontent.com/102980146/178751386-7d6fc670-8ad5-4c35-9faf-161be8828c96.png)




4. "New Repository Events" source gets error upon creation when previous data not available 
![image](https://user-images.githubusercontent.com/102980146/178753716-5a4912e9-747a-43f0-8e83-37e3d13b9b26.png)

2022-07-13 17:23 UTC, bush4u commented
> @bush4u following issues are observed;
> 
> 1. "New Branch" source events are only triggered at the point of source creation/deployment for already existing branches. Events received for new branches after the deployment are not reflected.
>    ![image](https://user-images.githubusercontent.com/102980146/178748074-078a849b-6562-41da-b8b6-f0c92b9346f5.png)
> 2. "New Branch" source gets events from other actions such as commits. It should trigger events only for New Branch events.
>    ![image](https://user-images.githubusercontent.com/102980146/178748556-8eae0f75-6c36-4c04-9c97-c56c32124033.png)
> 3. "New Pipeline Event" source gets an error upon creation when previous data is not available
>    ![image](https://user-images.githubusercontent.com/102980146/178751386-7d6fc670-8ad5-4c35-9faf-161be8828c96.png)
> 4. "New Repository Events" source gets error upon creation when previous data not available
>    ![image](https://user-images.githubusercontent.com/102980146/178753716-5a4912e9-747a-43f0-8e83-37e3d13b9b26.png)

Hi @DilanAthukorala ,
Thanks for the review. Kindly find my comments below;

Issue 1: I think this is a bug on that was just noticed. I did not work on any of the post deployment events. 
The scope of the the issue I worked on is simply on historical data (Deploy event). 
Would it be okay if a new issue is logged for that and I will pick it up?

Issue 2: Same as Issue 1.

Issue 3 and issue 4: I have fixed these

2022-07-14 10:17 UTC, DilanAthukorala commented
@bush4u New Pipeline Events are not emitted and throw the following error
![image](https://user-images.githubusercontent.com/102980146/178959002-5dc3d285-bb06-4f5c-843a-101248b75f8e.png)

2022-07-14 16:42 UTC, DilanAthukorala commented
@bush4u Noted, we will track the issues separately as a bug.

2022-07-14 17:19 UTC, bush4u commented
> @bush4u Noted, we will track the issues separately as a bug.

Great. Thanks

2022-07-18 14:46 UTC, bush4u commented
/approve

2022-07-18 14:47 UTC, lcaresia approved these changes
LGTM!

2022-07-18 14:48 UTC, merged