Paytrace actions, refactored @isaiahtaylor's PR
PipedreamHQ/pipedream pull request #3431
Opened 2022-07-13 17:38 UTC by feyzullah

Refactored @isaiahtaylor's [PR](https://github.com/PipedreamHQ/pipedream/pull/2775)
To QA reviewer, I could not create a sandbox or formal account on Paytrace, just refactored the code already written, I hope it works well

2022-07-13 17:38 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-07-18 14:34 UTC, lcaresia requested changes
Thanks for your contribution!

I requested just a little changes.

2022-07-18 14:34 UTC, lcaresia commented on components/paytrace/actions/batch-summary/batch-summary.mjs
> +  description: "This method can be used to export a summary of specific batch details or currently pending settlement details by card and transaction type.  If no optional parameter is provided, the
Add docs link in the description.

You can do this for the other actions too.

```suggestion
  description: "This method can be used to export a summary of specific batch details or currently pending settlement details by card and transaction type.  If no optional parameter is provided, the latest batch details will be returned. [See docs here](<docs_link>)",
```

2022-07-18 14:34 UTC, lcaresia commented on components/paytrace/actions/list-batch-transactions/list-batch-transactions.mjs
> +  description: "This method can be used to export settled transaction details within a specific batch.  This method will return one or more transaction records.",
Add docs link in the description.

2022-07-18 14:34 UTC, lcaresia commented on components/paytrace/actions/list-batches/list-batches.mjs
> +  description: "This method can be used to export a set of batch summary details with a provided date range.  This method will return one or more batch summary records.",
Add docs link in the description.

2022-07-18 14:34 UTC, lcaresia commented on components/paytrace/actions/list-transactions/list-transactions.mjs
> +  description: "This method can be used to export a set of credit card transaction details with a provided date range.  You can optimize your search by providing optional parameters.",
Add docs link in the description.

2022-07-18 14:34 UTC, lcaresia commented on components/paytrace/actions/list-transactions/list-transactions.mjs
> +      options: [
Move this for a constants file.

E.g. `common/constants.mjs`

2022-07-18 14:34 UTC, lcaresia commented on components/paytrace/paytrace.app.mjs
> +        "Authorization": `Bearer ${this.$auth.oauth_access_token}`,
Move this for a getter method.

```suggestion
        "Authorization": `Bearer ${this._accessToken()}`,
```

2022-07-19 16:24 UTC, lcaresia approved these changes
LGTM!

2022-07-20 09:42 UTC, vunguyenhung commented
Hello @dannyroosevelt, I'm also can not create personal account on PayTrace. I think we can either get the account as Pipedream org, or merge this PR and monitor. What do you think?

2022-07-20 18:31 UTC, dannyroosevelt commented
> Hello @dannyroosevelt, I'm also can not create personal account on PayTrace. I think we can either get the account as Pipedream org, or merge this PR and monitor. What do you think?

Go ahead and publish, and we'll see if we can get help QA'ing from the community. Thanks, Leo!

2022-07-21 13:21 UTC, merged