Update create-or-update-contact.mjs
PipedreamHQ/pipedream pull request #3470
Opened 2022-07-19 09:54 UTC by daltonlet

2022-07-19 09:54 UTC, dylburger commented
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

2022-07-19 09:54 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-07-19 11:24 UTC, lcaresia requested changes
Just a minor fix.

2022-07-19 11:24 UTC, lcaresia commented on components/activecampaign/actions/create-or-update-contact/create-or-update-contact.mjs
> +    city: {
Is this case the prop `city` is created, but isn't sent in the request.

Can you check this?

2022-07-29 13:30 UTC, vunguyenhung commented
Hello @daltonlet, I will close this PR since there's no update on this for more than 10 days. Kindly create a new Github issue or PR if needed. Thanks!

2022-07-29 13:30 UTC, closed without merging

2022-10-11 08:07 UTC, daltonlet commented
Hi! I ended up getting this resolved by contacting your dev team directly. There was an issue with the [{field, value}] pairs on the backend where Pipedream wasn’t recognizing ActiveCampaign's custom fields at all. That was since resolved yesterday! Kindly disregard these changes!
On Jul 28, 2022, 6:30 AM -0700, Leo ***@***.***>, wrote:
> Hello @daltonlet, do you have the bandwidth to resolve the change requested, or you want our component dev to take over?
> I've checked the Active Campaign API as the image below and it doesn't have city field available. Could you use fieldValues prop instead? For example, you can set fieldValues prop with value {{ [{"city": "Ho Chi Minh"}] }}
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>