Actions and triggers convertkit
PipedreamHQ/pipedream pull request #3508
Opened 2022-07-22 18:58 UTC by bush4u

2022-07-22 18:59 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-07-24 20:11 UTC, lcaresia requested changes
Thanks for your contribution!

Just minors fixes!

2022-07-24 20:11 UTC, lcaresia commented on components/convertkit/actions/add-subscriber-to-form/add-subscriber-to-form.mjs
> +  version: "0.0.2",
```suggestion
  version: "0.0.1",
```

2022-07-24 20:11 UTC, lcaresia commented on components/convertkit/actions/add-subscriber-to-form/add-subscriber-to-form.mjs
> +    response && $.export("$summary", "Successfully added subscriber to form");
Use a normal `if` here.

```suggestion
    response && $.export("$summary", "Successfully added subscriber to form");
```

2022-07-24 20:11 UTC, lcaresia commented on components/convertkit/actions/list-subscribers/list-subscribers.mjs
> +  version: "0.0.2",
```suggestion
  version: "0.0.1",
```

2022-07-24 20:11 UTC, lcaresia commented on components/convertkit/actions/list-subscribers/list-subscribers.mjs
> +    console.log(data);
```suggestion
```

2022-07-24 20:11 UTC, lcaresia commented on components/convertkit/actions/list-subscribers/list-subscribers.mjs
> +    data.length && $.export("$summary", "Successfully listed subscribers");
Use a normal `if` here.

2022-07-24 20:11 UTC, lcaresia commented on components/convertkit/actions/view-single-subscribers/view-single-subscribers.mjs
> +  version: "0.0.2",
```suggestion
  version: "0.0.1",
```

2022-07-24 20:11 UTC, lcaresia commented on components/convertkit/actions/view-single-subscribers/view-single-subscribers.mjs
> +    response && $.export("$summary", "Successfully found subscriber");
Use a normal `if` here.

2022-07-24 20:11 UTC, lcaresia commented on components/convertkit/sources/new-subscriber-instant/new-subscriber-instant.mjs
> +  version: "0.0.2",
```suggestion
  version: "0.0.1",
```

2022-07-24 20:11 UTC, lcaresia commented on components/convertkit/sources/new-subscriber-instant/new-subscriber-instant.mjs
> +      if (!body?.subscriber) return;
```suggestion
      if (!body?.subscriber) {
        return;
      }
```

2022-07-24 20:11 UTC, lcaresia commented on components/convertkit/sources/new-unsubscription-instant/new-unsubscription-instant.mjs
> +  version: "0.0.2",
```suggestion
  version: "0.0.1",
```

2022-07-24 20:11 UTC, lcaresia commented on components/convertkit/sources/new-unsubscription-instant/new-unsubscription-instant.mjs
> +      if (!body?.subscriber) return;
```suggestion
      if (!body?.subscriber) { 
        return;
      }
```

2022-07-24 20:11 UTC, lcaresia commented on components/convertkit/sources/webhook-events/webhook-events.mjs
> +  version: "0.0.2",
```suggestion
  version: "0.0.1",
```

2022-07-25 13:30 UTC, lcaresia approved these changes
LGTM!

2022-07-26 13:47 UTC, vunguyenhung commented
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Coverkit_3486_2046.pdf](https://github.com/PipedreamHQ/pipedream/files/9190341/Coverkit_3486_2046.pdf)

2022-07-27 11:36 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Coverkit_3486_1836.pdf](https://github.com/PipedreamHQ/pipedream/files/9198125/Coverkit_3486_1836.pdf)

2022-07-27 16:24 UTC, bush4u commented
/approve

2022-07-27 16:28 UTC, jcortes approved these changes
Approved!

2022-07-27 16:40 UTC, merged