3636 gist
PipedreamHQ/pipedream pull request #3940
Opened 2022-08-04 20:06 UTC by luancazarine

Triggers
  - New Contact (Polling)

Actions
  - Add Tag to an Existing Contact
  - Create or Update Contact
  - Remove Tag From Existing Contact
  - Find a Contact

2022-08-04 20:06 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-08-05 15:10 UTC, michelle0927 submitted a review, later dismissed
Left some comments about updating the `tagId` prop to use `withLabel`. Note: I haven't tested anything, so make sure to test any changes.

2022-08-05 15:10 UTC, michelle0927 commented on components/gist/gist.app.mjs
> +    },
This seems like a good opportunity to use `withLabel`. If you set `withLabel` to true, the prop value will contain `tagId.value` and `tagId.label`
```suggestion
    tagId: {
      label: "Tag",
      description: "The tag that will be added",
      type: "integer",
      async options({ page }) {
        const { tags } = await this.listTags({
          params: {
            page: page + 1,
          },
        });

        return tags.map(({
          name, id,
        }) => ({
          label: name,
          value: id,
        })) || [];
      },
      withLabel: true,
    },
```

2022-08-05 15:10 UTC, michelle0927 commented on components/gist/actions/add-tag-to-contact/add-tag-to-contact.mjs
> +    };
If we change `tagId` to use `withLabel`, we can update this:
```suggestion
    tagId: {
      propDefinition: [
        gist,
        "tagId",
      ],
    },
  },
  async run({ $ }) {
    const data = {
      id: this.tagId.value,
      name: this.tagId.label,
      contacts: this.contactId.map((contactId) => {
        return {
          id: `${contactId}`,
        };
      }),
    }
```

2022-08-05 15:10 UTC, michelle0927 commented on components/gist/actions/add-tag-to-contact/add-tag-to-contact.mjs
> +    $.export("$summary", `Successfully added tag ${tag.name} to contact`);
```suggestion
    $.export("$summary", `Successfully added tag ${this.tagId.label} to contact`);
```

2022-08-05 15:10 UTC, michelle0927 commented on components/gist/actions/remove-tag-from-contact/remove-tag-from-contact.mjs
> +      type: "string",
```suggestion
```

2022-08-05 15:10 UTC, michelle0927 commented on components/gist/actions/remove-tag-from-contact/remove-tag-from-contact.mjs
> +    $.export("$summary", `Successfully removed tag ${tag.name} from contact${
If we change tagId to use withLabel, we can update this:
```suggestion
    const data = {
      id: this.tagId.value,
      name: this.tagId.label,
      contacts: this.contactId.map((contactId) => {
        return {
          id: `${contactId}`,
          untag: true,
        };
      }),
    };

    const response = await this.gist.updateTagToContact({
      $,
      data,
    });

    $.export("$summary", `Successfully removed tag ${this.tagId.label} from contact${
```

2022-08-05 15:10 UTC, michelle0927 commented on components/gist/actions/remove-tag-from-contact/remove-tag-from-contact.mjs
> +    }`);
```suggestion
      this.contactId.length > 1
        ? "s"
        : ""
    }`);
```

2022-08-12 00:09 UTC, andrewjschuang reviewed
I've left some comments below.
Oh, and `@pipedream/platform` dependency is missing in `package.json`

2022-08-12 00:09 UTC, andrewjschuang commented on components/gist/sources/new-contact/new-contact.mjs
> +    console.log("Raw received event:");
I think the message may be misleading

```suggestion
    console.log("Run started:");
```

2022-08-12 00:09 UTC, andrewjschuang commented on components/gist/actions/add-tag-to-contact/add-tag-to-contact.mjs
> +  key: "gist-add-tag-to-contact",
Shouldn't this all be in plural (contacts)?

2022-08-15 15:54 UTC, vellames requested changes
Hey, just left one comment

2022-08-15 15:54 UTC, vellames commented on components/gist/actions/remove-tag-from-contact/remove-tag-from-contact.mjs
> +      contacts: this.contactId.map((contactId) => {
```suggestion
      contacts: this.contactId.map((contactId) => ({
          id: String(contactId),
          untag: true,
      ))
```

2022-08-15 19:40 UTC, vellames approved these changes
lgtm

2022-08-17 08:52 UTC, vunguyenhung commented
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Gist_3940_1550.pdf](https://github.com/PipedreamHQ/pipedream/files/9358005/Gist_3940_1550.pdf)

2022-08-18 12:37 UTC, vellames approved these changes

2022-08-18 20:22 UTC, luancazarine commented
Waiting for resolution
https://github.com/PipedreamHQ/pipedream/issues/4021

2023-10-25 17:29 UTC, michelle0927 submitted a review, later dismissed
LGTM!

2023-10-27 12:08 UTC, luancazarine commented
/approve

2023-10-27 14:16 UTC, michelle0927 approved these changes

2023-10-27 15:34 UTC, merged