3864 lemlist
PipedreamHQ/pipedream pull request #4002
Opened 2022-08-12 20:57 UTC by luancazarine

Triggers
  - New Activity
  - Unsubscribed Recipient
 
Actions
  - Mark a Lead From All Campaigns as Interested
  - Mark a Lead From One Campaign as Interested
  - Add Lead to Campaign
  - Mark a Lead From All Campaigns as Not Interested
  - Mark a Lead From One Campaign as Not Interested
  - Pause Lead From All Campaigns
  - Remove Lead From Campaign
Remove Lead From Unsubscribe
  - Resume Lead From All Campaigns
Stop Emailing a Lead in a Campaign
  - Add Recipient to Unsubscribe List
  - Update Lead From Campaign
Search Lead
Find or Create Lead

2022-08-12 20:57 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-08-16 12:59 UTC, vellames requested changes
Just some changes

2022-08-16 12:59 UTC, vellames commented on components/lemlist/actions/unsubscribe-lead-from-a-campaign/unsubscribe-lead-from-a-campaign.mjs
> +      async options({ campaignId }) {
Why change the options here? Can we do it on `app`?

2022-08-16 12:59 UTC, vellames commented on components/lemlist/actions/mark-lead-from-one-campaigns-as-notinterested/mark-lead-from-one-campaigns-as-notinterested.mjs
> +      async options({ campaignId }) {
Why change the options here? Can we do it on `app`?

2022-08-16 12:59 UTC, vellames commented on components/lemlist/actions/update-lead-in-a-campaign/update-lead-in-a-campaign.mjs
> +      async options({ campaignId }) {
Why change the options here? Can we do it on `app`?

2022-08-16 12:59 UTC, vellames commented on components/lemlist/lemlist.app.mjs
> +        const results = await this.listCampaigns({
Why change the options here? Can we do it on `app`?

2022-08-16 22:37 UTC, vellames submitted a review, later dismissed

2022-08-17 09:24 UTC, DilanAthukorala commented
@luancazarine Observing following issues

1. For actions - **delete_lead_from_campaign** , **mark_lead_from_one_campaigns_as_interested** , **mark_lead_from_one_campaigns_as_notinterested** , **unsubscribe_lead_from_a_campaign** , **update_lead_in_a_campaign** 

- Unable to delete a lead, observing - (404 - Not Found)

![image](https://user-images.githubusercontent.com/102980146/185079337-b65c3e47-380e-42fb-8210-d7312cba9b8e.png)




2. For **New_Activity** and **New_Unsubscribed** Sources - Missing Auth Params in the UI

![image](https://user-images.githubusercontent.com/102980146/185083916-0c26b3ef-cb82-49f4-a18d-792fcf0f93a9.png)
![image](https://user-images.githubusercontent.com/102980146/185084016-684387e8-f71a-484c-9be2-42cfdea8d59b.png)

2022-08-17 13:07 UTC, luancazarine commented
@DilanAthukorala I'm sorry, I don't know what happened with your source tests, but they actually have auth params
![image](https://user-images.githubusercontent.com/5638699/185141871-b8703bf6-ec40-4c37-9410-5faec45088c9.png)
![image](https://user-images.githubusercontent.com/5638699/185141904-7b2a8e48-96ed-4199-b490-40ad59e0a628.png)

2022-08-17 15:30 UTC, DilanAthukorala commented
@luancazarine Issue fixes are verified and one minor issue observed in update_lead_in_a_campaign action where value for param "IceBreaker" is not getting updated in lemlist.

2022-08-22 21:11 UTC, feyzullah requested changes
Hi @luancazarine I added just a few comments. And can you please add a `package.json`?

2022-08-22 21:11 UTC, feyzullah commented on components/lemlist/actions/mark-lead-from-all-campaigns-as-notinterested/mark-lead-from-all-campaigns-as-notinterested.mjs
> +  description: "This action marks a specific lead as not interested using its email in all campaigns. [See the docs here](https://developer.lemlist.com/#mark-as-interested-a-specific-lead-by-email)",
This link might not be correct
```suggestion
  description: "This action marks a specific lead as not interested using its email in all campaigns. [See the docs here](https://developer.lemlist.com/#mark-as-not-interested-a-specific-lead-by-email)",
```

2022-08-24 17:41 UTC, feyzullah commented
Hi @luancazarine is this ready for PR review?

2022-08-24 20:04 UTC, feyzullah submitted a review, later dismissed

2022-08-24 21:51 UTC, DilanAthukorala commented
@luancazarine After the changes there's an issue with listing the email addresses of the leads
![image](https://user-images.githubusercontent.com/102980146/186529993-6da9dedb-92e8-43dd-8bf0-ba1d466abe29.png)

2022-08-24 22:12 UTC, DilanAthukorala commented
Verification completed, This is ready for release.

2022-08-25 20:53 UTC, luancazarine commented
/approve

2022-08-25 20:55 UTC, feyzullah approved these changes

2022-08-25 20:59 UTC, merged