Create Source
PipedreamHQ/pipedream pull request #4080
Opened 2022-08-24 15:16 UTC by luancazarine

Trigger:
 - New Ticket

2022-08-24 15:16 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-08-24 16:40 UTC, feyzullah submitted a review, later dismissed

2022-08-24 22:05 UTC, DilanAthukorala commented
@luancazarine observing following issues;

1. Please correct the type error shown below
![image](https://user-images.githubusercontent.com/102980146/186531194-f2b54f7f-1647-436e-882f-e48a49719933.png)


2. observing following error when creating the source
![image](https://user-images.githubusercontent.com/102980146/186531949-d568fa97-79a9-40c2-906f-6f654ed07155.png)

2022-08-24 22:24 UTC, todsac commented
I fixed the typo

2022-09-05 13:00 UTC, lcaresia requested changes
Thanks for your contribution!

I requested just some fixes.

2022-09-05 13:00 UTC, lcaresia commented on components/estreamdesk/estreamdesk.app.mjs
> +        "apiKey": `${this.$auth.api_key}`,
Move this to a getter method.

```suggestion
        "apiKey": `${this._apiKey()}`,
```

2022-09-05 19:58 UTC, jcortes requested changes
Hi @luancazarine I've just added one simple suggestion. Thanks

2022-09-05 19:58 UTC, jcortes commented on components/estreamdesk/estreamdesk.app.mjs
> +    async listTickets({ ...args } = {}) {
```suggestion
    async listTickets(args = {}) {
```

2022-09-06 15:37 UTC, jcortes approved these changes
Hi @luancazarine LGTM! Ready for QA!

2022-09-06 16:07 UTC, DilanAthukorala commented
Verification completed and ready for release.

2022-09-08 11:38 UTC, luancazarine commented
/approve

2022-09-08 15:12 UTC, jcortes approved these changes
Approved!

2022-09-08 20:19 UTC, merged