3977 wildberries actions
PipedreamHQ/pipedream pull request #4111
Opened 2022-08-27 22:10 UTC by alysonturing

Actions
- List orders
- List orders stickers (regular and as pdf)
- Update order status

2022-08-27 22:11 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-08-29 14:21 UTC, lcaresia requested changes
Thanks for your contribution.

Just some fixes!

2022-08-29 14:21 UTC, lcaresia commented on components/wildberries/actions/common/common.ts
> +  stickersRequestType: [
```suggestion
  STICKERS_REQEUEST_TYPE: [
```

2022-08-29 14:21 UTC, lcaresia commented on components/wildberries/actions/common/common.ts
> +  orderStatus: [
```suggestion
  ORDER_STATUSES: [
```

2022-08-29 14:21 UTC, lcaresia commented on components/wildberries/actions/list-order-stickers/list-order-stickers.ts
> +      description: "Sticker type, default: code128.",
```suggestion
      description: "Sticker type, default: `code128`.",
```

2022-08-29 14:21 UTC, lcaresia commented on components/wildberries/actions/list-order-stickers/list-order-stickers.ts
> +  description: "List order stickers. [See docs](https://suppliers-api.wildberries.ru/swagger/index.html#/Marketplace/post_api_v2_orders_stickers)",
```suggestion
  description: "List order stickers. [See docs here](https://suppliers-api.wildberries.ru/swagger/index.html#/Marketplace/post_api_v2_orders_stickers)",
```

2022-08-29 14:21 UTC, lcaresia commented on components/wildberries/actions/list-order-stickers/list-order-stickers.ts
> +      description: "Set true for use the PDF API [See docs](https://suppliers-api.wildberries.ru/swagger/index.html#/Marketplace/post_api_v2_orders_stickers_pdf).",
```suggestion
      description: "Set true for use the PDF API [See docs here](https://suppliers-api.wildberries.ru/swagger/index.html#/Marketplace/post_api_v2_orders_stickers_pdf).",
```

2022-08-29 14:21 UTC, lcaresia commented on components/wildberries/actions/list-orders/list-orders.ts
> +  description: "Returns a list of orders. [See docs](https://suppliers-api.wildberries.ru/swagger/index.html#/Marketplace/get_api_v2_orders)",
```suggestion
  description: "Returns a list of orders. [See docs here](https://suppliers-api.wildberries.ru/swagger/index.html#/Marketplace/get_api_v2_orders)",
```

2022-08-29 14:21 UTC, lcaresia commented on components/wildberries/actions/update-order-status/update-order-status.ts
> +  description: "Update a order status. [See docs](https://suppliers-api.wildberries.ru/swagger/index.html#/Marketplace/put_api_v2_orders)",
```suggestion
  description: "Update a order status. [See docs here](https://suppliers-api.wildberries.ru/swagger/index.html#/Marketplace/put_api_v2_orders)",
```

2022-08-29 14:21 UTC, lcaresia commented on components/wildberries/actions/update-order-status/update-order-status.ts
> +      description: "Array required only for pharmaceutical products when they are transferred to status `Customer received the goods`.\n\n**Example:** `[{ code: string, numerator: integer, denominato
```suggestion
      description: "Array required only for pharmaceutical products when they are transferred to status `Customer received the goods`.\n\n**Example:** `[{ code: string, numerator: integer, denominator: integer, sid: integer }]`\n\n[See docs here](https://suppliers-api.wildberries.ru/swagger/index.html#/Marketplace/put_api_v2_orders)",
```

2022-08-31 01:55 UTC, alysonturing commented
/approve

2022-08-31 11:49 UTC, lcaresia approved these changes
LGTM!

2022-09-07 16:37 UTC, merged