Agile CRM - new sources & actions
PipedreamHQ/pipedream pull request #4134
Opened 2022-08-31 15:40 UTC by michelle0927

Resolves #3544 

**Sources**
- New Contact
- New Ticket
- New Task

**Actions**
- Create Ticket
- Create Task
- Create Contact
- Update Contact

2022-08-31 15:40 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-08-31 20:19 UTC, lcaresia requested changes
Thanks for your contribution.

I requested just some fixes!

2022-08-31 20:19 UTC, lcaresia commented on components/agile_crm/agile_crm.app.mjs
> +        password: this.$auth.api_key,
Move this to a getter method;

```suggestion
        username: this._username(), // this.$auth.username,
        password:  this.apiKey(), // this.$auth.api_key,
```

2022-08-31 20:19 UTC, lcaresia commented on components/agile_crm/sources/common/base.mjs
> +        intervalSeconds: 60 * 15,
```suggestion
        intervalSeconds: 60 * 15, // 15 minutes
```

2022-09-01 20:43 UTC, lcaresia submitted a review, later dismissed
LGTM!

2022-09-02 18:40 UTC, DilanAthukorala commented
Hi @michelle0927,

For "Update Contact", is "First Name" param mandatory? If not please make it an optional parameter
![image](https://user-images.githubusercontent.com/102980146/188211767-f28f9d94-4741-40bd-bfa3-7b2b3bef4a77.png)

2022-09-04 16:53 UTC, DilanAthukorala commented
Verification completed and ready for release.

2022-09-04 16:54 UTC, michelle0927 commented
/approve

2022-09-04 17:47 UTC, lcaresia approved these changes

2022-09-04 17:49 UTC, merged