[SOURCE] Eversign
PipedreamHQ/pipedream pull request #4189
Opened 2022-09-08 13:23 UTC by vellames

Closes #3862 

Since the free account is really limited. I was able to create a source where user can handle any Eversign event

2022-09-08 16:53 UTC, jcortes reviewed
Hi @vellames I think there are some actions that you still can implement. What about these ones?
https://eversign.com/api/documentation/methods#use-template
https://eversign.com/api/documentation/methods#download-original-pdf

2022-09-12 11:25 UTC, vellames commented
> Hi @vellames I think there are some actions that you still can implement. What about these ones? https://eversign.com/api/documentation/methods#use-template https://eversign.com/api/documentation/methods#download-original-pdf

Humm, I can because I need a paid account to set up a template for example, and the API calls are very limited for a free account. I was able to do the sources because the webhook notification does not count as an API call for the App. Also, I have a very limited number of documents to create in the free account. What do you think about approving this one so we can open another one asking for a paid version so that I can implement the other actions?

2022-09-12 17:59 UTC, michelle0927 requested changes
It's not ideal, but I see why you set it up this way. Just a couple things, and then good to go!

2022-09-12 18:01 UTC, michelle0927 requested changes
It's not ideal, but I see why you set it up this way. Just a couple things, and then good to go!

2022-09-12 18:01 UTC, michelle0927 commented on components/eversign/package.json
> +  "version": "0.0.1",
I think the package.json should list crypto as a dependency.

2022-09-12 18:01 UTC, michelle0927 commented on components/eversign/sources/new-event/new-event.mjs
> +  description: "Emit new event when a new event occurs in EverSign",
I think we should include some instructions here for the user. Something like:
```suggestion
  description: "Emit new event when a new event occurs in EverSign. To begin receiving events, navigate to your Developer dashboard, and enter the URL of this source/workflow as the Webhook URL. https://eversign.com/api/documentation/webhooks",
```

2022-09-12 20:03 UTC, michelle0927 approved these changes
Looks good!

2022-09-14 00:52 UTC, merged