[ACTIONS/SOURCES] Zoho desk new sources and actions
PipedreamHQ/pipedream pull request #4223
Opened 2022-09-13 19:08 UTC by jcortes

# Actions
- [ ] Create Account | Creates an account in your help desk portal. [See the docs here](https://desk.zoho.com/DeskAPIDocument#Accounts#Accounts_CreateAccount)
- [ ] Create Contact | Creates a contact in your help desk portal. [See the docs here](https://desk.zoho.com/DeskAPIDocument#Contacts#Contacts_CreateContact)
- [ ] Update Contact | Updates details of an existing contact. [See the docs here](https://desk.zoho.com/DeskAPIDocument#Contacts#Contacts_Updateacontact)
- [ ] Find Contact | Searches for contacts in your help desk portal. [See the docs here](https://desk.zoho.com/DeskAPIDocument#Search#Search_SearchContacts)
- [ ] Find or Create Contact | Finds or create a contact. [See the docs here](https://desk.zoho.com/DeskAPIDocument#Contacts#Contacts_CreateContact)
- [ ] Create Ticket | Creates a ticket in your helpdesk. [See the docs here](https://desk.zoho.com/DeskAPIDocument#Tickets#Tickets_Createaticket)
- [ ] Add Ticket Comment | Adds a comment to a ticket. [See the docs here](https://desk.zoho.com/DeskAPIDocument#TicketsComments#TicketsComments_Createticketcomment)
- [ ] Add Ticket Attachment | Attaches a file to a ticket. [See the docs here](https://desk.zoho.com/DeskAPIDocument#TicketAttachments)
- [ ] Update Ticket | Updates an existing ticket. [See the docs here](https://desk.zoho.com/DeskAPIDocument#Tickets#Tickets_Updateaticket)
- [ ] Search Ticket | Searches for tickets in your help desk. [See the docs here](https://desk.zoho.com/DeskAPIDocument#Search_TicketsSearchAPI)
- [ ] Send E-Mail Reply | Sends an email reply. [See the docs here](https://desk.zoho.com/DeskAPIDocument#Threads#Threads_SendEmailReply)

# Sources
- [ ] New Account | Emit new event when a new account is created. [See the docs here](https://desk.zoho.com/DeskAPIDocument#Accounts#Accounts_Listaccounts)
- [ ] New Agent | Emit new event when a new agent is created. [See the docs here](https://desk.zoho.com/DeskAPIDocument#Agents#Agents_Listagents)
- [ ] New Ticket Attachment | Emit new event when a new ticket attachment is created. [See the docs here](https://desk.zoho.com/DeskAPIDocument#TicketAttachments#TicketAttachments_Listticketattachments)
- [ ] New Ticket Comment | Emit new event when a new ticket comment is created. [See the docs here](https://desk.zoho.com/DeskAPIDocument#TicketsComments#TicketsComments_Listallticketcomments)
- [ ] New Contact | Emit new event when a new contact is created. [See the docs here](https://desk.zoho.com/DeskAPIDocument#Contacts#Contacts_Listcontacts)
- [ ] New Ticket | Emit new event when a new ticket is created. [See the docs here](https://desk.zoho.com/DeskAPIDocument#Tickets#Tickets_Listalltickets)
- [ ] Updated Ticket | Emit new event when a ticket is updated. [See the docs here](https://desk.zoho.com/DeskAPIDocument#Tickets#Tickets_Listalltickets)

2022-09-13 19:09 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-09-16 18:51 UTC, michelle0927 requested changes

2022-09-16 18:51 UTC, michelle0927 commented on components/zoho_desk/sources/new-agent/new-agent.mjs
> +      return Date.now() > lastCreatedAt;
Won't this always be true?

2022-09-16 18:51 UTC, michelle0927 commented on components/zoho_desk/sources/updated-ticket/updated-ticket.mjs
> +        id: ts,
Maybe include the id just in case there are 2 resources with the same modifiedTime?
```suggestion
        id: `${resource.id}${ts}`,
```

2022-09-16 18:51 UTC, michelle0927 commented on components/zoho_desk/zoho_desk.app.mjs
> +      }
Can `from` be null here? Won't it be set to 1 if it is null?

2022-09-16 18:51 UTC, michelle0927 commented on components/zoho_desk/zoho_desk.app.mjs
> +      };
I think `index` here is supposed to be `from`. I don't see `from` being set anywhere else.
```suggestion
      return {
        options,
        context: {
          from: currentLen
            ? currentLen + from
            : null,
        },
      };
```

2022-09-16 20:31 UTC, michelle0927 requested changes

2022-09-16 20:31 UTC, michelle0927 commented on components/zoho_desk/zoho_desk.app.mjs
> +      const options = resources.map(resourceMapper);
The prop pagination works, but it gets errors when it reaches the bottom of the list. Adding `?` fixed it for me.

<img width="892" alt="Screen Shot 2022-09-16 at 4 27 27 PM" src="https://user-images.githubusercontent.com/10889229/190727599-736a3277-53d4-46fb-9d9e-8fd9fed18d94.png">

<img width="888" alt="Screen Shot 2022-09-16 at 4 25 44 PM" src="https://user-images.githubusercontent.com/10889229/190727657-65eb5089-66ba-4b17-996c-8441b96b33e0.png">


```suggestion
      const currentLen = resources?.length;
      const options = resources?.map(resourceMapper);
```

2022-09-16 23:05 UTC, michelle0927 submitted a review, later dismissed
Approved!

2022-09-19 08:19 UTC, vunguyenhung commented
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Zoho_Desk_3850_1517.pdf](https://github.com/PipedreamHQ/pipedream/files/9597186/Zoho_Desk_3850_1517.pdf)

2022-09-20 12:15 UTC, andrewjschuang reviewed
LGTM, just some minors

2022-09-20 12:25 UTC, andrewjschuang submitted a review, later dismissed

2022-09-20 16:01 UTC, vunguyenhung reviewed
Hello @jcortes, I suggest 2 code change to fix the send reply email that doesn't use the content type prop

2022-09-20 16:01 UTC, vunguyenhung commented on components/zoho_desk/actions/send-email-reply/send-email-reply.mjs
> +      content,
```suggestion
      content,
      contentType,
```

2022-09-20 16:01 UTC, vunguyenhung commented on components/zoho_desk/actions/send-email-reply/send-email-reply.mjs
> +        content,
```suggestion
        content,
        contentType,
```

2022-09-20 16:13 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Zoho_Desk_3850_2312.pdf](https://github.com/PipedreamHQ/pipedream/files/9609473/Zoho_Desk_3850_2312.pdf)

2022-09-20 18:34 UTC, andrewjschuang approved these changes

2022-09-20 18:36 UTC, merged