New Actions and Sources Teamwork
PipedreamHQ/pipedream pull request #4285
Opened 2022-09-20 12:41 UTC by vellames

Closes #3803

2022-09-20 12:42 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-09-20 19:19 UTC, andrewjschuang requested changes
Hey @vellames, just a few comments

2022-09-20 19:19 UTC, andrewjschuang commented on components/teamwork/common/common-sources.mjs
> +export default {
Since this is for sources only, can it be inside `sources/common/`?

2022-09-20 19:19 UTC, andrewjschuang commented on components/teamwork/sources/task-updated/task-updated.mjs
> +      id: event.body["Task.ID"],
Since it's an `updated` trigger, it is necessary to add the timestamp to the id or remove the `dedupe: unique`

2022-09-21 13:35 UTC, andrewjschuang reviewed
Thanks, LGTM!

2022-09-21 15:30 UTC, DilanAthukorala commented
@vellames Observing following issues:

1. for all actions following error is thrown when trying to list projects
![image](https://user-images.githubusercontent.com/102980146/191545013-7cd69d02-e281-4a79-b0f1-b222b3379dab.png)

2. for all sources following error is thrown when creating the source 
![image](https://user-images.githubusercontent.com/102980146/191546132-5df4eb8a-1276-4906-84b8-9e6fa11a9b3b.png)

2022-09-21 15:44 UTC, vellames commented
Humm, for some reason, looks like your domain does not have the `/`. I will add an additional validation for this

2022-09-21 16:21 UTC, DilanAthukorala commented
@vellames list_project_tasks action is not filtering the tasks correctly by `Complete After Date`, `Complete Before Date` and `Creators Id`

2022-09-21 19:11 UTC, vellames commented
@DilanAthukorala Could you check again, please?

2022-09-21 19:13 UTC, vellames commented
I have to abandon this PR. Will create another one

2022-09-21 19:18 UTC, closed without merging