3838 woodpeckerco
PipedreamHQ/pipedream pull request #4286
Opened 2022-09-20 12:55 UTC by luancazarine

Triggers
  - Email Sent
  - Email Opened
  - Follow-Up After Autoreply
  - Link Clicked
  - Prospect Autoreplied
  - Prospect Blacklisted
  - Prospect Bounced
  - Prospect Interested
  - Prospect Invalid
  - Prospect Maybe Later
  - Prospect Not Interested
  - Prospect Replied

Actions
  - Create/Update Prospect in Campaign
  - Create/Update Prospect
  - Stop Follow-Ups
  - Find Prospect's Email

2022-09-20 12:56 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-09-20 19:45 UTC, andrewjschuang requested changes
Hey @luancazarine, I've added just a few comments.

2022-09-20 19:45 UTC, andrewjschuang commented on components/woodpecker_co/utils.mjs
> +export const orderOptions = [
Can you put this file inside a `common/` folder so it's not mistaken as a component?

2022-09-20 19:45 UTC, andrewjschuang commented on components/woodpecker_co/package.json
> +  "version": "0.0.2",
```suggestion
  "version": "0.0.1",
```

2022-09-20 19:45 UTC, andrewjschuang commented on components/woodpecker_co/package.json
> +  "main": "dist/app/woodpecker_co.app.mjs",
```suggestion
  "main": "woodpecker_co.app.mjs",
```

2022-09-20 19:45 UTC, andrewjschuang commented on components/woodpecker_co/package.json
> +  ],
```suggestion
```

2022-09-20 19:45 UTC, andrewjschuang commented on components/woodpecker_co/actions/stop-follow-ups/stop-follow-ups.mjs
> +  description: "This action searches a specific prospect. [See the docs here](https://woodpecker.co/help/api-managing-prospects/)",
Update description

2022-09-20 19:45 UTC, andrewjschuang commented on components/woodpecker_co/sources/prospect-blacklisted/prospect-blacklisted.mjs
> +  name: "New Prospect Autoreplied (Instant)",
Update name

2022-09-20 19:45 UTC, andrewjschuang commented on components/woodpecker_co/woodpecker_co.app.mjs
> +      return await this.sdk().prospects()
```suggestion
      return this.sdk().prospects()
```

2022-09-20 19:45 UTC, andrewjschuang commented on components/woodpecker_co/woodpecker_co.app.mjs
> +      return await this.sdk().campaigns()
```suggestion
      return this.sdk().campaigns()
```

2022-09-20 19:45 UTC, andrewjschuang commented on components/woodpecker_co/woodpecker_co.app.mjs
> +        .find();
Is this right?

2022-09-20 19:45 UTC, andrewjschuang commented on components/woodpecker_co/woodpecker_co.app.mjs
> +      return await this.sdk().webhooks()
```suggestion
      return this.sdk().webhooks()
```

2022-09-20 19:45 UTC, andrewjschuang commented on components/woodpecker_co/woodpecker_co.app.mjs
> +      return await this.sdk().webhooks()
```suggestion
      return this.sdk().webhooks()
```

2022-09-20 19:45 UTC, andrewjschuang commented on components/woodpecker_co/woodpecker_co.app.mjs
> +    id: {
Is there a way to list the `ids` ?

2022-09-20 19:45 UTC, andrewjschuang commented on components/woodpecker_co/woodpecker_co.app.mjs
> +      } else {
`else` is not needed here

2022-09-20 19:45 UTC, andrewjschuang commented on components/woodpecker_co/woodpecker_co.app.mjs
> +      params, campaignId = null,
Isn't the default `undefined` value for `campaignId` sufficient?

2022-09-21 13:41 UTC, andrewjschuang reviewed
Thanks, LGTM!

2022-09-22 14:39 UTC, vunguyenhung commented
Hello @luancazarine, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Woodpecker.co_3838_2138.pdf](https://github.com/PipedreamHQ/pipedream/files/9626836/Woodpecker.co_3838_2138.pdf)

2022-09-22 19:01 UTC, andrewjschuang reviewed
Just some optional (but recommended) comments!

2022-09-23 03:39 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Woodpecker.co_3838_1039.pdf](https://github.com/PipedreamHQ/pipedream/files/9630606/Woodpecker.co_3838_1039.pdf)

2022-09-23 14:28 UTC, luancazarine commented on components/woodpecker_co/woodpecker_co.app.mjs
> +          : [];
![image](https://user-images.githubusercontent.com/5638699/191983943-e18f3fcf-9e7c-4273-bdf4-89740ca0dd28.png)
I tried but it didn't work

2022-09-23 14:44 UTC, andrewjschuang approved these changes

2022-09-23 14:45 UTC, andrewjschuang commented on components/woodpecker_co/woodpecker_co.app.mjs
> +          : [];
Weird, it will depend on the returned object from the sdk. But np in leaving it like that.

2022-09-23 14:48 UTC, merged