4047 trigger new youtube subscription
PipedreamHQ/pipedream pull request #4293
Opened 2022-09-20 19:54 UTC by luancazarine

Source:
  - New Subscription

2022-09-20 19:54 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-09-21 14:20 UTC, andrewjschuang requested changes
Hi @luancazarine, I've left a few comments.
Can we also emit historical events?

2022-09-21 14:20 UTC, andrewjschuang commented on components/youtube_data_api/sources/new-subscription/new-subscription.mjs
> +    this._setLastExecutionDate(new Date().getTime());
I think it's better to use the last `item.snippet.publishedAt` date to avoid missing events mistakenly (although improbable).

2022-09-21 14:20 UTC, andrewjschuang commented on components/youtube_data_api/sources/new-subscription/new-subscription.mjs
> +      this._setLastExecutionDate(new Date().getTime());
You can set a default value in `_getLastExecutionDate()` if that's why this is here

2022-09-21 14:20 UTC, andrewjschuang commented on components/youtube_data_api/sources/new-subscription/new-subscription.mjs
> +      let nextPageToken = null;
```suggestion
      let nextPageToken;
```

2022-09-21 14:20 UTC, andrewjschuang commented on components/youtube_data_api/package.json
> +  "version": "0.4.4",
```suggestion
  "version": "0.4.0",
```

2022-09-22 18:50 UTC, andrewjschuang approved these changes
Thanks, LGTM!

2022-09-23 12:07 UTC, merged