[ACTION] Update Threads components to use newest API #4350
PipedreamHQ/pipedream pull request #4367
Opened 2022-09-28 19:34 UTC by luancazarine

Refactored:
  - App
  - Action Post Thread
  - Action Delete Thread

Created:
  - Action Post Chat Message

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4367"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-09-28 19:35 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-09-29 23:38 UTC, vellames requested changes
Hey! Looks like you forgot a console.log here. Not sure, but I am requesting changes just in case.

2022-09-29 23:38 UTC, vellames commented on components/threads/actions/post-chat-message/post-chat-message.mjs
> +    console.log("chatMessage: ", chatMessage);
Do you want this here?

2022-09-30 15:56 UTC, vellames approved these changes
lgtm

2022-10-03 14:27 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Threads_4350.pdf](https://github.com/PipedreamHQ/pipedream/files/9698319/Threads_4350.pdf)

2022-10-03 19:27 UTC, luancazarine commented
/approve

2022-10-03 19:29 UTC, feyzullah approved these changes

2022-10-03 20:31 UTC, merged

2022-10-04 21:20 UTC, dannyroosevelt commented
I'm running into problems getting any of these components to work.

**Post Thread**
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/193931288-1f920bce-b70f-435b-945d-565abe262d02.png)
And both prop descriptions could be improved. I can provide a recommendation.

**Post Chat Message**
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/193931613-89e04bae-316c-421c-a3bb-078a8244631f.png)
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/193931676-9267c8f6-2d23-46ce-aeef-effc61d152ce.png)
Both prop descriptions could be improved.

**Delete Thread**
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/193931776-7cbc974f-19a0-402c-b600-867ef653f925.png)
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/193931841-9a0c91d8-60d1-4850-984c-aec900eebc4b.png)
The prop description is outdated I believe (it references threads.com, but it should reference trythreads.com)

2022-10-05 00:48 UTC, vunguyenhung commented
Sorry @dannyroosevelt, I have created a new PR to fix the Post Thread action, as well as improve the description to `trythreads.com` https://github.com/PipedreamHQ/pipedream/pull/4413

2022-10-05 16:36 UTC, dannyroosevelt commented on components/threads/threads.app.mjs
> +        "This is ID of the chat you want to post to. An easy way to find a chatID for a chat is to navigate to that chat on the Threads website. The URL will be trythreads.com/messages/<your_chat_id>
>"To find the chat ID, open the Threads chat in your browser and copy the ID: `https://trythreads.com/messages/{your_chat_id}`"

2022-10-05 16:36 UTC, dannyroosevelt commented on components/threads/actions/post-thread/post-thread.mjs
>    description: "Post a new thread to a specific forum",
>"Post a new thread to a specific channel",

2022-10-05 16:37 UTC, dannyroosevelt commented on components/threads/actions/post-chat-message/post-chat-message.mjs
> +        "This is the body of the message. To format the body, you can send markdown.",
Compose your chat message here, and include markdown if you'd like. See [here](https://github.com/ThreadsHQ/api-documentation#2-1) for examples.

2022-10-05 16:38 UTC, dannyroosevelt reviewed
I added comments on suggested changes to the component and prop descriptions