[Splitwise] New Components
PipedreamHQ/pipedream pull request #4501
Opened 2022-10-13 17:37 UTC by andrewjschuang

**Actions:**

- Create Expense
- Get Expense Information
- Get Expenses

**Sources:**

- Expense Created
- Group Created
- Recently Occurred Activity

Resolves #4149.

2022-10-13 17:38 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-10-13 18:41 UTC, lcaresia requested changes
Thanks for your contribution!

Is needed just one fix.

2022-10-13 18:41 UTC, lcaresia commented on components/splitwise/splitwise.app.mjs
> +          Authorization: `Bearer ${this.$auth.oauth_access_token}`,
Move this to a getter method

```suggestion
          Authorization: `Bearer ${this._accessToken()}`,
```

2022-10-13 19:08 UTC, lcaresia submitted a review, later dismissed
LGTM!

2022-10-14 17:52 UTC, andrewjschuang commented
/approve

2022-10-14 18:04 UTC, lcaresia approved these changes

2022-10-14 18:05 UTC, merged