#3606 - Detrack new action
PipedreamHQ/pipedream pull request #4503
Opened 2022-10-14 03:32 UTC by GTFalcao

# New Action
- **Create Job**

Closes #3606

2022-10-14 03:32 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-10-14 13:35 UTC, lcaresia requested changes
Hello, just is needed one fix!

2022-10-14 13:35 UTC, lcaresia commented on components/detrack/actions/create-job/create-job.ts
> +    $.export("$summary", `Successfully created job ${data.id}`);
```suggestion
    $.export("$summary", `Successfully created job with ID ${data.id}`);
```

2022-10-14 13:35 UTC, lcaresia commented on components/detrack/app/detrack.app.ts
> +          "X-API-KEY": this.$auth.api_key,
Move this to a getter method

```suggestion
          "X-API-KEY": this._apiKey(),
```

2022-10-14 15:57 UTC, GTFalcao commented on components/detrack/app/detrack.app.ts
> +          "X-API-KEY": this.$auth.api_key,
Applied this

2022-10-14 15:58 UTC, GTFalcao commented on components/detrack/actions/create-job/create-job.ts
> +    $.export("$summary", `Successfully created job ${data.id}`);
Applied this

2022-10-14 19:14 UTC, lcaresia approved these changes
LGTM!

2022-10-16 18:45 UTC, DilanAthukorala commented
Verification completed, ready for release.

2022-10-17 16:03 UTC, merged