feat: Create a generic action to run any API based on the document
PipedreamHQ/pipedream pull request #4521
Opened 2022-10-17 11:02 UTC by trendoscope-algorithms

This is generic method which kind of caters for everything. I think this is better way of developing instead of building each and every action for all endpoints. This will also take care of deprecations.

Tests done on following things:

1. GET Request without any query parameters
2. GET Request with query parameters
3. POST request
4. DELETE request

At present, I did not find any PUT request. But, kept the option open in case if there is any addition later on. Can look to build some enhancements - but for now this will do.

2022-10-17 11:02 UTC, dylburger commented
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

2022-10-17 11:02 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-10-17 11:10 UTC, trendoscope-algorithms commented
Testing results

**GET Without parameters.**

![image](https://user-images.githubusercontent.com/107564590/196162321-34cc3916-ca90-43d3-aa22-6300f1167936.png)

**GET With parameters.**
![image](https://user-images.githubusercontent.com/107564590/196162467-354d51da-f813-474a-8bf3-0c0de34493d6.png)

**POST Request**
![image](https://user-images.githubusercontent.com/107564590/196162518-286a076e-557c-4b1e-a310-13ba639250a2.png)

**DELETE Request**
![image](https://user-images.githubusercontent.com/107564590/196162745-e5aac0c7-7f2f-4345-adcc-25640a71674d.png)

2022-10-18 17:24 UTC, jcortes reviewed
Hi @trendoscope-algorithms I've just added a suggestion and one minor request change. But in general looks good to me. Almost done.

Also please rename the file `kucoin_futures.mjs` to `kucoin_futures.app.mjs` thanks!

2022-10-18 17:24 UTC, jcortes commented on components/kucoin_futures/actions/generic-api-call/generic-api-call.mjs
> +    );
Just as a suggestion I think you can pre validate the `api_path` like 
```suggestion
    if (!this.api_path.startsWith("/")) {
      throw new Error("Api Path property should always start with `/` as a path like string");
    }
    const returnValue = await this.kucoin_futures.makeRequest(
      this.http_method, this.api_path, this.params,
    );
```

2022-10-18 17:24 UTC, jcortes commented on components/kucoin_futures/package.json
>    "main": "dist/app/kucoin_futures.app.mjs",
I think this line should now be just
```suggestion
  "main": "kucoin_futures.app.mjs",
```
since you are working with just plain javascript

2022-10-20 01:45 UTC, trendoscope-algorithms commented
Hi @jcortes - thanks, will make the updates soon and ping you back. Sorry been busy and couldn't check from last few days.

2022-10-25 00:51 UTC, alysonturing requested changes
Thanks for your PR, I just added some minors, and then you'll be good to go!

2022-10-25 00:51 UTC, alysonturing commented on components/kucoin_futures/actions/generic-api-call/generic-api-call.mjs
> +import kucoin_futures from "../../kucoin_futures.app.mjs";
please use cammelCase, this import should look like: 
`import kucoinFuturesApp from "../../kucoin_futures.app.mjs";`

2022-10-25 00:51 UTC, alysonturing commented on components/kucoin_futures/actions/generic-api-call/generic-api-call.mjs
> +        "[reference](https://docs.kucoin.com/futures/#general)",
We normally use the following pattern on description: 
`Make any API call for Kucoin Futures as per the documentation. See docs [here](https://docs.kucoin.com/futures/#general)`

2022-10-25 00:51 UTC, alysonturing commented on components/kucoin_futures/actions/generic-api-call/generic-api-call.mjs
> +    kucoin_futures,
please rename to cammelCase

2022-10-25 00:51 UTC, alysonturing commented on components/kucoin_futures/actions/generic-api-call/generic-api-call.mjs
> +    http_method: {
please rename to cammelCase

2022-10-25 00:51 UTC, alysonturing commented on components/kucoin_futures/actions/generic-api-call/generic-api-call.mjs
> +    api_path: {
please rename to cammelCase

2022-10-25 00:51 UTC, alysonturing commented on components/kucoin_futures/actions/generic-api-call/generic-api-call.mjs
> +      optional: false,
the default optional is false, in this case you can omit it.

2022-10-25 00:51 UTC, alysonturing commented on components/kucoin_futures/actions/generic-api-call/generic-api-call.mjs
> +      optional: false,
the default optional is false, in this case you can omit it.

2022-10-25 00:51 UTC, alysonturing commented on components/kucoin_futures/actions/generic-api-call/generic-api-call.mjs
> +      throw new Error("Api Path property should always start with `/` as a path like string");
Please throw a ConfigurationError on this case

[see docs here:](https://pipedream.com/docs/code/nodejs/#configuration-error) 
`Throwing a ConfigurationError in a Node.js step will display the error message in a dedicated area.
This is useful for providing feedback during validation of props. In the example below, a required Header value is missing from the Google Sheets action:`

2022-10-25 00:51 UTC, alysonturing commented on components/kucoin_futures/kucoin_futures.app.mjs
> +
please remove this empty line

2022-10-25 13:18 UTC, alysonturing approved these changes
LGTM!

2022-10-25 16:03 UTC, vunguyenhung commented on components/kucoin_futures/actions/generic-api-call/generic-api-call.mjs
> +      type: "object",
```suggestion
      type: "object",
      optional: true
```

2022-10-25 16:20 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Kucoin_4521.pdf](https://github.com/PipedreamHQ/pipedream/files/9862159/Kucoin_4521.pdf)

2022-10-25 16:20 UTC, vunguyenhung commented
/approve

2022-10-25 16:24 UTC, alysonturing approved these changes
Approved!

2022-10-25 16:29 UTC, vunguyenhung commented
Thanks @alysonturing, I will merge this on behave of @trendoscope-algorithms

2022-10-25 16:29 UTC, merged