[ACTION] expofp #4596
PipedreamHQ/pipedream pull request #4622
Opened 2022-10-31 15:15 UTC by lcaresia

2022-10-31 21:09 UTC, GTFalcao requested changes
Hi @lcaresia , thanks for your contribution!

I've left some very minor suggestions and a few component versions that need to be reset.

2022-10-31 22:56 UTC, GTFalcao reviewed
LGTM! 👏 

There's just a minor typo in a summary, so I'm moving this to Ready for QA.

2022-10-31 22:56 UTC, GTFalcao commented on components/expofp/actions/update-booth/update-booth.mjs
> +    $.export("$summary", `Successfully updasted booth with ID ${this.boothId}`);
Typo fix
```suggestion
    $.export("$summary", `Successfully updated booth with ID ${this.boothId}`);
```

2022-11-01 10:33 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[ExpoFx.pdf](https://github.com/PipedreamHQ/pipedream/files/9909020/ExpoFx.pdf)

2022-11-01 12:27 UTC, lcaresia commented
/approve

2022-11-01 22:34 UTC, lcaresia commented
/approve

2022-11-01 22:35 UTC, GTFalcao approved these changes

2022-11-01 22:40 UTC, merged