Actions and Sources - Siteleaf
PipedreamHQ/pipedream pull request #4668
Opened 2022-11-04 13:39 UTC by vellames

Closes #3783

2022-11-04 13:40 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-11-04 20:28 UTC, GTFalcao submitted a review, later dismissed
Hi @vellames , thanks for your contribution!

I commented on a few things that could be improved for reusability and maintainability, following Pipedream's DRY standards.

2022-11-04 20:28 UTC, GTFalcao commented on components/siteleaf/sources/new-collection/new-collection.mjs
> +    async fetchEvents() {
The `fetchEvents()` method is nearly identical across the sources. I think we can reuse most of this code into a common method in the `base` file for the sources.

An individual `getData` or similar method to fetch `listCollections`, `listPages`, etc. and `getSummary` method would take care of the parts that differ between the sources.

2022-11-04 23:48 UTC, vellames commented on components/siteleaf/siteleaf.app.mjs
> +      return axios(ctx, this._getAxiosParams({
I don't get it exactly. Are you suggesting wrapping `axios` in a function and then calling that function? Like a function that only calls another function?. Could you please provide an example?

2022-11-07 20:01 UTC, GTFalcao commented on components/siteleaf/siteleaf.app.mjs
> +      return axios(ctx, this._getAxiosParams({
I mean the axios lib should only be used directly in a single place. I see you've done this in a new `_makeHttpRequest` which is exactly what I was thinking, so, looks good!

2022-11-07 20:16 UTC, luancazarine commented on components/siteleaf/actions/create-document/create-document.mjs
> +  version: "0.1.1",
isn't this the first version?
```suggestion
  version: "0.0.1",
```

2022-11-07 20:20 UTC, luancazarine commented on components/siteleaf/sources/new-collection/new-collection.mjs
> +  description: "Emit new event when a new collection is created",
Could you put the docs link?

2022-11-07 20:21 UTC, luancazarine commented on components/siteleaf/sources/new-document/new-document.mjs
> +  description: "Emit new event when a new document is created",
Could you put the docs link?

2022-11-07 20:21 UTC, luancazarine commented on components/siteleaf/sources/new-page/new-page.mjs
> +  description: "Emit new event when a new page is created",
Could you put the docs link?

2022-11-07 20:21 UTC, luancazarine commented on components/siteleaf/sources/new-site/new-site.mjs
> +  description: "Emit new event when a new site is created",
Could you put the docs link?

2022-11-07 20:24 UTC, luancazarine requested changes
Hi @vellames I've just added a few minor request changes.

2022-11-08 12:19 UTC, luancazarine approved these changes

2022-11-08 13:30 UTC, merged