[ACTION] Audit on polling sources #4691
PipedreamHQ/pipedream pull request #4692
Opened 2022-11-08 12:26 UTC by lcaresia

2022-11-08 12:27 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-11-08 17:08 UTC, lcaresia commented
@dannyroosevelt I remember like 50+, but I made default `timer: 15 * 60, // 15 minutes` to all sources. And because of this the script are getting some old eslint errors, and I'm fixing this now.

2022-11-09 13:47 UTC, luancazarine requested changes
Hi @lcaresia  I've just added one minor request change.

2022-11-09 13:54 UTC, lcaresia commented on components/swapi/actions/get-film/get-film.js
> +  description: "Get a filme",
Yes, I just put a simple description to Eslint stop give me error

2022-11-09 14:03 UTC, luancazarine submitted a review, later dismissed

2022-11-11 17:14 UTC, luancazarine submitted a review, later dismissed

2026-08-07 23:53 UTC, GTFalcao commented
Closing: too old, superseded

2026-08-07 23:53 UTC, closed without merging