Direct7 SMS Integration request
PipedreamHQ/pipedream pull request #4765
Opened 2022-11-17 08:08 UTC by d7networks

Included action to send SMS using  Direct7 SMS API.

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4765"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-11-17 08:08 UTC, dylburger commented
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

2022-11-17 08:09 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-11-17 16:26 UTC, jcortes reviewed
Hi @d7networks first of all thanks for this great contribution you made. And I've just added a suggestion on how you can refactor the code for better maintenance.

1. You can create the file `d7_networks/common/constants.mjs` with folowing content:
```javascript
const BASE_URL = "https://api.d7networks.com";
const API_VERSION = "v1";

export default {
  BASE_URL,
  API_VERSION,
};

```

2. Then you can create the file `d7_networks/d7_networks.app.mjs` with following content:
```javascript
import { axios } from "@pipedream/platform";
import constants from "./common/constants.mjs";

export default {
  type: "app",
  app: "d7_networks",
  propDefinitions: {},
  methods: {
    getUrl(path) {
      return `${constants.BASE_URL}${path}`;
    },
    getHeaders(headers) {
      return {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.$auth.oauth_access_token}`,
        ...headers,
      };
    },
    async makeRequest({
      step = this, path, headers, ...args
    } = {}) {

      const config = {
        headers: this.getHeaders(headers),
        url: this.getUrl(path),
        ...args,
      };

      try {
        return await axios(step, config);
      } catch (error) {
        console.log("Error", error);
        throw error;
      }
    },
  },
};

```
What we are doing here is basically creating our own SDK using Pipedream libs capabilities and reuse code with DRY in mind.
So now you can delete the file `d7_networks/app/d7_networks.app.ts` along with `app` dir.

3. Now you can create your component with the following content:
```javascript
import app from "../d7_networks.app.mjs";
import constants from "../common/constants.mjs";

export default {
  name: "Send SMS",
  version: "0.0.1",
  key: "d7_networks-send-sms",
  description: "Sending sms via D7 networks! [See the docs](https://d7networks.com/docs/Messages/Send_Message/)",
  type: "action",
  props: {
    app,
    originator: {
      type: "string",
      label: "Originator",
      description: "The Sender/Header of a message. Brand name with a maximum character limit of 11 or your mobile number with country code. E.g. `Pipedream`",
    },
    recipients: {
      type: "string[]",
      label: "Recipients",
      description: "Mobile Numbers to send SMS.",
    },
    content: {
      type: "string",
      label: "Content",
      description: "Content of the message.",
    },
    channel: {
      type: "string",
      label: "Channel",
      description: "Messaging Channel (`SMS`, `WhatsApp`, `Viber`, `Telegram`, etc)",
      options: [
        "SMS",
        "WhatsApp",
        "Viber",
        "Telegram",
      ],
    },
    reportUrl: {
      type: "string",
      label: "Report URL",
      description: "Your call back server URL to recieve delivery status",
      optional: true,
    },
    dataCoding: {
      type: "string",
      label: "Data Encoding",
      description: "Set as `text` for normal GSM 03.38 characters (English, normal characters). Set as `unicode` for non GSM 03.38 characters (Arabic, Chinese, Hebrew, Greek like regional languages and Unicode characters). Set as `auto` so we will find the data_coding based on your content.",
      options: [
        "text",
        "unicode",
        "auto",
      ],
      default: "text",
    },
    msgType: {
      type: "string",
      label: "Message Type",
      description: "Set as `text` for normal GSM 03.38 characters (English, normal characters). Set as `unicode` for non GSM 03.38 characters (Arabic, Chinese, Hebrew, Greek like regional languages and Unicode characters). Set as `auto` so we will find the data_coding based on your content.",
      options: [
        "text",
        "audio",
        "sms",
        "multimedia",
        "image",
      ],
      default: "text",
    },
  },
  methods: {
    sendSMS(args = {}) {
      return this.app.makeRequest({
        method: "post",
        path: `/messages/${constants.API_VERSION}/send`,
        ...args,
      });
    },
  },
  async run({ $: step }) {
    const {
      originator,
      recipients,
      content,
      channel,
      reportUrl,
      dataCoding,
      msgType,
    } = this;

    const response = await this.sendSMS({
      step,
      data: {
        messages: [
          {
            channel,
            recipients,
            content,
            msg_type: msgType,
            data_coding: dataCoding,
          },
        ],
        message_globals: {
          originator,
          report_url: reportUrl,
        },
      },
    });

    step.export("$summary", `Successfully sent SMS with request ID ${response.request_id}`);

    return response;
  },
};

```

Let me know if you get all request changes otherwise DM on slack my user is `jcortes` just in case you want a little help! and remember also you can take a look at the docs [here](https://pipedream.com/docs/components/) and there is also a lot of other component [here](https://github.com/PipedreamHQ/pipedream/tree/master/components) that you can use as a reference! Thanks again!

2022-11-18 10:11 UTC, d7networks commented
Great thanks for the review , requested changes updated in PR. thanks

2022-12-07 13:49 UTC, vellames requested changes
Hi there. Thanks for your contribution!
The code itself looks great. Just some minors. Also, please take a look at the pipeline. Looks like some of then failed.
Most part of the problems you can fix just merging master inside your branch

2022-12-07 13:49 UTC, vellames commented on components/d7_networks/actions/send-sms.mjs
> +    sendSMS(args = {}) {
Hi there. Instead of using `sendSMS` here. Could you please move it to the `app` file?

2022-12-07 13:49 UTC, vellames commented on components/d7_networks/actions/send-sms.mjs
> +      options: [
Could you please move these `options` the the `constants` file?

2022-12-07 13:49 UTC, vellames commented on components/d7_networks/actions/send-sms.mjs
> +  version: "0.0.2",
`0.0.1`

2022-12-07 13:49 UTC, vellames commented on components/d7_networks/actions/send-sms.mjs
> +  description: "Sending sms via D7 networks! [See the docs](https://d7networks.com/docs/Messages/Send_Message/)",
"d7-networks-send-sms"

2022-12-13 13:35 UTC, vunguyenhung commented
Hello @d7networks, I'm Leo, the Integration QA for Pipedream actions

I've created a free account on d7networks and tried to test this action. But I couldn't test this action since it requires Credits/Payment
![image](https://user-images.githubusercontent.com/18277920/207332771-a1ce0746-8952-415e-8f80-4fe9fef87fa3.png)

I've tried to add my phone number to get OTP for Free Credit, but the OTP code isn't arrived (I'm from Vietnam and use +84 country code)
<img width="1919" alt="Screen Shot 2022-12-13 at 20 32 29" src="https://user-images.githubusercontent.com/18277920/207335553-6d9dcf38-492e-4f04-88d5-5c86a305ef11.png">

For the next action @d7networks:
- If you have tested this action on your side, I'd love to move it to ready for release immediately
- Else, could you add some credit to my account with email `hung.v@turing.com` for me to test?

2022-12-14 06:09 UTC, d7networks commented
@vunguyenhung send action is tested from our side you can release these immediately. thanks

2022-12-14 06:16 UTC, merged

2022-12-14 09:38 UTC, d7networks commented
@vunguyenhung   thanks for listing the app , we need one modification here , please change the app name to D7 SMS instead of "D7 Networks".  it will be really helpful for the  users to find us, is this something  that can be done from the code side  please mention. thanks

2022-12-14 09:47 UTC, vunguyenhung commented
Hello @d7networks, I've created [a ticket here](https://github.com/PipedreamHQ/pipedream/issues/4949) to fulfill your request and added to our Prioritized list. Our component dev will take a look at it soon!