Ring central fixes + new action
PipedreamHQ/pipedream pull request #4833
Opened 2022-11-27 00:25 UTC by zalmanlew

Resolves #4822 (thanks to @jcortes) - and updated the description of the source.

Also added a new action for **Get Message** from the message store.

2022-11-27 00:26 UTC, dylburger commented
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

2022-11-27 00:26 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

2022-11-27 15:43 UTC, michelle0927 requested changes
Looks great, thanks! Just one suggestion about using the `$` variable to help with debugging.

2022-11-27 15:43 UTC, michelle0927 commented on components/ringcentral/actions/get-message/get-message.mjs
> +    );
Passing along the `$` variable to the axios call helps us get more meaningful debugging info if an error is thrown. I would have `getMessage` accept an object including `$` as shown below, and then update the `getMessage` method in the app file as well.
```suggestion
    const response = await this.ringcentral.getMessage({
      $,
      accountId: this.accountId,
      extensionId: this.extensionId,
      messageId: this.messageId,
    });
```

2022-11-27 15:43 UTC, michelle0927 commented on components/ringcentral/ringcentral.app.mjs
> +    },
If we update `getMessage` to accept `...args`, we can pass along the `$` variable to `makeRequest`.
```suggestion
    async getMessage({
      accountId = "~", extensionId, messageId, ...args
    } = {}) {
      return this.makeRequest({
        path: `/account/${accountId}/extension/${extensionId}/message-store/${messageId}`,
        ...args,
      });
    },
```

2022-11-28 18:25 UTC, andrewjschuang approved these changes
Thanks for the contribution! LGTM!
I just added a minor commit

2022-11-28 21:29 UTC, Hassan-Abbas-SQA commented
![image](https://user-images.githubusercontent.com/104946677/204384561-980e3ba9-f3d9-40d0-981f-b76924da8dca.png)
![image](https://user-images.githubusercontent.com/104946677/204384910-1e994d42-eba4-44f2-a761-e0a20c226b06.png)

2022-11-30 19:34 UTC, merged