Crove App - Updates generate pdf from template action to use new api
PipedreamHQ/pipedream pull request #4893
Opened 2022-12-06 15:02 UTC by croveapp

## Update the existing generate pdf from template action to use a new api.

### Changes with this update
- We are eliminating the need to use multiple apis by instead using single api to perform the required task.
- Adding background mode input prop.

2022-12-06 15:03 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-12-07 13:44 UTC, vellames requested changes
Hi there. Thanks for your contribution. Instead of using the`_makeRequest` method here. It would be great if you could create a method that calls `_makeRequest` inside the `app`.
If you want some reference you can check a component called `siteleaf`

2022-12-07 13:44 UTC, vellames commented
Also, looks like you have some lint problem

2022-12-08 10:23 UTC, croveapp commented
@vellames We have made the changes as requested. Kindly have a look.

2022-12-09 13:02 UTC, vellames requested changes
Hey. Thanks for the changes! I missed one suggestion in `generate-template-pdf.mjs`, sorry about that. Once you do that, we are good to go

2022-12-09 13:02 UTC, vellames commented on components/crove_app/actions/generate-template-pdf/generate-template-pdf.mjs
> +    let resp = await this.croveApp._makeRequest(config);
Could you please create a method inside `app` and call the method here?

2022-12-09 19:30 UTC, croveapp commented
@vellames the changes you requested have been done please have a look.

2022-12-12 14:43 UTC, feyzullah reviewed
Hi @croveapp, this looks good to me, just changed `var`s with `const`s

2022-12-12 14:43 UTC, feyzullah commented on components/crove_app/actions/generate-template-pdf/generate-template-pdf.mjs
> +    for (var k in symbolTable) {
```suggestion
    for (const k in symbolTable) {
```

2022-12-12 14:43 UTC, feyzullah commented on components/crove_app/actions/generate-template-pdf/generate-template-pdf.mjs
> +    for (var k in symbolTable) {
```suggestion
    for (const k in symbolTable) {
```

2022-12-12 14:58 UTC, feyzullah approved these changes
Ready for QA

2022-12-12 15:41 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[CroveApp_4893_2241.pdf](https://github.com/PipedreamHQ/pipedream/files/10209601/CroveApp_4893_2241.pdf)

2022-12-12 15:42 UTC, merged