Feature/repairshopr 3759
PipedreamHQ/pipedream pull request #4933
Opened 2022-12-12 13:34 UTC by vellames

2022-12-12 16:43 UTC, feyzullah requested changes
Hi @vellames, I guess Superdocu's `package.json` has been deleted accidentally. Can you check? And I have added just a few comments. Can you please check them too?

2022-12-12 16:43 UTC, feyzullah commented on components/repairshopr/package.json
> +
```suggestion

```
oops there were spaces here

2022-12-12 16:43 UTC, feyzullah commented on components/repairshopr/package.json
> +    }
Does not this app have any dependency?

2022-12-12 16:43 UTC, feyzullah commented on components/repairshopr/sources/common/source.mjs
> +        intervalSeconds: 60 * 15,
Can we just use `DEFAULT_POLLING_SOURCE_TIMER_INTERVAL` from `@pipedream/platform` like it is done [here](https://github.com/PipedreamHQ/pipedream/blob/f8ff2ffb27265ef154c1f69c08440d70f9bc4fec/components/podio/sources/common/common-poll.mjs#L11)

2022-12-13 12:28 UTC, vellames commented
Hey @feyzullah. I mess this branch. Please continue your review by looking at #4939 please. I already applied the changes

2022-12-13 12:28 UTC, closed without merging