[ACTION] Add inReplyTo & references to gmail-send-email
PipedreamHQ/pipedream pull request #4940
Opened 2022-12-13 13:45 UTC by jc-tzn

The "References" and "In-Reply-To" headers are necessary to keep an email answer in the same thread as the original email. 

Related documentation:
- Gmail API: https://developers.google.com/gmail/api/guides/sending#sending_messages
- RFC 2822 standard: https://www.rfc-editor.org/rfc/rfc2822#appendix-A.2
- Nodemailer Mailcomposer: https://nodemailer.com/extras/mailcomposer/#e-mail-message-fields

2022-12-13 13:45 UTC, dylburger commented
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

2022-12-13 13:46 UTC, dylburger commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2022-12-15 21:04 UTC, andrewjschuang approved these changes
Looks great! I just added some nitpicks

2022-12-15 21:04 UTC, andrewjschuang commented on components/gmail/actions/send-email/send-email.mjs
> +      description: "Specify the message-id this email is replying to. To use this prop with async options please use `Gmail(Developer App)` `Send Email` component.",
```suggestion
      description: "Specify the `message-id` this email is replying to. To use this prop with `async options` please use `Gmail (Developer App)` `Send Email` component.",
```

Also we should remove the `replyTo` prop.

2022-12-15 21:13 UTC, andrewjschuang requested changes
Actually, I copied the `message-id` from `async options` and pasted to the **Gmail** app and tried sending the email, but it said that the value is not a valid message ID.

The **Gmail Developer App** worked fine though.

2022-12-15 21:25 UTC, feyzullah commented
> Actually, I copied the `message-id` from `async options` and pasted to the **Gmail** app and tried sending the email, but it said that the value is not a valid message ID.
> 
> The **Gmail Developer App** worked fine though.

Oops! This is again because of the insufficient scopes. Let me remove it from there and add directly to threadId.

2022-12-15 21:47 UTC, feyzullah commented
Now this should be able to reply non-replied emails. If a replied message-id would be given Gmail API will return an error because `threadId` is not existing. We can remove this prop from Gmail app and keep it in Gmail (Developer App). What do you think @andrewjschuang?

2022-12-15 21:56 UTC, andrewjschuang commented
Oh, so in the **Gmail** app `threadId` won't work? If so, yeah we can leave it only on the **Gmail Developer App**

2022-12-15 22:07 UTC, feyzullah commented
> Oh, so in the **Gmail** app `threadId` won't work? If so, yeah we can leave it only on the **Gmail Developer App**

It works for the first message. If replying to a reply, it will fail. Then I am removing the prop from Gmail app

2022-12-16 14:35 UTC, andrewjschuang commented
> It works for the first message. If replying to a reply, it will fail. Then I am removing the prop from Gmail app

Ok, I see. After testing a little bit more I have a few suggestions:

- `opts.inReplyTo` and `opts.references` are actually not needed (delete lines 96-97, 99-100).
- `inReplyTo` prop description in **Gmail** app: add that it must be the `message-id` of the first message sent in the thread.
- In the **Gmail** app, if the error is `Requested entity was not found` (`message-id` was not for the first message in the thread), change the error message to: **Unable to find email thread. `In Reply To` must be the `message-id` of the first message of the thread.**

Other than that looks great to me!

2022-12-16 16:04 UTC, feyzullah commented
> 

@andrewjschuang I have applied second and third suggestions. However when I don't send `inReplyTo` and `refenreces`, sender side is able to cluster all under one thread ID but receiver side is not. The following happens for sender side;
![sender](https://user-images.githubusercontent.com/8221369/208139221-70e7a021-34d0-4e25-8dbc-cc6dce8d771a.JPG)

And for the receiver side;
![receiver](https://user-images.githubusercontent.com/8221369/208139282-b8fb3fee-6ed8-4942-b2dc-6f435204d65c.JPG)

Am I missing something here? Or is there some other config to be done?

2022-12-16 16:11 UTC, andrewjschuang commented
> @andrewjschuang I have applied second and third suggestions. However when I don't send `inReplyTo` and `refenreces`, sender side is able to cluster all under one thread ID but receiver side is not.

Oh ok, sorry please keep it that way

2022-12-16 16:50 UTC, andrewjschuang approved these changes

2022-12-16 20:48 UTC, merged