3748 quipu actions
PipedreamHQ/pipedream pull request #5011
Opened 2022-12-21 15:58 UTC by alysonturing

### Actions:
- create-contact
- create-invoice
- create-ticket

2022-12-22 13:43 UTC, lcaresia requested changes
Thanks for your contribution!

Need just some fixes!

2022-12-22 13:43 UTC, lcaresia commented on components/quipu/actions/create-contact/create-contact.mjs
> +      label: "Tax Id (CIF/NIF)",
```suggestion
      label: "Tax ID (CIF/NIF)",
```

2022-12-22 13:43 UTC, lcaresia commented on components/quipu/actions/create-contact/create-contact.mjs
> +    $.export("$summary", `Successfully created contact "${contact.id}"`);
```suggestion
    $.export("$summary", `Successfully created contact with ID "${contact.id}"`);
```

2022-12-22 13:43 UTC, lcaresia commented on components/quipu/actions/create-contact/create-contact.mjs
> +  name: "Creating a contact",
```suggestion
  name: "Create Contact",
```

2022-12-22 13:43 UTC, lcaresia commented on components/quipu/actions/create-invoice/create-invoice.mjs
> +  name: "Creating an invoice",
```suggestion
  name: "Create Invoice",
```

2022-12-22 13:43 UTC, lcaresia commented on components/quipu/actions/create-invoice/create-invoice.mjs
> +        console.log(items);
```suggestion
```

2022-12-22 13:43 UTC, lcaresia commented on components/quipu/actions/create-ticket/create-ticket.mjs
> +  name: "Creating a ticket",
```suggestion
  name: "Create Ticket",
```

2022-12-22 13:43 UTC, lcaresia commented on components/quipu/actions/create-ticket/create-ticket.mjs
> +    $.export("$summary", `Successfully created ticket "${ticket.id}"`);
```suggestion
    $.export("$summary", `Successfully created ticket with ID "${ticket.id}"`);
```

2022-12-22 13:43 UTC, lcaresia commented on components/quipu/actions/create-invoice/create-invoice.mjs
> +    $.export("$summary", `Successfully created invoice "${invoice.id}"`);
```suggestion
    $.export("$summary", `Successfully created invoice with ID "${invoice.id}"`);
```

2022-12-22 13:43 UTC, lcaresia commented on components/quipu/package.json
> +    "@pipedream/platform": "^1.2.0"
https://www.npmjs.com/package/@pipedream/platform

The lastest version is `1.2.1`, you can update to last one

2022-12-22 13:43 UTC, lcaresia commented on components/quipu/quipu.app.mjs
> +        "Authorization": `Bearer ${this.$auth.oauth_access_token}`,
Move this to a getter method.

```suggestion
        "Authorization": `Bearer ${this._accessToken()}`,
```

2022-12-22 13:59 UTC, lcaresia approved these changes
LGTM!

2022-12-22 18:58 UTC, DilanAthukorala commented
@alysonturing following issues observed,

1. Can we add how to obtain the APP ID and Secret here?
![image](https://user-images.githubusercontent.com/102980146/209198468-b9839d3e-71f4-4f44-a164-be460181a414.png)


2. Create Ticket Action, Items are not getting created in quipu 
![image](https://user-images.githubusercontent.com/102980146/209206902-44a33117-7801-4b5b-87e8-7905166e302f.png)


3. Rename Components create ticket and create invoice to - "Create Income Ticket" & "Create Income Invoice" (This can help separate the expense ticket and invoices)

2022-12-22 19:14 UTC, alysonturing commented
The first issue must to be addressed to @dannyroosevelt 

I'm fixing the rest, thanks

2022-12-22 20:31 UTC, dannyroosevelt commented
>Can we add how to obtain the APP ID and Secret here?

Done, thanks for flagging @DilanAthukorala

2022-12-23 13:14 UTC, alysonturing commented
@DilanAthukorala everything was resolved

2022-12-23 13:14 UTC, alysonturing commented
/approve

2022-12-23 14:04 UTC, DilanAthukorala commented
Verification completed, ready for release.

2022-12-23 14:31 UTC, lcaresia approved these changes
LGTM!

2022-12-23 14:42 UTC, merged