3582 chartmogul
PipedreamHQ/pipedream pull request #5014
Opened 2022-12-21 20:44 UTC by luancazarine

ChartMogul

Actions
  - Add a Custom Attribute to a Customer via Email
  - Add a Custom Attribute to a Customer via UUID
  - Add Tags to a Customer via UUID
  - Add Tags to a Customer via Email
  - Create a Customer
  - Merge Customers
  - Update a Customer
  - Search for Customer via Email
  - Search for Customer via External ID
  - Retrieve a Customer Profile
  - Retrieve All Key Metrics
  - Retrieve Average Revenue Per Account (ARPA)
  - Retrieve ARR
  - Retrieve Average Sale Price (ASP)
  - Retrieve Customer Churn Rate
  - Retrieve Customer Count
  - Retrieve Customer Lifetime Value (LTV)
  - Retrieve MRR
  - Retrieve MRR Churn Rate

2022-12-22 13:57 UTC, lcaresia requested changes
Thanks for your contribution!

Need just some fixes!

2022-12-22 13:57 UTC, lcaresia commented on components/chartmogul/actions/add-custom-attributes-via-email/add-custom-attributes-via-email.mjs
> +    $.export("$summary", "Custom Attributes Successfully added");
You can do this to the others actions too.

Obs: I didn't tested this.

```suggestion
    $.export("$summary", `Custom attributes successfully added with ID ${response.id}`);
```

2022-12-22 13:57 UTC, lcaresia commented on components/chartmogul/actions/add-tags-via-email/add-tags-via-email.mjs
> +  version: "0.0.3",
```suggestion
  version: "0.0.1",
```

2022-12-22 13:57 UTC, lcaresia commented on components/chartmogul/package.json
> +  "version": "0.0.2",
```suggestion
  "version": "0.0.1",
```

2022-12-22 18:44 UTC, lcaresia requested changes
Fix the `export` summary to all actions/sources too.

Like this https://github.com/PipedreamHQ/pipedream/pull/5014#discussion_r1055476576

2022-12-22 19:25 UTC, lcaresia submitted a review, later dismissed
LGTM!

2022-12-26 20:51 UTC, luancazarine commented
/approve

2022-12-26 21:58 UTC, alysonturing requested changes
Thanks for your contribution, please check the following warnings and then you're good to go.

2022-12-26 21:58 UTC, alysonturing commented on components/chartmogul/actions/search-customers-via-email/search-customers-via-email.mjs
> +      return;
you should expose the error for better use experience, in this case, you could log the original error `log(e);` and throw a ConfigurationError with a custom message.

2022-12-26 21:58 UTC, alysonturing commented on components/chartmogul/actions/search-customers-via-external-id/search-customers-via-external-id.mjs
> +      return;
you should expose the error for better use experience, in this case, you could log the original error log(e); and throw a ConfigurationError with a custom message.

2022-12-27 15:46 UTC, alysonturing approved these changes
LGTM!

2022-12-27 17:00 UTC, merged