Leadfeeder new actions sources
PipedreamHQ/pipedream pull request #5018
Opened 2022-12-21 22:48 UTC by jcortes

2022-12-22 15:23 UTC, lcaresia requested changes
Thanks for your contribution!

Need just one fix!

2022-12-22 15:23 UTC, lcaresia commented on components/leadfeeder/leadfeeder.app.mjs
> +        "Authorization": `Token token=${this.$auth.api_token}`,
Move this to a getter method!

```suggestion
        "Authorization": `Token token=${this._apiToken()}`,
```

2022-12-22 18:41 UTC, lcaresia approved these changes
LGTM!

2022-12-23 15:27 UTC, vunguyenhung commented
Hello @jcortes, I've successfully installed the feedleader into a live wordpress website, though I couldn't create any new leads eventhough I've waited for a while

![22 25 33 - 23 - 12 - 2022](https://user-images.githubusercontent.com/18277920/209359831-3a481693-5768-4321-a939-d52fe2c0c0f0.png)


I think for now I'll let it ready for release, then we'll track for future issue if needed

2022-12-23 16:04 UTC, merged