Clientary actions & sources
PipedreamHQ/pipedream pull request #5022
Opened 2022-12-22 18:35 UTC by feyzullah

### Actions
* Create Client
* Create Expense
* Create Estimate
* Create Invoice
* Create Task
### Sources
* New Contact Created
* New Expense Created
* New Payment Created
* New Project Created
* New Staff Created
* New Task Created
* New Invoice Created
* New Client Created
* New Estimate Created

2022-12-22 21:16 UTC, lcaresia requested changes
Just some fixes!

2022-12-22 21:16 UTC, lcaresia commented on components/clientary/app/clientary.app.ts
> +          page,
```suggestion
        return await utils.getAsyncOptions({
          resourceFn: this.getRequestMethod("getProjects"),
          page: page + 1,
```

2022-12-22 21:16 UTC, lcaresia commented on components/clientary/app/clientary.app.ts
> +          page,
```suggestion
        return await utils.getAsyncOptions({
          resourceFn: this.getRequestMethod("getInvoices"),
          page: page + 1,
```

2022-12-23 01:02 UTC, lcaresia approved these changes
LGTM!

2022-12-23 15:05 UTC, DilanAthukorala commented
@feyzullah Please check the following improvements,

1. Create Estimate Action -`Estimate Item Attributes` should be a mandatory prop
![image](https://user-images.githubusercontent.com/102980146/209351876-5372370c-7b05-466a-857d-2acb094d150f.png)


2. Create Expense Action - `client_id` and `invoice_id` is not properly passed to Clientary
![image](https://user-images.githubusercontent.com/102980146/209353186-04713abf-6b1f-4608-b0e8-f667b9421e77.png)


3. Create Invoice Action - `Estimate Item Attributes` should be a mandatory prop
![image](https://user-images.githubusercontent.com/102980146/209353597-d4db763a-562c-43d8-9e50-1258cf791336.png)


4. Create Task Action - `client_id`  is not properly passed to Clientary
![image](https://user-images.githubusercontent.com/102980146/209354252-79bd97d3-4e06-4618-bdd6-d05b4b5e652b.png)

2022-12-23 21:26 UTC, feyzullah commented
> @feyzullah Please check the following improvements,
> 
> 1. Create Estimate Action -`Estimate Item Attributes` should be a mandatory prop
>    ![image](https://user-images.githubusercontent.com/102980146/209351876-5372370c-7b05-466a-857d-2acb094d150f.png)
> 2. Create Expense Action - `client_id` and `invoice_id` is not properly passed to Clientary
>    ![image](https://user-images.githubusercontent.com/102980146/209353186-04713abf-6b1f-4608-b0e8-f667b9421e77.png)
> 3. Create Invoice Action - `Estimate Item Attributes` should be a mandatory prop
>    ![image](https://user-images.githubusercontent.com/102980146/209353597-d4db763a-562c-43d8-9e50-1258cf791336.png)
> 4. Create Task Action - `client_id`  is not properly passed to Clientary
>    ![image](https://user-images.githubusercontent.com/102980146/209354252-79bd97d3-4e06-4618-bdd6-d05b4b5e652b.png)

Hi @DilanAthukorala I have fixed 1st and 3rd ones. They are still optional but you won't see that error if they are not given.
For 2nd and 4th ones, if `client_id` is given with the `project_id`, the project must have the related client in clients on Clientary.
In 2nd one, I was not able to pass `invoice_id` to Clientary under any condition, so I removed that prop from the action. Can you please check once more?

2022-12-26 15:54 UTC, DilanAthukorala commented
Verification completed, ready for release!

2022-12-26 16:18 UTC, feyzullah commented
/approve

2022-12-26 16:45 UTC, alysonturing approved these changes
LGTM!

2022-12-26 16:57 UTC, merged