5057 action discord bot modify guild member
PipedreamHQ/pipedream pull request #5065
Opened 2022-12-30 13:24 UTC by luancazarine

Action
  - Modify Guild Member

2022-12-30 15:25 UTC, alysonturing requested changes
Please check the minor issues pointed

2022-12-30 15:25 UTC, alysonturing commented on components/discord_bot/actions/modify-guild-member/modify-guild-member.mjs
> +      description: "When the user's [timeout](https://support.discord.com/hc/en-us/articles/4413305239191-Time-Out-FAQ) will expire and the user will be able to communicate in the guild again (up to
Can you add examples of how the user could fill that field? e.g: `1 hour` or `10 days` or the way its supposed to be filled?

2022-12-30 15:25 UTC, alysonturing commented on components/discord_bot/package.json
> +  "version": "0.5.0",
Since it doesn't have major changes, it should be `0.4.1`, do you agree?

2023-01-02 17:11 UTC, GTFalcao reviewed
Hi @luancazarine , thanks for your contribution!

I've left two comments regarding one small code suggestion and one minor grammar suggestion.

2023-01-02 17:11 UTC, GTFalcao commented on components/discord_bot/actions/modify-guild-member/modify-guild-member.mjs
> +  Object.keys(OTHER_CHANNELS).map((key) => OTHER_CHANNELS[key]);
```suggestion
  Object.values(OTHER_CHANNELS);
```

2023-01-02 17:11 UTC, GTFalcao commented on components/discord_bot/actions/modify-guild-member/modify-guild-member.mjs
> +    $.export("$summary", `Member with Id ${userId} Successfully modified!`);
```suggestion
    $.export("$summary", `Member with Id ${userId} successfully modified!`);
```

2023-01-02 20:35 UTC, GTFalcao approved these changes
Looks good to me! 👏

2023-01-04 12:30 UTC, luancazarine commented
/approve

2023-01-04 15:56 UTC, alysonturing approved these changes

2023-01-04 18:15 UTC, merged