Solve CRM New Sources and Actions
PipedreamHQ/pipedream pull request #5083
Opened 2023-01-02 21:42 UTC by michelle0927

Resolves #3789

**Sources**
- New Company
- New Contact
- New Tagged Contact
- New User

**Actions**
- Create Contact

2023-01-02 22:38 UTC, GTFalcao requested changes
Hi @michelle0927 , thanks for your contribution, this looks good!

I left a comment about the source component names, they should all be adjusted as per the recent update to the guidelines.

2023-01-02 22:38 UTC, GTFalcao commented on components/solve_crm/actions/create-contact/create-contact.mjs
> +    $.export("$summary", `Sucessfully created contact with ID ${response.item.id}`);
```suggestion
    $.export("$summary", `Successfully created contact with ID ${response.item.id}`);
```

2023-01-02 22:38 UTC, GTFalcao commented on components/solve_crm/sources/new-company/new-company.mjs
> +  name: "New Company (Instant)",
We should update all the source keys in accordance with [the updated guidelines](https://pipedream.com/docs/components/guidelines/#component-key-pattern):
`Company Created (Instant)`
or
`New Company Created (Instant)`

2023-01-03 17:25 UTC, GTFalcao approved these changes
Looks good to me! 👏

2023-01-03 18:11 UTC, DilanAthukorala commented
@michelle0927 Observing following issue,

1. "Create Contact" Action - "Mobile Phone" value is not getting updated in Solve CRM. 
![image](https://user-images.githubusercontent.com/102980146/210413804-03042002-75d6-4ab2-b6e1-6ef7686dfe6d.png)

2. "New Contact Tagged" Source is not filtering events by "Category"
![image](https://user-images.githubusercontent.com/102980146/210415831-7cee2c7f-538c-4eaf-91e5-dcf8ee5ef0fd.png)
![image](https://user-images.githubusercontent.com/102980146/210415719-dd1186f7-e4ff-47bb-a8b5-b320a86cc462.png)

2023-01-03 19:44 UTC, DilanAthukorala commented
@michelle0927 I'm still observing `"New Contact Tagged" Source is not filtering events by "Category"` issue

2023-01-03 20:17 UTC, DilanAthukorala commented
Verification success, ready for release!

2023-01-03 20:18 UTC, michelle0927 commented
/approve

2023-01-03 20:19 UTC, GTFalcao approved these changes

2023-01-03 20:19 UTC, merged