intuiface
PipedreamHQ/pipedream pull request #5103
Opened 2023-01-04 15:36 UTC by alysonturing

adding send-message and available-experiences actions

2023-01-04 16:26 UTC, alysonturing commented
<img width="489" alt="Captura de Tela 2023-01-04 às 13 24 00" src="https://user-images.githubusercontent.com/103650302/210602165-80ee9c62-d491-44a3-b120-5d5488b7a0a6.png">
<img width="486" alt="Captura de Tela 2023-01-04 às 13 24 11" src="https://user-images.githubusercontent.com/103650302/210602174-cddcde09-0d52-48c5-8e85-0f747c29d97a.png">
<img width="471" alt="Captura de Tela 2023-01-04 às 13 24 32" src="https://user-images.githubusercontent.com/103650302/210602177-593d6ba2-5ef6-4a4d-ad8d-ca9976157ba3.png">
<img width="481" alt="Captura de Tela 2023-01-04 às 13 24 50" src="https://user-images.githubusercontent.com/103650302/210602180-2def2d4a-b0e7-4f49-8ba4-4c82cdfd40af.png">

2023-01-06 16:10 UTC, GTFalcao requested changes
Hi @alysonturing , thanks for your contribution!

I've pointed out a few minor edits needed before this can be merged - but I'll move this to QA as those are not related to functionality.

2023-01-06 16:10 UTC, GTFalcao commented on components/intuiface/actions/available-experiences/available-experiences.mjs
> +  version: "0.0.3",
```suggestion
  version: "0.0.1",
```

2023-01-06 16:10 UTC, GTFalcao commented on components/intuiface/actions/available-experiences/available-experiences.mjs
> +  name: "Available Experiences",
I think "List Available Experiences" would be more appropriate for the action name

2023-01-06 16:10 UTC, GTFalcao commented on components/intuiface/actions/send-message/send-message.mjs
> +  version: "0.0.10",
```suggestion
  version: "0.0.1",
```

2023-01-09 11:04 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Intuiface_3660.pdf](https://github.com/PipedreamHQ/pipedream/files/10372535/Intuiface_3660.pdf)

2023-01-09 12:01 UTC, alysonturing commented
/approve

2023-01-09 16:41 UTC, GTFalcao approved these changes

2023-01-09 16:42 UTC, merged