[ACTIONS/SOURCES]: Prodbad new actions sources
PipedreamHQ/pipedream pull request #5400
Opened 2023-02-03 02:28 UTC by jcortes

Solves #3742

2023-02-03 16:34 UTC, andrewjschuang requested changes
Looking very good! The code is very very clean and easy to read!
I left just a few comments!

2023-02-03 16:34 UTC, andrewjschuang commented on components/prodpad/actions/create-company/create-company.mjs
> +        tags: tagIds?.map((id) => ({
Please add a verification - if the input is a string, parse it (due to custom expressions). Same with other actions!
[See example.](https://github.com/PipedreamHQ/pipedream/blob/master/components/adroll/actions/replace-emails-from-crm-audience/replace-emails-from-crm-audience.mjs#L40)

2023-02-03 16:34 UTC, andrewjschuang commented on components/prodpad/actions/find-idea/find-idea.mjs
> +    const { ideas } = await this.listIdeas({
```suggestion
    const { ideas } = await this.app.listIdeas({
```
Can we use the method defined in the app file instead of this one?

2023-02-03 16:34 UTC, andrewjschuang commented on components/prodpad/actions/find-idea/find-idea.mjs
> +  },
```suggestion
```

2023-02-06 12:17 UTC, andrewjschuang commented on components/prodpad/prodpad.app.mjs
> +        if (Array.isArray(response)) {
But wouldn't it be be returned in [this line](https://github.com/PipedreamHQ/pipedream/blob/4681a45eeb5a088148d4fc6482f482a164b8ed7d/components/prodpad/prodpad.app.mjs#L400)?

2023-02-06 12:18 UTC, andrewjschuang approved these changes
Thanks, LGTM!
I just left a question in the the thread about pagination

2023-02-06 12:18 UTC, andrewjschuang commented on components/prodpad/actions/create-company/create-company.mjs
> +        tags: tagIds?.map((id) => ({
Thank you, the solution is very good!

2023-02-08 02:52 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Prodpad_3742_0946.pdf](https://github.com/PipedreamHQ/pipedream/files/10681206/Prodpad_3742_0946.pdf)

2023-02-08 15:27 UTC, merged