Shopify - Access Read/Write Shopify Metafields
PipedreamHQ/pipedream pull request #5426
Opened 2023-02-07 20:36 UTC by michelle0927

Resolves #5375

2023-02-08 13:18 UTC, vellames requested changes

2023-02-08 13:18 UTC, vellames commented on components/shopify/actions/common/metafield-actions.mjs
> +      if (ownerResource === "product") {
Looks like we always have `ownerId` field in the props. If that's the case, can we start `props` with this property and just remove some of these `ifs`?

2023-02-09 14:04 UTC, vellames approved these changes
lgtm

2023-02-10 20:24 UTC, michelle0927 commented
/approve

2023-02-10 22:12 UTC, merged

2023-02-17 23:43 UTC, zecul commented
Hi, I'm not currently able to make this work. I have a list metafield for products called "labels"
![image](https://user-images.githubusercontent.com/123815443/219816833-031ad3b4-7b87-437a-a53d-ffb09d7d9a9b.png)

Currently contains data:
![image](https://user-images.githubusercontent.com/123815443/219816919-2775923c-83b3-482b-b8ca-06fd44cd29ec.png)

I'm updating the data in the format recommended by https://shopify.dev/docs/apps/custom-data/metafields/types#list-types
![image](https://user-images.githubusercontent.com/123815443/219817022-712c3548-cc49-4b6e-a5bd-3a902d5873c7.png)

But there is an error returned:
![image](https://user-images.githubusercontent.com/123815443/219817184-9120d12a-2da4-4f12-bec7-f15a222ee1f5.png)