#5172 - Formatter actions
PipedreamHQ/pipedream pull request #5430
Opened 2023-02-08 04:13 UTC by GTFalcao

19 new actions for the new `Formatting` utilities app.

Closes #5172

2023-02-08 13:43 UTC, vellames requested changes

2023-02-08 13:43 UTC, vellames commented on components/formatting/actions/format-number/format-number.ts
> +      options: [
Could you please move the `options` of this file to a separated `options` file?

2023-02-08 13:43 UTC, vellames commented on components/formatting/actions/split-text/split-text.ts
> +      options: [
Could you please move these `options` to an options file?

2023-02-08 13:43 UTC, vellames commented on components/formatting/actions/transform-case/transform-case.ts
> +      options: CASE_OPTIONS.map(({
Could you please move these `options` to an options file?

2023-02-09 14:04 UTC, vellames requested changes
Lint problems :/
Please check pipeline

2023-02-10 13:00 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Fomatting_5172.pdf](https://github.com/PipedreamHQ/pipedream/files/10707592/Fomatting_5172.pdf)

2023-02-10 20:28 UTC, GTFalcao commented
/approve

2023-02-10 22:00 UTC, vellames approved these changes

2023-02-10 22:11 UTC, merged