[FEATURE] @pipedream/platform axios should support the ability to create custom axios constructor, or pass all standard axios options #5497
PipedreamHQ/pipedream pull request #5544
Opened 2023-02-22 13:19 UTC by lcaresia

2023-02-24 14:57 UTC, vunguyenhung commented
Hello @lcaresia @andrewjschuang, would you mind advice how can I test this? Or is this needed testing?

2023-02-24 16:02 UTC, andrewjschuang commented
@vunguyenhung I think you can create two instances of each `axios`, e.g.
```js
import axios from "axios";
import { axios as pipedreamAxios } from "./platform/dist/index.js";
```
or something like that.

And then create a config to pass in to the constructor with most or all `axios` parameters, make the request and see if they were really used by `pipedreamAxios`.

2023-02-27 03:39 UTC, vunguyenhung commented
Hello @andrewjschuang, I couldn't test the action due to an error on the publish action step. 

Could you check the test report below and advice how can I test it?
[Axios_5544_1037.pdf](https://github.com/PipedreamHQ/pipedream/files/10835843/Axios_5544_1037.pdf)

2023-02-28 09:52 UTC, andrewjschuang commented
Hi @lcaresia, looking at the code, seems like the change doesn't reflect in anything in practice, since we don't remove any key from the `config` object.

Also, looking at [the thread](https://pipedream.com/community/t/can-i-use-axios-directly-with-pipedream/4774/2) that originated this issue, I think it's if best we implemente the [axios.create()](https://axios-http.com/docs/instance) method.

I also thought of adding a flag `fullResponse` with `default: false` in `AxiosRequestConfig` that enables the user to receive the whole [response schema](https://axios-http.com/docs/res_schema) from the request instead of just `data`, what do you think?

2023-03-07 13:02 UTC, lcaresia commented
@vunguyenhung @andrewjschuang 

You can test creating an `test.js` file on project root folder with this code:

```
const {
  axios, createAxiosInstance,
} = require("./platform/dist");

async function test1() {
  const createdAxios = createAxiosInstance({
    baseURL: "https://random-data-api.com/api/v2",
  });

  const response = await createdAxios.get("users");

  console.log("createdAxios:", response);
}

async function test2() {
  const data = await axios(this, {
    url: "https://random-data-api.com/api/v2/users",
    returnRawResponse: false,
  });

  console.log("onlyData:", data);
}

async function test3() {
  // const axios = createAxiosInstance({});

  const response = await axios(this, {
    url: "https://random-data-api.com/api/v2/users",
    returnRawResponse: true,
  });

  console.log("returnRawResponse:", response);
}

test1();
test2();
test3();
```

2023-03-07 17:10 UTC, andrewjschuang requested changes
Thanks @lcaresia!
I've left some comments about some improvements, but overall this is in the right track!

2023-03-07 17:10 UTC, andrewjschuang commented on platform/lib/index.ts
> +  createAxiosInstance,
```suggestion
```
See other comment about `axios.create`

2023-03-07 17:10 UTC, andrewjschuang commented on platform/lib/index.ts
> +import axios, { createAxiosInstance } from "./axios";
```suggestion
```
See other comment about `axios.create`

2023-03-07 18:31 UTC, lcaresia commented on platform/lib/axios.ts
> +interface PipedreamAxiosRequestConfig extends AxiosRequestConfig {
Oh, I didn't see that

2023-03-13 20:49 UTC, andrewjschuang approved these changes

2023-03-13 21:09 UTC, merged