[SOURCES] Parseur added new sources
PipedreamHQ/pipedream pull request #5587
Opened 2023-03-01 00:12 UTC by jcortes

2023-03-01 14:24 UTC, alysonturing commented on components/parseur/sources/common/webhook.mjs
> +    async deploy() {},
is there any reason to leave this empty deploy function?

2023-03-01 14:28 UTC, alysonturing requested changes
Please check this one comment that I did for improvement.

2023-03-01 19:53 UTC, alysonturing approved these changes
LGTM!

2023-03-03 04:39 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Parseur_5587.pdf](https://github.com/PipedreamHQ/pipedream/files/10878218/Parseur_5587.pdf)

2023-03-03 14:26 UTC, merged