[ACTION] Zoom new action list webinar participants report plus refactor
PipedreamHQ/pipedream pull request #5597
Opened 2023-03-02 01:43 UTC by jcortes

2023-03-03 00:06 UTC, alysonturing requested changes
Thanks for your contributions, I just added some minor changes to improve usability and ensure our pattern

2023-03-03 00:06 UTC, alysonturing commented on components/zoom/sources/meeting-ended/meeting-ended.mjs
>    description: "Emit new event each time a meeting ends where you're the host",
is it possible to add the link to the docs?

2023-03-03 00:06 UTC, alysonturing commented on components/zoom/sources/meeting-started/meeting-started.mjs
>    description: "Emit new event each time a meeting starts where you're the host",
is it possible to add the link to the docs?

2023-03-03 00:06 UTC, alysonturing commented on components/zoom/sources/meeting-updated/meeting-updated.mjs
>    description: "Emit new event each time a meeting is updated where you're the host",
is it possible to add the link to the docs?

2023-03-03 00:06 UTC, alysonturing commented on components/zoom/sources/phone-event/phone-event.mjs
> +  description: "Emit new Zoom Phone event tied to your Zoom user or resources you own",
is it possible to add the link to the docs?

2023-03-03 00:06 UTC, alysonturing commented on components/zoom/sources/recording-completed/recording-completed.mjs
>    description: "Emit new event each time a new recording completes for a meeting or webinar where you're the host",
is it possible to add the link to the docs?

2023-03-03 00:06 UTC, alysonturing commented on components/zoom/sources/webinar-created/webinar-created.mjs
>    description: "Emit new event each time a webinar is created where you're the host",
is it possible to add the link to the docs?

2023-03-03 00:06 UTC, alysonturing commented on components/zoom/sources/webinar-deleted/webinar-deleted.mjs
>    description: "Emit new event each time a webinar is deleted where you're the host",
is it possible to add the link to the docs?

2023-03-03 00:06 UTC, alysonturing commented on components/zoom/sources/webinar-ended/webinar-ended.mjs
>    description: "Emit new event each time a webinar ends where you're the host",
is it possible to add the link to the docs?

2023-03-03 00:06 UTC, alysonturing commented on components/zoom/sources/webinar-started/webinar-started.mjs
>    description: "Emit new event each time a webinar starts where you're the host",
is it possible to add the link to the docs?

2023-03-03 00:06 UTC, alysonturing commented on components/zoom/sources/webinar-updated/webinar-updated.mjs
>    description: "Emit new event each time a webinar is updated where you're the host",
is it possible to add the link to the docs?

2023-03-04 02:42 UTC, alysonturing submitted a review, later dismissed
LGTM!

2023-03-07 02:49 UTC, vunguyenhung commented
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Zoom_5597_0948.pdf](https://github.com/PipedreamHQ/pipedream/files/10904926/Zoom_5597_0948.pdf)

2023-03-09 00:02 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Zoom_5597_7001.pdf](https://github.com/PipedreamHQ/pipedream/files/10926363/Zoom_5597_7001.pdf)

2023-03-09 03:21 UTC, GTFalcao approved these changes

2023-03-09 13:21 UTC, merged