[Actions] Orbit
PipedreamHQ/pipedream pull request #5601
Opened 2023-03-02 14:31 UTC by vellames

Closes #3711

Unfortunately, Orbit is presenting an error in their API for webhook creation. Even trying to create a Webhook directly from their site, I receive a `422` error.

2023-03-02 15:44 UTC, alysonturing commented on components/orbit/actions/create-activity/create-activity.mjs
> +    ocurredAt: {
You have a typo here, `occurred`

2023-03-02 16:02 UTC, alysonturing commented on components/orbit/actions/create-activity/create-activity.mjs
> +    $.export("$summary", "Activity successfully created");
can you export the identification of the created resource?

2023-03-02 16:02 UTC, alysonturing commented on components/orbit/actions/create-member-note/create-member-note.mjs
> +    $.export("$summary", "Note successfully created");
can you export the identification of the created resource?

2023-03-02 16:09 UTC, alysonturing commented on components/orbit/actions/create-member/create-member.mjs
> +    $.export("$summary", "Member successfully created");
can you export the identification of the created resource?

2023-03-02 16:10 UTC, alysonturing commented on components/orbit/actions/get-member-by-identity/get-member-by-identity.mjs
> +    $.export("$summary", "Member(s) successfully fetched");
can you export the count number of exported data?

2023-03-02 16:12 UTC, alysonturing requested changes
Thanks for your contribution. Please check the minor changes pointed out.

2023-03-02 19:55 UTC, alysonturing approved these changes
LGTM!

2023-03-03 06:01 UTC, vunguyenhung commented
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Orbit_3711_1300.pdf](https://github.com/PipedreamHQ/pipedream/files/10878650/Orbit_3711_1300.pdf)

2023-03-04 18:27 UTC, vellames commented
Hey @vunguyenhung. I have tested the find and looks like this is a problem in Orbit API. Try to add a github account to one of the members and use the filters: `Source = github` and `Username = {yourusername}`.
I ensured I am using all params in the right way and looks like this is something related to the way that Orbit works

2023-03-07 03:11 UTC, vunguyenhung commented
Hi @vellames, your points make sense to me. I'll move this to ready for release!

2023-03-07 03:24 UTC, merged