Overloop - New Components
PipedreamHQ/pipedream pull request #5611
Opened 2023-03-03 20:56 UTC by michelle0927

Resolves #3712

2023-03-06 13:48 UTC, alysonturing requested changes
Thanks for your contribution, please check the requested changes.

2023-03-06 13:48 UTC, alysonturing commented on components/overloop/actions/mark-deal-won/mark-deal-won.mjs
> +    const { data: response } = await this.overloop.markDealLost(this.dealId, {
is that correct? this action is `mark-deal-won` but the method called is `markDealLost`

2023-03-06 13:48 UTC, alysonturing commented on components/overloop/overloop.app.mjs
> +    markDealWon(dealId, args = {}) {
I believe that this method is not being used

2023-03-06 21:43 UTC, GTFalcao commented
Hi @michelle0927 , I see the requested change has been addressed, so this is good to go!

@alysonturing since you had previously requested changes, Github will require your approval before the PR can be merged.

2023-03-07 16:57 UTC, michelle0927 commented
/approve

2023-03-07 16:57 UTC, GTFalcao approved these changes

2023-03-07 16:59 UTC, alysonturing commented
Sorry, it's done!

2023-03-07 17:01 UTC, merged