Actions - Refersion
PipedreamHQ/pipedream pull request #5705
Opened 2023-03-13 13:17 UTC by vellames

Closes #3757

It was not possible to implement all actions and sources because the free account was limited in some ways

2023-03-13 15:10 UTC, luancazarine requested changes
Hi @vellames 
Thanks for your contribution, I just left some comments, please verify if the those are applicable.

2023-03-13 15:10 UTC, luancazarine commented on components/refersion/package.json
> +  "version": "0.0.1",
```suggestion
  "version": "0.0.5",
```

2023-03-13 15:10 UTC, luancazarine commented on components/refersion/actions/get-affiliate/get-affiliate.mjs
> +      optional: true,
```suggestion
      propDefinition: [
        app,
        "affiliateId",
      ],
```

2023-03-13 15:10 UTC, luancazarine commented on components/refersion/actions/manual-commission-credit/manual-commission-credit.mjs
> +    const res = await this.app.createManualCommissionCredit(data, $);
```suggestion
    const {
        app,
        ...data
    } = this;
    
    const res = await app.createManualCommissionCredit(data, $);
```

2023-03-14 13:18 UTC, luancazarine submitted a review, later dismissed
LGTM!

2023-03-18 07:10 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[refersion_1410.pdf](https://github.com/PipedreamHQ/pipedream/files/11007753/refersion_1410.pdf)

2023-03-20 11:56 UTC, vellames commented
/approve

2023-03-20 13:23 UTC, luancazarine approved these changes

2023-03-20 13:43 UTC, vellames commented
/approve

2023-03-20 13:44 UTC, luancazarine approved these changes

2023-03-20 13:47 UTC, closed without merging