Smartsheet - New Components
PipedreamHQ/pipedream pull request #5917
Opened 2023-04-03 19:11 UTC by michelle0927

Resolves #3785

2023-04-04 12:29 UTC, andrewjschuang reviewed
Thanks, looks good overall but we need to figure out a way to work around `additionalProps` for custom expressions. Can you think of a way?

2023-04-04 12:29 UTC, andrewjschuang commented on components/smartsheet/actions/update-row/update-row.mjs
> +  async additionalProps() {
See comment above for `additionalProps`

2023-04-04 12:29 UTC, andrewjschuang commented on components/smartsheet/actions/update-row/update-row.mjs
> +    /* eslint-disable no-unused-vars */
Is there a reason for `/* eslint-disable no-unused-vars */` to be here?

2023-04-04 18:21 UTC, michelle0927 commented on components/smartsheet/actions/add-row-to-sheet/add-row-to-sheet.mjs
> +  async additionalProps() {
I added a `cells` prop that allows the user to manually enter the column values in case `sheetId` is entered as a custom expression.

2023-04-05 12:03 UTC, andrewjschuang requested changes
Thanks for adding the cells prop!

Just a few questions regarding the use of `isNan()`:
- What does the API return if `sheetId` or `rowId` is not a number?
- Would it be better to `throw ConfigurationError` instead of returning a empty array?
- I think we could create a function `validateId` that receives an `id` and checks if it's a number or not. And this function is called in `getRow`, `getSheet`, `listColumns`, `createSheetInFolder`, etc. So the logic is contained inside the method that makes the request and not outside

2023-04-05 12:03 UTC, andrewjschuang commented on components/smartsheet/smartsheet.app.mjs
> +      type: "string",
```suggestion
      type: "integer",
```

Should this be of type integer?

2023-04-05 12:03 UTC, andrewjschuang commented on components/smartsheet/smartsheet.app.mjs
> +      type: "string",
```suggestion
      type: "integer",
```

Should this be of type integer?

2023-04-05 12:03 UTC, andrewjschuang commented on components/smartsheet/smartsheet.app.mjs
> +      type: "string",
```suggestion
      type: "integer",
```

Should this be of type integer?

2023-04-05 12:03 UTC, andrewjschuang commented on components/smartsheet/smartsheet.app.mjs
> +      type: "string",
```suggestion
      type: "integer",
```

Should this be of type integer?

2023-04-05 15:56 UTC, michelle0927 commented
> Thanks for adding the cells prop!
> 
> Just a few questions regarding the use of `isNan()`:
> 
> * What does the API return if `sheetId` or `rowId` is not a number?
> * Would it be better to `throw ConfigurationError` instead of returning a empty array?
> * I think we could create a function `validateId` that receives an `id` and checks if it's a number or not. And this function is called in `getRow`, `getSheet`, `listColumns`, `createSheetInFolder`, etc. So the logic is contained inside the method that makes the request and not outside

I wanted to allow the user to enter custom expressions instead of selecting async options, as you suggested. If a custom expression was entered for `sheetId`, it would try to put the expression in as a path parameter and result in an error. Similarly, the `additionalProps` sections would get errors if `sheetId` or `rowId` were entered as custom expressions. 

My intent with `isNan()` was to use it as a way to detect if a custom expression has been entered, and if so, allow the user to use the components without getting errors. There's probably a better way to do that though, so if you have an idea, let me know and I'll update it.

2023-04-05 18:32 UTC, andrewjschuang submitted a review, later dismissed
Thanks, LGTM!

For some reason I can't create an account to see how the props work - @vunguyenhung can you please verify if it is suitable when QAing?

2023-04-06 15:06 UTC, vunguyenhung commented
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Smartsheet_5917_2206.pdf](https://github.com/PipedreamHQ/pipedream/files/11171941/Smartsheet_5917_2206.pdf)

2023-04-06 16:03 UTC, andrewjschuang approved these changes

2023-04-06 16:04 UTC, merged