[Nordigen] Can now select multiple scopes
PipedreamHQ/pipedream pull request #6239
Opened 2023-05-03 19:15 UTC by LucBerge

Possibility to select multiple scopes when creating a requisition link

2023-05-03 19:16 UTC, pipedream-component-development commented
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

2023-05-03 19:16 UTC, pipedream-component-development commented
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

2023-05-03 19:16 UTC, dylburger commented on components/nordigen/actions/create-requisition-link/create-requisition-link.mjs
> +  version: "0.0.2",
```suggestion
  version: "0.0.2",
```

2023-05-03 19:16 UTC, dylburger commented on components/nordigen/actions/create-requisition-link/create-requisition-link.mjs
> +  version: "0.0.2",
Google's Developer docs style guide: Use double quotes for strings.

2023-05-03 19:16 UTC, dylburger commented on components/nordigen/actions/create-requisition-link/create-requisition-link.mjs
> +      accessScope: this.accessScope,
```suggestion
      accessScope: this.accessScope,
```

2023-05-03 19:16 UTC, dylburger commented on components/nordigen/actions/create-requisition-link/create-requisition-link.mjs
> +      accessScope: this.accessScope,
Google's Developer docs style guide: Use double quotes for strings.

2023-05-03 19:16 UTC, dylburger commented on components/nordigen/nordigen.app.mjs
> +      type: "string[]",
```suggestion
      type: "string[]",
```

2023-05-03 19:16 UTC, dylburger commented on components/nordigen/nordigen.app.mjs
> +      type: "string[]",
Google's Developer docs style guide: Use double quotes for strings.

2023-05-03 19:26 UTC, alysonturing requested changes
@LucBerge  You need to increment the version of 7 component(s). Please see [this output](https://github.com/PipedreamHQ/pipedream/actions/runs/4875680165/jobs/8698192390?pr=6239) and https://pipedream.com/docs/components/guidelines/#versioning for more information.

2023-05-04 18:28 UTC, michelle0927 commented
Testing passed. Ready for release!

Test report
[Nordigen_6239.pdf](https://github.com/PipedreamHQ/pipedream/files/11400308/Nordigen_6239.pdf)

2023-05-04 18:32 UTC, merged